export enum MarketType {
    // Winner
    WINNER = 0,
    // Winner with draw - for hockey
    WINNER2 = 10011,
    // Winner (placeholder)
    WINNER3 = 10012,
    // Winner period - half for soccer, quarter for basketball
    FIRST_PERIOD_WINNER = 10021,
    SECOND_PERIOD_WINNER = 10022,
    THIRD_PERIOD_WINNER = 10023,
    FOURTH_PERIOD_WINNER = 10024,
    FIFTH_PERIOD_WINNER = 10025,
    SIXTH_PERIOD_WINNER = 10026,
    SEVENTH_PERIOD_WINNER = 10027,
    EIGHTH_PERIOD_WINNER = 10028,
    NINTH_PERIOD_WINNER = 10029,
    // Winner period - half for basketball
    FIRST_PERIOD_WINNER2 = 10051,
    SECOND_PERIOD_WINNER2 = 10052,
    THIRD_PERIOD_WINNER2 = 10053,
    FOURTH_PERIOD_WINNER2 = 10054,
    FIFTH_PERIOD_WINNER2 = 10055,
    SIXTH_PERIOD_WINNER2 = 10056,
    SEVENTH_PERIOD_WINNER2 = 10057,
    EIGHTH_PERIOD_WINNER2 = 10058,
    NINTH_PERIOD_WINNER2 = 10059,

    // Spread (handicap)
    SPREAD = 10001,
    // Spread (handicap) - sets for tennis
    SPREAD2 = 10013,
    // Spread period - half for soccer, quarter for basketball
    FIRST_PERIOD_SPREAD = 10041,
    SECOND_PERIOD_SPREAD = 10042,
    THIRD_PERIOD_SPREAD = 10043,
    FOURTH_PERIOD_SPREAD = 10044,
    FIFTH_PERIOD_SPREAD = 10045,
    SIXTH_PERIOD_SPREAD = 10046,
    SEVENTH_PERIOD_SPREAD = 10047,
    EIGHTH_PERIOD_SPREAD = 10048,
    NINTH_PERIOD_SPREAD = 10049,
    // Spread period - half for basketball
    FIRST_PERIOD_SPREAD2 = 10071,
    SECOND_PERIOD_SPREAD2 = 10072,
    THIRD_PERIOD_SPREAD2 = 10073,
    FOURTH_PERIOD_SPREAD2 = 10074,
    FIFTH_PERIOD_SPREAD2 = 10075,
    SIXTH_PERIOD_SPREAD2 = 10076,
    SEVENTH_PERIOD_SPREAD2 = 10077,
    EIGHTH_PERIOD_SPREAD2 = 10078,
    NINTH_PERIOD_SPREAD2 = 10079,

    // Total
    TOTAL = 10002,
    // Total - sets for tennis
    TOTAL2 = 10014,
    // Total period - half for soccer, quarter for basketball
    FIRST_PERIOD_TOTAL = 10031,
    SECOND_PERIOD_TOTAL = 10032,
    THIRD_PERIOD_TOTAL = 10033,
    FOURTH_PERIOD_TOTAL = 10034,
    FIFTH_PERIOD_TOTAL = 10035,
    SIXTH_PERIOD_TOTAL = 10036,
    SEVENTH_PERIOD_TOTAL = 10037,
    EIGHTH_PERIOD_TOTAL = 10038,
    NINTH_PERIOD_TOTAL = 10039,
    // Total period - half for basketball
    FIRST_PERIOD_TOTAL2 = 10061,
    SECOND_PERIOD_TOTAL2 = 10062,
    THIRD_PERIOD_TOTAL2 = 10063,
    FOURTH_PERIOD_TOTAL2 = 10064,
    FIFTH_PERIOD_TOTAL2 = 10065,
    SIXTH_PERIOD_TOTAL2 = 10066,
    SEVENTH_PERIOD_TOTAL2 = 10067,
    EIGHTH_PERIOD_TOTAL2 = 10068,
    NINTH_PERIOD_TOTAL2 = 10069,
    // Total per team
    TOTAL_HOME_TEAM = 10017,
    TOTAL_AWAY_TEAM = 10018,
    // Total per team period - half for soccer
    FIRST_PERIOD_HOME_TEAM = 10111,
    FIRST_PERIOD_AWAY_TEAM = 10112,
    SECOND_PERIOD_HOME_TEAM = 10211,
    SECOND_PERIOD_AWAY_TEAM = 10212,

    // Total odd/even
    TOTAL_ODD_EVEN = 10005,
    // Total odd/even period - half for soccer, quarter for basketball
    FIRST_PERIOD_TOTAL_ODD_EVEN = 10081,
    SECOND_PERIOD_TOTAL_ODD_EVEN = 10082,
    THIRD_PERIOD_TOTAL_ODD_EVEN = 10083,
    FOURTH_PERIOD_TOTAL_ODD_EVEN = 10084,
    FIFTH_PERIOD_TOTAL_ODD_EVEN = 10085,
    SIXTH_PERIOD_TOTAL_ODD_EVEN = 10086,
    SEVENTH_PERIOD_TOTAL_ODD_EVEN = 10087,
    EIGHTH_PERIOD_TOTAL_ODD_EVEN = 10088,
    NINTH_PERIOD_TOTAL_ODD_EVEN = 10089,
    // Total odd/even period - half for basketball
    FIRST_PERIOD_TOTAL2_ODD_EVEN = 10091,
    SECOND_PERIOD_TOTAL2_ODD_EVEN = 10092,
    THIRD_PERIOD_TOTAL2_ODD_EVEN = 10093,
    FOURTH_PERIOD_TOTAL2_ODD_EVEN = 10094,
    FIFTH_PERIOD_TOTAL2_ODD_EVEN = 10095,
    SIXTH_PERIOD_TOTAL2_ODD_EVEN = 10096,
    SEVENTH_PERIOD_TOTAL2_ODD_EVEN = 10097,
    EIGHTH_PERIOD_TOTAL2_ODD_EVEN = 10098,
    NINTH_PERIOD_TOTAL2_ODD_EVEN = 10099,

    // Double chance
    DOUBLE_CHANCE = 10003,
    // Double chance period - half for soccer
    FIRST_PERIOD_DOUBLE_CHANCE = 10015,
    SECOND_PERIOD_DOUBLE_CHANCE = 10016,

    // Both teams to score
    BOTH_TEAMS_TO_SCORE = 10009,
    // Both teams to score period - half for soccer
    FIRST_PERIOD_BOTH_TEAMS_TO_SCORE = 10101,
    SECOND_PERIOD_BOTH_TEAMS_TO_SCORE = 10102,
    THIRD_PERIOD_BOTH_TEAMS_TO_SCORE = 10103,
    FOURTH_PERIOD_BOTH_TEAMS_TO_SCORE = 10104,
    FIFTH_PERIOD_BOTH_TEAMS_TO_SCORE = 10105,
    SIXTH_PERIOD_BOTH_TEAMS_TO_SCORE = 10106,
    SEVENTH_PERIOD_BOTH_TEAMS_TO_SCORE = 10107,
    EIGHTH_PERIOD_BOTH_TEAMS_TO_SCORE = 10108,
    NINTH_PERIOD_BOTH_TEAMS_TO_SCORE = 10109,

    // Combined positions
    WINNER_TOTAL = 10004,
    HALFTIME_FULLTIME = 10006,
    GOALS = 10007,
    HALFTIME_FULLTIME_GOALS = 10008,

    // Player props
    PLAYER_PROPS_HOMERUNS = 11010,
    PLAYER_PROPS_STRIKEOUTS = 11019,
    PLAYER_PROPS_PASSING_YARDS = 11051,
    PLAYER_PROPS_PASSING_TOUCHDOWNS = 11052,
    PLAYER_PROPS_RUSHING_YARDS = 11053,
    PLAYER_PROPS_RECEIVING_YARDS = 11057,
    PLAYER_PROPS_TOUCHDOWNS = 11055,
    PLAYER_PROPS_FIELD_GOALS_MADE = 11060,
    PLAYER_PROPS_PITCHER_HITS_ALLOWED = 11047,
    PLAYER_PROPS_POINTS = 11029,
    PLAYER_PROPS_SHOTS = 11097,
    PLAYER_PROPS_GOALS = 11086,
    PLAYER_PROPS_HITS_RECORDED = 11012,
    PLAYER_PROPS_REBOUNDS = 11035,
    PLAYER_PROPS_ASSISTS = 11039,
    PLAYER_PROPS_DOUBLE_DOUBLE = 11087,
    PLAYER_PROPS_TRIPLE_DOUBLE = 11088,
    PLAYER_PROPS_RECEPTIONS = 11058,
    PLAYER_PROPS_FIRST_TOUCHDOWN = 11049,
    PLAYER_PROPS_LAST_TOUCHDOWN = 11056,
    PLAYER_PROPS_3PTS_MADE = 11038,
}

export enum MarketTypeGroup {
    TOTALS = 'Totals',
    HANDICAP = 'Handicap',
}

export enum ParlayErrorCode {
    NO_ERROS = 0,
    MAX_MATCHES = 1,
    SAME_TEAM_TWICE = 2,
    MAX_DOUBLE_CHANCES = 3,
    MAX_COMBINED_MARKETS = 4,
    MAX_NUMBER_OF_MARKETS_WITH_COMBINED_MARKETS = 5,
    SAME_EVENT_PARTICIPANT = 6,
    UNIQUE_TOURNAMENT_PLAYERS = 7,
    ADDING_PLAYER_PROPS_ALREADY_HAVE_POSITION_OF_SAME_MARKET = 8,
    SAME_GAME_OTHER_PLAYER_PROPS_TYPE = 9,
    COMBINE_REGULAR_WITH_COMBINED_POSITIONS = 10,
}

export const PLAYER_PROPS_MARKET_TYPES = [
    MarketType.PLAYER_PROPS_HOMERUNS,
    MarketType.PLAYER_PROPS_STRIKEOUTS,
    MarketType.PLAYER_PROPS_PASSING_YARDS,
    MarketType.PLAYER_PROPS_PASSING_TOUCHDOWNS,
    MarketType.PLAYER_PROPS_RUSHING_YARDS,
    MarketType.PLAYER_PROPS_RECEIVING_YARDS,
    MarketType.PLAYER_PROPS_TOUCHDOWNS,
    MarketType.PLAYER_PROPS_FIELD_GOALS_MADE,
    MarketType.PLAYER_PROPS_PITCHER_HITS_ALLOWED,
    MarketType.PLAYER_PROPS_POINTS,
    MarketType.PLAYER_PROPS_SHOTS,
    MarketType.PLAYER_PROPS_GOALS,
    MarketType.PLAYER_PROPS_HITS_RECORDED,
    MarketType.PLAYER_PROPS_REBOUNDS,
    MarketType.PLAYER_PROPS_ASSISTS,
    MarketType.PLAYER_PROPS_DOUBLE_DOUBLE,
    MarketType.PLAYER_PROPS_TRIPLE_DOUBLE,
    MarketType.PLAYER_PROPS_RECEPTIONS,
    MarketType.PLAYER_PROPS_FIRST_TOUCHDOWN,
    MarketType.PLAYER_PROPS_LAST_TOUCHDOWN,
    MarketType.PLAYER_PROPS_3PTS_MADE,
];

export const ONE_SIDE_PLAYER_PROPS_MARKET_TYPES = [
    MarketType.PLAYER_PROPS_TOUCHDOWNS,
    MarketType.PLAYER_PROPS_GOALS,
    MarketType.PLAYER_PROPS_FIRST_TOUCHDOWN,
    MarketType.PLAYER_PROPS_LAST_TOUCHDOWN,
];

export const YES_NO_PLAYER_PROPS_MARKET_TYPES = [
    MarketType.PLAYER_PROPS_DOUBLE_DOUBLE,
    MarketType.PLAYER_PROPS_TRIPLE_DOUBLE,
];

export const TOTAL_MARKET_TYPES = [
    MarketType.TOTAL,
    MarketType.TOTAL2,
    MarketType.TOTAL_HOME_TEAM,
    MarketType.TOTAL_AWAY_TEAM,
    MarketType.FIRST_PERIOD_TOTAL,
    MarketType.SECOND_PERIOD_TOTAL2,
    MarketType.THIRD_PERIOD_TOTAL,
    MarketType.FOURTH_PERIOD_TOTAL,
    MarketType.FIFTH_PERIOD_TOTAL,
    MarketType.SIXTH_PERIOD_TOTAL,
    MarketType.SEVENTH_PERIOD_TOTAL,
    MarketType.EIGHTH_PERIOD_TOTAL,
    MarketType.NINTH_PERIOD_TOTAL,
    MarketType.FIRST_PERIOD_TOTAL2,
    MarketType.SECOND_PERIOD_TOTAL2,
    MarketType.THIRD_PERIOD_TOTAL2,
    MarketType.FOURTH_PERIOD_TOTAL2,
    MarketType.FIFTH_PERIOD_TOTAL2,
    MarketType.SIXTH_PERIOD_TOTAL2,
    MarketType.SEVENTH_PERIOD_TOTAL2,
    MarketType.EIGHTH_PERIOD_TOTAL2,
    MarketType.NINTH_PERIOD_TOTAL2,
    MarketType.FIRST_PERIOD_HOME_TEAM,
    MarketType.FIRST_PERIOD_AWAY_TEAM,
    MarketType.SECOND_PERIOD_HOME_TEAM,
    MarketType.SECOND_PERIOD_AWAY_TEAM,
];

export const TOTAL_ODD_EVEN_MARKET_TYPES = [
    MarketType.TOTAL_ODD_EVEN,
    MarketType.FIRST_PERIOD_TOTAL_ODD_EVEN,
    MarketType.SECOND_PERIOD_TOTAL_ODD_EVEN,
    MarketType.THIRD_PERIOD_TOTAL_ODD_EVEN,
    MarketType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
    MarketType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
    MarketType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
    MarketType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
    MarketType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
    MarketType.NINTH_PERIOD_TOTAL_ODD_EVEN,
    MarketType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
    MarketType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
    MarketType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
    MarketType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
    MarketType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
    MarketType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
    MarketType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
    MarketType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
    MarketType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
];

export const SPREAD_MARKET_TYPES = [
    MarketType.SPREAD,
    MarketType.SPREAD2,
    MarketType.FIRST_PERIOD_SPREAD,
    MarketType.SECOND_PERIOD_SPREAD,
    MarketType.THIRD_PERIOD_SPREAD,
    MarketType.FOURTH_PERIOD_SPREAD,
    MarketType.FIFTH_PERIOD_SPREAD,
    MarketType.SIXTH_PERIOD_SPREAD,
    MarketType.SEVENTH_PERIOD_SPREAD,
    MarketType.EIGHTH_PERIOD_SPREAD,
    MarketType.NINTH_PERIOD_SPREAD,
    MarketType.FIRST_PERIOD_SPREAD2,
    MarketType.SECOND_PERIOD_SPREAD2,
    MarketType.THIRD_PERIOD_SPREAD2,
    MarketType.FOURTH_PERIOD_SPREAD2,
    MarketType.FIFTH_PERIOD_SPREAD2,
    MarketType.SIXTH_PERIOD_SPREAD2,
    MarketType.SEVENTH_PERIOD_SPREAD2,
    MarketType.EIGHTH_PERIOD_SPREAD2,
    MarketType.NINTH_PERIOD_SPREAD2,
];

export const COMBINED_POSITIONS_MARKET_TYPES = [
    MarketType.WINNER_TOTAL,
    MarketType.HALFTIME_FULLTIME,
    MarketType.GOALS,
    MarketType.HALFTIME_FULLTIME_GOALS,
];

export const WINNER_MARKET_TYPES = [
    MarketType.WINNER,
    MarketType.WINNER2,
    MarketType.WINNER3,
    MarketType.FIRST_PERIOD_WINNER,
    MarketType.SECOND_PERIOD_WINNER,
    MarketType.THIRD_PERIOD_WINNER,
    MarketType.FOURTH_PERIOD_WINNER,
    MarketType.FIFTH_PERIOD_WINNER,
    MarketType.SIXTH_PERIOD_WINNER,
    MarketType.SEVENTH_PERIOD_WINNER,
    MarketType.EIGHTH_PERIOD_WINNER,
    MarketType.NINTH_PERIOD_WINNER,
    MarketType.FIRST_PERIOD_WINNER2,
    MarketType.SECOND_PERIOD_WINNER2,
    MarketType.THIRD_PERIOD_WINNER2,
    MarketType.FOURTH_PERIOD_WINNER2,
    MarketType.FIFTH_PERIOD_WINNER2,
    MarketType.SIXTH_PERIOD_WINNER2,
    MarketType.SEVENTH_PERIOD_WINNER2,
    MarketType.EIGHTH_PERIOD_WINNER2,
    MarketType.NINTH_PERIOD_WINNER2,
];

export const BOTH_TEAMS_TO_SCORE_MARKET_TYPES = [
    MarketType.BOTH_TEAMS_TO_SCORE,
    MarketType.FIRST_PERIOD_BOTH_TEAMS_TO_SCORE,
    MarketType.SECOND_PERIOD_BOTH_TEAMS_TO_SCORE,
    MarketType.THIRD_PERIOD_BOTH_TEAMS_TO_SCORE,
    MarketType.FOURTH_PERIOD_BOTH_TEAMS_TO_SCORE,
    MarketType.FIFTH_PERIOD_BOTH_TEAMS_TO_SCORE,
    MarketType.SIXTH_PERIOD_BOTH_TEAMS_TO_SCORE,
    MarketType.SEVENTH_PERIOD_BOTH_TEAMS_TO_SCORE,
    MarketType.EIGHTH_PERIOD_BOTH_TEAMS_TO_SCORE,
    MarketType.NINTH_PERIOD_BOTH_TEAMS_TO_SCORE,
];

export const DOUBLE_CHANCE_MARKET_TYPES = [
    MarketType.DOUBLE_CHANCE,
    MarketType.FIRST_PERIOD_DOUBLE_CHANCE,
    MarketType.SECOND_PERIOD_DOUBLE_CHANCE,
];
