import { BracketMatch, MarchMadTeam } from 'types/marchMadness';

export const NCAA_BASKETBALL_LEAGU_TAG = 9005;

export const NUMBER_OF_MATCHES = 63;
export const NUMBER_OF_TEAMS = 64;
export const NUMBER_OF_ROUNDS = 6;

export const FIRST_ROUND_EAST_MATCH_IDS = [0, 1, 2, 3, 4, 5, 6, 7];
export const FIRST_ROUND_WEST_MATCH_IDS = [8, 9, 10, 11, 12, 13, 14, 15];
export const FIRST_ROUND_SOUTH_MATCH_IDS = [16, 17, 18, 19, 20, 21, 22, 23];
export const FIRST_ROUND_MIDWEST_MATCH_IDS = [24, 25, 26, 27, 28, 29, 30, 31];
export const FIRST_ROUND_MATCH_IDS = [
    ...FIRST_ROUND_EAST_MATCH_IDS,
    ...FIRST_ROUND_WEST_MATCH_IDS,
    ...FIRST_ROUND_SOUTH_MATCH_IDS,
    ...FIRST_ROUND_MIDWEST_MATCH_IDS,
];

export const SECOND_ROUND_EAST_MATCH_IDS = [32, 33, 34, 35];
export const SECOND_ROUND_WEST_MATCH_IDS = [36, 37, 38, 39];
export const SECOND_ROUND_SOUTH_MATCH_IDS = [40, 41, 42, 43];
export const SECOND_ROUND_MIDWEST_MATCH_IDS = [44, 45, 46, 47];
export const SECOND_ROUND_MATCH_IDS = [
    ...SECOND_ROUND_EAST_MATCH_IDS,
    ...SECOND_ROUND_WEST_MATCH_IDS,
    ...SECOND_ROUND_SOUTH_MATCH_IDS,
    ...SECOND_ROUND_MIDWEST_MATCH_IDS,
];

export const SWEET16_ROUND_EAST_MATCH_IDS = [48, 49];
export const SWEET16_ROUND_WEST_MATCH_IDS = [50, 51];
export const SWEET16_ROUND_SOUTH_MATCH_IDS = [52, 53];
export const SWEET16_ROUND_MIDWEST_MATCH_IDS = [54, 55];
export const SWEET16_ROUND_MATCH_IDS = [
    ...SWEET16_ROUND_EAST_MATCH_IDS,
    ...SWEET16_ROUND_WEST_MATCH_IDS,
    ...SWEET16_ROUND_SOUTH_MATCH_IDS,
    ...SWEET16_ROUND_MIDWEST_MATCH_IDS,
];

export const ELITE8_ROUND_EAST_MATCH_ID = 56;
export const ELITE8_ROUND_WEST_MATCH_ID = 57;
export const ELITE8_ROUND_SOUTH_MATCH_ID = 58;
export const ELITE8_ROUND_MIDWEST_MATCH_ID = 59;
export const ELITE8_ROUND_MATCH_IDS = [
    ELITE8_ROUND_EAST_MATCH_ID,
    ELITE8_ROUND_WEST_MATCH_ID,
    ELITE8_ROUND_SOUTH_MATCH_ID,
    ELITE8_ROUND_MIDWEST_MATCH_ID,
];

export const SEMI_FINAL_EAST_WEST_MATCH_ID = 60;
export const SEMI_FINAL_SOUTH_MIDWEST_MATCH_ID = 61;
export const SEMI_FINAL_MATCH_IDS = [SEMI_FINAL_EAST_WEST_MATCH_ID, SEMI_FINAL_SOUTH_MIDWEST_MATCH_ID];

export const FINAL_MATCH_ID = 62;

export const initialBracketsData: BracketMatch[] = [
    {
        id: 0,
        homeTeamId: 1,
        awayTeamId: 16,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'East',
        round: 'First',
    },
    {
        id: 1,
        homeTeamId: 8,
        awayTeamId: 9,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'East',
        round: 'First',
    },
    {
        id: 2,
        homeTeamId: 5,
        awayTeamId: 12,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'East',
        round: 'First',
    },
    {
        id: 3,
        homeTeamId: 4,
        awayTeamId: 13,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'East',
        round: 'First',
    },
    {
        id: 4,
        homeTeamId: 6,
        awayTeamId: 11,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'East',
        round: 'First',
    },
    {
        id: 5,
        homeTeamId: 3,
        awayTeamId: 14,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'East',
        round: 'First',
    },
    {
        id: 6,
        homeTeamId: 7,
        awayTeamId: 10,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'East',
        round: 'First',
    },
    {
        id: 7,
        homeTeamId: 2,
        awayTeamId: 15,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'East',
        round: 'First',
    },
    {
        id: 8,
        homeTeamId: 17,
        awayTeamId: 32,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'West',
        round: 'First',
    },
    {
        id: 9,
        homeTeamId: 24,
        awayTeamId: 25,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'West',
        round: 'First',
    },
    {
        id: 10,
        homeTeamId: 21,
        awayTeamId: 28,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'West',
        round: 'First',
    },
    {
        id: 11,
        homeTeamId: 20,
        awayTeamId: 29,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'West',
        round: 'First',
    },
    {
        id: 12,
        homeTeamId: 22,
        awayTeamId: 27,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'West',
        round: 'First',
    },
    {
        id: 13,
        homeTeamId: 19,
        awayTeamId: 30,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'West',
        round: 'First',
    },
    {
        id: 14,
        homeTeamId: 23,
        awayTeamId: 26,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'West',
        round: 'First',
    },
    {
        id: 15,
        homeTeamId: 18,
        awayTeamId: 31,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'West',
        round: 'First',
    },
    {
        id: 16,
        homeTeamId: 33,
        awayTeamId: 48,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'South',
        round: 'First',
    },
    {
        id: 17,
        homeTeamId: 40,
        awayTeamId: 41,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'South',
        round: 'First',
    },
    {
        id: 18,
        homeTeamId: 37,
        awayTeamId: 44,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'South',
        round: 'First',
    },
    {
        id: 19,
        homeTeamId: 36,
        awayTeamId: 45,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'South',
        round: 'First',
    },
    {
        id: 20,
        homeTeamId: 38,
        awayTeamId: 43,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'South',
        round: 'First',
    },
    {
        id: 21,
        homeTeamId: 35,
        awayTeamId: 46,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'South',
        round: 'First',
    },
    {
        id: 22,
        homeTeamId: 39,
        awayTeamId: 42,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'South',
        round: 'First',
    },
    {
        id: 23,
        homeTeamId: 34,
        awayTeamId: 47,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'South',
        round: 'First',
    },
    {
        id: 24,
        homeTeamId: 49,
        awayTeamId: 64,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'Midwest',
        round: 'First',
    },
    {
        id: 25,
        homeTeamId: 56,
        awayTeamId: 57,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'Midwest',
        round: 'First',
    },
    {
        id: 26,
        homeTeamId: 53,
        awayTeamId: 60,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'Midwest',
        round: 'First',
    },
    {
        id: 27,
        homeTeamId: 52,
        awayTeamId: 61,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'Midwest',
        round: 'First',
    },
    {
        id: 28,
        homeTeamId: 54,
        awayTeamId: 59,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'Midwest',
        round: 'First',
    },
    {
        id: 29,
        homeTeamId: 51,
        awayTeamId: 62,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'Midwest',
        round: 'First',
    },
    {
        id: 30,
        homeTeamId: 55,
        awayTeamId: 58,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'Midwest',
        round: 'First',
    },
    {
        id: 31,
        homeTeamId: 50,
        awayTeamId: 63,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
        region: 'Midwest',
        round: 'First',
    },
    {
        id: 32,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 0,
        awayTeamParentMatchId: 1,
        region: 'East',
        round: 'Second',
    },
    {
        id: 33,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 2,
        awayTeamParentMatchId: 3,
        region: 'East',
        round: 'Second',
    },
    {
        id: 34,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 4,
        awayTeamParentMatchId: 5,
        region: 'East',
        round: 'Second',
    },
    {
        id: 35,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 6,
        awayTeamParentMatchId: 7,
        region: 'East',
        round: 'Second',
    },
    {
        id: 36,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 8,
        awayTeamParentMatchId: 9,
        region: 'West',
        round: 'Second',
    },
    {
        id: 37,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 10,
        awayTeamParentMatchId: 11,
        region: 'West',
        round: 'Second',
    },
    {
        id: 38,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 12,
        awayTeamParentMatchId: 13,
        region: 'West',
        round: 'Second',
    },
    {
        id: 39,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 14,
        awayTeamParentMatchId: 15,
        region: 'West',
        round: 'Second',
    },
    {
        id: 40,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 16,
        awayTeamParentMatchId: 17,
        region: 'South',
        round: 'Second',
    },
    {
        id: 41,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 18,
        awayTeamParentMatchId: 19,
        region: 'South',
        round: 'Second',
    },
    {
        id: 42,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 20,
        awayTeamParentMatchId: 21,
        region: 'South',
        round: 'Second',
    },
    {
        id: 43,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 22,
        awayTeamParentMatchId: 23,
        region: 'South',
        round: 'Second',
    },
    {
        id: 44,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 24,
        awayTeamParentMatchId: 25,
        region: 'Midwest',
        round: 'Second',
    },
    {
        id: 45,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 26,
        awayTeamParentMatchId: 27,
        region: 'Midwest',
        round: 'Second',
    },
    {
        id: 46,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 28,
        awayTeamParentMatchId: 29,
        region: 'Midwest',
        round: 'Second',
    },
    {
        id: 47,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 30,
        awayTeamParentMatchId: 31,
        region: 'Midwest',
        round: 'Second',
    },
    {
        id: 48,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 32,
        awayTeamParentMatchId: 33,
        region: 'East',
        round: 'Sweet16',
    },
    {
        id: 49,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 34,
        awayTeamParentMatchId: 35,
        region: 'East',
        round: 'Sweet16',
    },
    {
        id: 50,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 36,
        awayTeamParentMatchId: 37,
        region: 'West',
        round: 'Sweet16',
    },
    {
        id: 51,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 38,
        awayTeamParentMatchId: 39,
        region: 'West',
        round: 'Sweet16',
    },
    {
        id: 52,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 40,
        awayTeamParentMatchId: 41,
        region: 'South',
        round: 'Sweet16',
    },
    {
        id: 53,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 42,
        awayTeamParentMatchId: 43,
        region: 'South',
        round: 'Sweet16',
    },
    {
        id: 54,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 44,
        awayTeamParentMatchId: 45,
        region: 'Midwest',
        round: 'Sweet16',
    },
    {
        id: 55,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 46,
        awayTeamParentMatchId: 47,
        region: 'Midwest',
        round: 'Sweet16',
    },
    {
        id: 56,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 48,
        awayTeamParentMatchId: 49,
        region: 'East',
        round: 'Elite8',
    },
    {
        id: 57,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 50,
        awayTeamParentMatchId: 51,
        region: 'West',
        round: 'Elite8',
    },
    {
        id: 58,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 52,
        awayTeamParentMatchId: 53,
        region: 'South',
        round: 'Elite8',
    },
    {
        id: 59,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 54,
        awayTeamParentMatchId: 55,
        region: 'Midwest',
        round: 'Elite8',
    },
    {
        id: 60,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 56,
        awayTeamParentMatchId: 57,
        region: 'East-West',
        round: 'SemiFinal',
    },
    {
        id: 61,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 58,
        awayTeamParentMatchId: 59,
        region: 'South-Midwest',
        round: 'SemiFinal',
    },
    {
        id: 62,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 60,
        awayTeamParentMatchId: 61,
        region: 'East-West-South-Midwest',
        round: 'Final',
    },
];

// TODO: Populate after draw only name and displayName by region and position.
// Name is used for searching logo and displayName for showing team name on UI.
// Update also Wild Card when first four games are played.
export const teamsData: MarchMadTeam[] = [
    {
        id: 1,
        name: 'Purdue Boilermakers',
        displayName: 'Purdue',
        region: 'East',
        position: 1,
    },
    {
        id: 2,
        name: 'Kansas State Wildcats',
        displayName: 'Kansas St.',
        region: 'East',
        position: 2,
    },
    {
        id: 3,
        name: 'Tennessee Volunteers',
        displayName: 'Tennessee',
        region: 'East',
        position: 3,
    },
    {
        id: 4,
        name: 'Virginia Cavaliers',
        displayName: 'Virginia',
        region: 'East',
        position: 4,
    },
    {
        id: 5,
        name: 'Creighton Blue Jays',
        displayName: 'Creighton',
        region: 'East',
        position: 5,
    },
    {
        id: 6,
        name: 'San Diego State Aztecs',
        displayName: 'San Diego St.',
        region: 'East',
        position: 6,
    },
    {
        id: 7,
        name: 'Michigan State Spartans',
        displayName: 'Michigan St.',
        region: 'East',
        position: 7,
    },
    {
        id: 8,
        name: 'Kentucky Wildcats',
        displayName: 'Kentucky',
        region: 'East',
        position: 8,
    },
    {
        id: 9,
        name: 'Boise State Broncos',
        displayName: 'Boise St.',
        region: 'East',
        position: 9,
    },
    {
        id: 10,
        name: 'Pittsburgh Panthers',
        displayName: 'Pittsburgh',
        region: 'East',
        position: 10,
    },
    {
        id: 11,
        name: 'West Virginia Mountaineers',
        displayName: 'West Virginia',
        region: 'East',
        position: 11,
    },
    {
        id: 12,
        name: 'Vcu Rams',
        displayName: 'Vcu',
        region: 'East',
        position: 12,
    },
    {
        id: 13,
        name: 'Utah Valley Wolverines',
        displayName: 'Utah Valley',
        region: 'East',
        position: 13,
    },
    {
        id: 14,
        name: 'Eastern Washington Eagles',
        displayName: 'Eastern Washington',
        region: 'East',
        position: 14,
    },
    {
        id: 15,
        name: 'Vermont Catamounts',
        displayName: 'Vermont',
        region: 'East',
        position: 15,
    },
    {
        id: 16,
        name: '',
        displayName: 'Wild Card',
        region: 'East',
        position: 16,
    },
    {
        id: 17,
        name: 'Kansas Jayhawks',
        displayName: 'Kansas',
        region: 'West',
        position: 1,
    },
    {
        id: 18,
        name: 'Ucla Bruins',
        displayName: 'Ucla',
        region: 'West',
        position: 2,
    },
    {
        id: 19,
        name: 'Gonzaga Bulldogs',
        displayName: 'Gonzaga',
        region: 'West',
        position: 3,
    },
    {
        id: 20,
        name: 'Uconn Huskies',
        displayName: 'Uconn',
        region: 'West',
        position: 4,
    },
    {
        id: 21,
        name: "Saint Mary's Gaels",
        displayName: "Saint Mary's",
        region: 'West',
        position: 5,
    },
    {
        id: 22,
        name: 'Tcu Horned Frogs',
        displayName: 'Tcu',
        region: 'West',
        position: 6,
    },
    {
        id: 23,
        name: 'Maryland Terrapins',
        displayName: 'Maryland',
        region: 'West',
        position: 7,
    },
    {
        id: 24,
        name: 'Arkansas Razorbacks',
        displayName: 'Arkansas',
        region: 'West',
        position: 8,
    },
    {
        id: 25,
        name: 'Illinois Fighting Illini',
        displayName: 'Illinois',
        region: 'West',
        position: 9,
    },
    {
        id: 26,
        name: 'Auburn Tigers',
        displayName: 'Auburn',
        region: 'West',
        position: 10,
    },
    {
        id: 27,
        name: '',
        displayName: 'Wild Card',
        region: 'West',
        position: 11,
    },
    {
        id: 28,
        name: 'Drake Bulldogs',
        displayName: 'Drake',
        region: 'West',
        position: 12,
    },
    {
        id: 29,
        name: 'Iona Gaels',
        displayName: 'Iona',
        region: 'West',
        position: 13,
    },
    {
        id: 30,
        name: 'Colgate Raiders',
        displayName: 'Colgate',
        region: 'West',
        position: 14,
    },
    {
        id: 31,
        name: 'Samford Bulldogs',
        displayName: 'Samford',
        region: 'West',
        position: 15,
    },
    {
        id: 32,
        name: 'Texas A&M Corpus Christi Islanders',
        displayName: 'TAMU-CC',
        region: 'West',
        position: 16,
    },
    {
        id: 33,
        name: 'Alabama Crimson Tide',
        displayName: 'Alabama',
        region: 'South',
        position: 1,
    },
    {
        id: 34,
        name: 'Arizona Wildcats',
        displayName: 'Arizona',
        region: 'South',
        position: 2,
    },
    {
        id: 35,
        name: 'Baylor Bears',
        displayName: 'Baylor',
        region: 'South',
        position: 3,
    },
    {
        id: 36,
        name: 'Miami (fl) Hurricanes',
        displayName: 'Miami',
        region: 'South',
        position: 4,
    },
    {
        id: 37,
        name: 'Xavier Muskateers',
        displayName: 'Xavier',
        region: 'South',
        position: 5,
    },
    {
        id: 38,
        name: 'Texas A&M Aggies',
        displayName: 'Texas A&M',
        region: 'South',
        position: 6,
    },
    {
        id: 39,
        name: 'Providence Friars',
        displayName: 'Providence',
        region: 'South',
        position: 7,
    },
    {
        id: 40,
        name: 'Iowa Hawkeyes',
        displayName: 'Iowa',
        region: 'South',
        position: 8,
    },
    {
        id: 41,
        name: 'Nevada Wolf Pack',
        displayName: 'Nevada',
        region: 'South',
        position: 9,
    },
    {
        id: 42,
        name: 'Memphis Tigers',
        displayName: 'Memphis',
        region: 'South',
        position: 10,
    },
    {
        id: 43,
        name: 'Florida Atlantic Owls',
        displayName: 'FL Atlantic',
        region: 'South',
        position: 11,
    },
    {
        id: 44,
        name: 'Marshall Thundering Herd',
        displayName: 'Marshall',
        region: 'South',
        position: 12,
    },
    {
        id: 45,
        name: 'Hofstra Pride',
        displayName: 'Hofstra',
        region: 'South',
        position: 13,
    },
    {
        id: 46,
        name: 'Uc Irvine Anteaters',
        displayName: 'Uc Irvine',
        region: 'South',
        position: 14,
    },
    {
        id: 47,
        name: 'Youngstown State Penguins',
        displayName: 'Youngstown St',
        region: 'South',
        position: 15,
    },
    {
        id: 48,
        name: '',
        displayName: 'Wild Card',
        region: 'South',
        position: 16,
    },
    {
        id: 49,
        name: 'Houston Cougars',
        displayName: 'Houston',
        region: 'Midwest',
        position: 1,
    },
    {
        id: 50,
        name: 'Texas Longhorns',
        displayName: 'Texas',
        region: 'Midwest',
        position: 2,
    },
    {
        id: 51,
        name: 'Marquette Golden Eagles',
        displayName: 'Marquette',
        region: 'Midwest',
        position: 3,
    },
    {
        id: 52,
        name: 'Iowa State Cyclones',
        displayName: 'Iowa St.',
        region: 'Midwest',
        position: 4,
    },
    {
        id: 53,
        name: 'Indiana Hoosiers',
        displayName: 'Indiana',
        region: 'Midwest',
        position: 5,
    },
    {
        id: 54,
        name: 'Northwestern Wildcats',
        displayName: 'Northwestern',
        region: 'Midwest',
        position: 6,
    },
    {
        id: 55,
        name: 'Duke Blue Devils',
        displayName: 'Duke',
        region: 'Midwest',
        position: 7,
    },
    {
        id: 56,
        name: 'Nc State Wolfpack',
        displayName: 'Nc State',
        region: 'Midwest',
        position: 8,
    },
    {
        id: 57,
        name: 'Rutgers Scarlet Knights',
        displayName: 'Rutgers',
        region: 'Midwest',
        position: 9,
    },
    {
        id: 58,
        name: 'Missouri Tigers',
        displayName: 'Missouri',
        region: 'Midwest',
        position: 10,
    },
    {
        id: 59,
        name: '',
        displayName: 'Wild Card',
        region: 'Midwest',
        position: 11,
    },
    {
        id: 60,
        name: 'Oral Roberts Golden Eagles',
        displayName: 'Oral Roberts',
        region: 'Midwest',
        position: 12,
    },
    {
        id: 61,
        name: 'Marquette Golden Eagles',
        displayName: 'Marquette',
        region: 'Midwest',
        position: 13,
    },
    {
        id: 62,
        name: 'Toledo Rockets',
        displayName: 'Toledo',
        region: 'Midwest',
        position: 14,
    },
    {
        id: 63,
        name: 'Kennesaw State Owls',
        displayName: 'Kennesaw St.',
        region: 'Midwest',
        position: 15,
    },
    {
        id: 64,
        name: 'Unc Asheville Bulldogs',
        displayName: 'Unc Asheville',
        region: 'Midwest',
        position: 16,
    },
];

// TODO: Populate after draw only only name (not in use) and displayName by region and position.
export const wildCardTeams: MarchMadTeam[] = [
    {
        id: 1,
        name: 'Morehead State Eagles',
        displayName: 'Morehead St.',
        region: 'East',
        position: 1,
    },
    {
        id: 2,
        name: 'Alcorn State Braves',
        displayName: 'Alcorn St.',
        region: 'East',
        position: 2,
    },
    {
        id: 3,
        name: 'Wisconsin Badgers',
        displayName: 'Wisconsin',
        region: 'West',
        position: 3,
    },
    {
        id: 4,
        name: 'Mississippi State Bulldogs',
        displayName: 'Mississippi St.',
        region: 'West',
        position: 4,
    },
    {
        id: 5,
        name: 'Howard Bison',
        displayName: 'Howard',
        region: 'South',
        position: 5,
    },
    {
        id: 6,
        name: 'Fairleigh Dickinson Knights',
        displayName: 'Fairleigh Dickinson',
        region: 'South',
        position: 6,
    },
    {
        id: 7,
        name: 'Oklahoma State Cowboys',
        displayName: 'Oklahoma St.',
        region: 'Midwest',
        position: 7,
    },
    {
        id: 8,
        name: 'Usc Trojans',
        displayName: 'Usc',
        region: 'Midwest',
        position: 8,
    },
];
