import { MarketType } from 'enums/marketTypes';
import { League, MatchResolveType, PeriodType, ScoringType, Sport } from 'enums/sports';
import { LeagueInfo } from 'types/sports';

export const LeagueMap: Record<League, LeagueInfo> = {
    [League.NCAAF]: {
        sport: Sport.FOOTBALL,
        id: League.NCAAF,
        label: 'NCAA Football',
        logo: `/logos/leagueLogos/ncaa.webp`,
        logoClass: 'icon-homepage league--ncaa',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 202,
        hidden: false,
    },
    [League.NFL]: {
        sport: Sport.FOOTBALL,
        id: League.NFL,
        label: 'NFL',
        logo: `/logos/leagueLogos/nfl.webp`,
        logoClass: 'icon-homepage league--nfl',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 201,
        hidden: false,
    },
    [League.MLB]: {
        sport: Sport.BASEBALL,
        id: League.MLB,
        label: 'MLB',
        logo: `/logos/leagueLogos/mlb.webp`,
        logoClass: 'icon-homepage league--mlb',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.INNING,
        isDrawAvailable: true,
        priority: 401,
        hidden: false,
    },
    [League.NBA]: {
        sport: Sport.BASKETBALL,
        id: League.NBA,
        label: 'NBA',
        logo: `/logos/leagueLogos/nba.webp`,
        logoClass: 'icon-homepage league--nba',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 301,
        hidden: false,
    },
    [League.NCAAB]: {
        sport: Sport.BASKETBALL,
        id: League.NCAAB,
        label: 'NCAA Basketball',
        logoClass: 'icon-homepage league--ncaa',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.HALF,
        isDrawAvailable: false,
        priority: 302,
        hidden: false,
    },
    [League.NHL]: {
        sport: Sport.HOCKEY,
        id: League.NHL,
        label: 'NHL',
        logo: `/logos/leagueLogos/nhl.webp`,
        logoClass: 'icon-homepage league--nhl',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
        priority: 501,
        hidden: false,
    },
    [League.UFC]: {
        sport: Sport.FIGHTING,
        id: League.UFC,
        label: 'UFC',
        logo: '/logos/leagueLogos/ufc.webp',
        logoClass: 'icon-homepage league--ufc',
        scoringType: ScoringType.ROUNDS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.ROUND,
        isDrawAvailable: false,
        priority: 601,
        hidden: false,
    },
    [League.WNBA]: {
        sport: Sport.BASKETBALL,
        id: League.WNBA,
        label: 'WNBA',
        logoClass: 'icon-homepage league--wnba',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 305,
        hidden: false,
    },
    [League.MLS]: {
        sport: Sport.SOCCER,
        id: League.MLS,
        label: 'MLS',
        logo: `/logos/leagueLogos/mls.webp`,
        logoClass: 'icon-homepage league--mls',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 140,
        hidden: false,
    },
    [League.EPL]: {
        sport: Sport.SOCCER,
        id: League.EPL,
        label: 'EPL',
        logo: `/logos/leagueLogos/EPL.webp`,
        logoClass: 'icon-homepage league--epl',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 120,
        hidden: false,
    },
    [League.LIGUE_ONE]: {
        sport: Sport.SOCCER,
        id: League.LIGUE_ONE,
        label: 'Ligue 1',
        logo: `/logos/leagueLogos/Ligue1.webp`,
        logoClass: 'icon-homepage league--ligue1',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 124,
        hidden: false,
    },
    [League.BUNDESLIGA]: {
        sport: Sport.SOCCER,
        id: League.BUNDESLIGA,
        label: 'Bundesliga',
        logo: '/logos/leagueLogos/bundesliga.webp',
        logoClass: 'icon-homepage league--bundesliga',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 123,
        hidden: false,
    },
    [League.LA_LIGA]: {
        sport: Sport.SOCCER,
        id: League.LA_LIGA,
        label: 'La Liga',
        logo: `/logos/leagueLogos/LaLiga.webp`,
        logoClass: 'icon-homepage league--la-liga',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 121,
        hidden: false,
    },
    [League.SERIE_A]: {
        sport: Sport.SOCCER,
        id: League.SERIE_A,
        label: 'Serie A',
        logo: `/logos/leagueLogos/seriea.webp`,
        logoClass: 'icon-homepage league--serie-a',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 122,
        hidden: false,
    },
    [League.UEFA_CL]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CL,
        label: 'UEFA Champions League',
        logo: `/logos/leagueLogos/ucl-white.webp`,
        logoClass: 'icon-homepage league--ucl',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 103,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.UEFA_EL]: {
        sport: Sport.SOCCER,
        id: League.UEFA_EL,
        label: 'UEFA Europa League',
        logoClass: 'icon-homepage league--uel',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 104,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.FIFA_WC]: {
        sport: Sport.SOCCER,
        id: League.FIFA_WC,
        label: 'FIFA World Cup Qualifiers',
        logoClass: 'icon-homepage league--fifa-world-cup',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 100,
        hidden: false,
        tooltipKey: 'common.fifa-tooltip',
    },
    [League.J1_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.J1_LEAGUE,
        label: 'J1 League',
        logoClass: 'icon-homepage league--j1',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 144,
        hidden: false,
    },
    [League.IPL]: {
        sport: Sport.CRICKET,
        id: League.IPL,
        label: 'Indian Premier League',
        logoClass: 'icon-homepage league--ipl',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.INNING,
        isDrawAvailable: false,
        priority: 901,
        hidden: false,
    },
    [League.T20_BLAST]: {
        sport: Sport.CRICKET,
        id: League.T20_BLAST,
        label: 'T20 Blast',
        logoClass: 'icon-homepage league--t20',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.INNING,
        isDrawAvailable: false,
        priority: 902,
        hidden: false,
    },
    [League.IIHF_WORLD_CHAMPIONSHIP]: {
        sport: Sport.HOCKEY,
        id: League.IIHF_WORLD_CHAMPIONSHIP,
        label: 'IIHF World Championship',
        logoClass: 'icon-homepage league--iihf',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
        priority: 502,
        hidden: false,
        tooltipKey: 'common.iihf-tooltip',
    },
    [League.COPA_AMERICA]: {
        sport: Sport.SOCCER,
        id: League.COPA_AMERICA,
        label: 'Copa America 2024',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 102,
        hidden: true,
    },
    [League.COPA_LIBERTADORES]: {
        sport: Sport.SOCCER,
        id: League.COPA_LIBERTADORES,
        label: 'Copa Libertadores',
        logoClass: 'icon-homepage league--copa-libertadores',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 107,
        hidden: false,
    },
    [League.UEFA_EURO]: {
        sport: Sport.SOCCER,
        id: League.UEFA_EURO,
        label: 'UEFA EURO 2024',
        logoClass: 'icon-homepage league--uefa',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 101,
        hidden: true,
        tooltipKey: 'common.football-tooltip',
    },
    [League.EREDIVISIE]: {
        sport: Sport.SOCCER,
        id: League.EREDIVISIE,
        label: 'Eredivisie',
        logoClass: 'icon-homepage league--eredivisie',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 141,
        hidden: false,
    },
    [League.PRIMEIRA_LIGA]: {
        sport: Sport.SOCCER,
        id: League.PRIMEIRA_LIGA,
        label: 'Primeira Liga',
        logoClass: 'icon-homepage league--portugal',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 142,
        hidden: false,
    },
    [League.SUMMER_OLYMPICS_SOCCER_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.SUMMER_OLYMPICS_SOCCER_WOMEN,
        label: 'Olympic Games Soccer Women',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 102,
        hidden: true,
        tooltipKey: 'common.football-tooltip',
    },
    [League.SUMMER_OLYMPICS_SOCCER]: {
        sport: Sport.SOCCER,
        id: League.SUMMER_OLYMPICS_SOCCER,
        logoClass: 'icon-homepage league--paris2024',
        label: 'Olympic Games Soccer',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 102,
        hidden: true,
        tooltipKey: 'common.football-tooltip',
    },
    [League.FIFA_WC_WOMEN]: {
        sport: Sport.SOCCER,
        id: League.FIFA_WC_WOMEN,
        label: 'FIFA World Cup Women',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 112,
        hidden: true,
        tooltipKey: 'common.football-tooltip',
    },
    [League.ENGLAND_FA_CUP]: {
        sport: Sport.SOCCER,
        id: League.ENGLAND_FA_CUP,
        label: 'FA Cup',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 130,
        hidden: false,
    },
    [League.FRANCE_CUP]: {
        sport: Sport.SOCCER,
        id: League.FRANCE_CUP,
        label: 'Coupe de France',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 134,
        hidden: false,
    },
    [League.SPAIN_CUP]: {
        sport: Sport.SOCCER,
        id: League.SPAIN_CUP,
        label: 'Copa del Rey',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 131,
        hidden: false,
    },
    [League.ITALY_CUP]: {
        sport: Sport.SOCCER,
        id: League.ITALY_CUP,
        label: 'Coppa Italia',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 132,
        hidden: false,
    },
    [League.TENNIS_WTA]: {
        sport: Sport.TENNIS,
        id: League.TENNIS_WTA,
        label: 'WTA Events',
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
        priority: 703,
        hidden: false,
        tooltipKey: 'common.tennis-tooltip',
    },
    [League.TENNIS_GS]: {
        sport: Sport.TENNIS,
        id: League.TENNIS_GS,
        label: 'Grand Slam',
        logo: `/logos/Tennis/atp.webp`,
        logoClass: 'icon-homepage league--atp',
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
        priority: 701,
        hidden: false,
        tooltipKey: 'common.tennis-tooltip',
    },
    [League.TENNIS_MASTERS]: {
        sport: Sport.TENNIS,
        id: League.TENNIS_MASTERS,
        label: 'ATP Events',
        logo: `/logos/Tennis/atp.webp`,
        logoClass: 'icon-homepage league--atp',
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
        priority: 702,
        hidden: false,
        tooltipKey: 'common.tennis-tooltip',
    },
    [League.SUMMER_OLYMPICS_TENNIS]: {
        sport: Sport.TENNIS,
        id: League.SUMMER_OLYMPICS_TENNIS,
        label: 'Olympic Games Tennis',
        logo: `/logos/Tennis/atp.webp`,
        logoClass: 'icon-homepage league--atp',
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
        priority: 700,
        hidden: true,
        tooltipKey: 'common.tennis-tooltip',
    },
    [League.GERMANY_CUP]: {
        sport: Sport.SOCCER,
        id: League.GERMANY_CUP,
        label: 'DFB Pokal',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 133,
        hidden: false,
    },
    [League.LIGA_MX]: {
        sport: Sport.SOCCER,
        id: League.LIGA_MX,
        label: 'Liga MX',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 150,
        hidden: false,
    },
    [League.BRAZIL_1]: {
        sport: Sport.SOCCER,
        id: League.BRAZIL_1,
        label: 'Brazil Serie A',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 143,
        hidden: false,
    },
    [League.UEFA_EURO_U21]: {
        sport: Sport.SOCCER,
        id: League.UEFA_EURO_U21,
        label: 'UEFA EURO U21',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 111,
        hidden: true,
        tooltipKey: 'common.football-tooltip',
    },
    [League.FIFA_WORLD_CUP_U20]: {
        sport: Sport.SOCCER,
        id: League.FIFA_WORLD_CUP_U20,
        label: 'FIFA World Cup U20',
        logoClass: 'icon-homepage league--fifa-world-cup-u20',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 110,
        hidden: true,
        tooltipKey: 'common.fifa-tooltip',
    },
    [League.SUMMER_OLYMPICS_HANDBALL_WOMEN]: {
        sport: Sport.HANDBALL,
        id: League.SUMMER_OLYMPICS_HANDBALL_WOMEN,
        label: 'Olympic Games Handball Women',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 1402,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_HANDBALL]: {
        sport: Sport.HANDBALL,
        id: League.SUMMER_OLYMPICS_HANDBALL,
        label: 'Olympic Games Handball',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 1401,
        hidden: true,
    },
    [League.EUROLEAGUE]: {
        sport: Sport.BASKETBALL,
        id: League.EUROLEAGUE,
        label: 'Euroleague',
        logoClass: 'icon-homepage league--euroleague',
        logo: `/logos/leagueLogos/euroleague.webp`,
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 303,
        hidden: false,
    },
    [League.SUMMER_OLYMPICS_BASKETBALL]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_BASKETBALL,
        label: 'Olympic Games Basketball',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 306,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_BASKETBALL_WOMEN]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_BASKETBALL_WOMEN,
        label: 'Olympic Games Basketball Women',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 306,
        hidden: true,
    },
    [League.FIBA_WORLD_CUP]: {
        sport: Sport.BASKETBALL,
        id: League.FIBA_WORLD_CUP,
        label: 'FIBA World Cup',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 300,
        hidden: true,
    },
    [League.FORMULA1]: {
        sport: Sport.MOTOSPORT,
        id: League.FORMULA1,
        label: 'Formula 1',
        logo: '/logos/leagueLogos/f1.webp',
        logoClass: 'icon-homepage league--f1',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1001,
        hidden: false,
    },
    [League.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN]: {
        sport: Sport.VOLLEYBALL,
        id: League.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN,
        label: 'Olympic Games Beach Voleyball Women',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
        priority: 1304,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_BEACH_VOLEYBALL]: {
        sport: Sport.VOLLEYBALL,
        id: League.SUMMER_OLYMPICS_BEACH_VOLEYBALL,
        label: 'Olympic Games Beach Voleyball',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
        priority: 1303,
        hidden: true,
    },
    [League.MOTOGP]: {
        sport: Sport.MOTOSPORT,
        id: League.MOTOGP,
        label: 'MotoGP',
        logo: `/logos/leagueLogos/motogp.webp`,
        logoClass: 'icon-homepage league--motogp',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1002,
        hidden: true,
    },
    [League.SAUDI_PROFESSIONAL_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.SAUDI_PROFESSIONAL_LEAGUE,
        label: 'Saudi Professional League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 145,
        hidden: false,
    },
    [League.SUMMER_OLYMPICS_WATERPOLO]: {
        sport: Sport.WATERPOLO,
        id: League.SUMMER_OLYMPICS_WATERPOLO,
        label: 'Olympic Games Water Polo',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: true,
        priority: 1501,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_VOLEYBALL_WOMEN]: {
        sport: Sport.VOLLEYBALL,
        id: League.SUMMER_OLYMPICS_VOLEYBALL_WOMEN,
        label: 'Olympic Games Voleyball Women',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
        priority: 1302,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_VOLEYBALL]: {
        sport: Sport.VOLLEYBALL,
        id: League.SUMMER_OLYMPICS_VOLEYBALL,
        label: 'Olympic Games Voleyball',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
        priority: 1301,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_TABLE_TENNIS]: {
        sport: Sport.TABLE_TENNIS,
        id: League.SUMMER_OLYMPICS_TABLE_TENNIS,
        label: 'Olympic Games Table Tennis',
        scoringType: ScoringType.SETS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.SET,
        isDrawAvailable: false,
        priority: 1601,
        hidden: true,
    },
    [League.BOXING]: {
        sport: Sport.FIGHTING,
        id: League.BOXING,
        label: 'Boxing',
        logoClass: 'icon-homepage league--boxing',
        scoringType: ScoringType.ROUNDS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.ROUND,
        isDrawAvailable: false,
        priority: 602,
        hidden: false,
    },
    [League.SUMMER_OLYMPICS_RUGBY]: {
        sport: Sport.RUGBY,
        id: League.SUMMER_OLYMPICS_RUGBY,
        label: 'Olympic Games Rugby',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 1201,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_RUGBY_WOMEN]: {
        sport: Sport.RUGBY,
        id: League.SUMMER_OLYMPICS_RUGBY_WOMEN,
        label: 'Olympic Games Rugby Women',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 1202,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_HOCKEY_WOMEN]: {
        sport: Sport.HOCKEY,
        id: League.SUMMER_OLYMPICS_HOCKEY_WOMEN,
        label: 'Olympic Games Hockey Women',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
        priority: 504,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_HOCKEY]: {
        sport: Sport.HOCKEY,
        id: League.SUMMER_OLYMPICS_HOCKEY,
        label: 'Olympic Games Hockey',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.PERIOD,
        isDrawAvailable: true,
        priority: 503,
        hidden: true,
    },
    [League.UEFA_NATIONS_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.UEFA_NATIONS_LEAGUE,
        label: 'UEFA Nations League',
        logoClass: 'icon-homepage league--uefa-nations',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 106,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.CONCACAF_NATIONS_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.CONCACAF_NATIONS_LEAGUE,
        label: 'CONCACAF Nations League',
        logoClass: 'icon-homepage league--concacaf-nations',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 108,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.CSGO]: {
        sport: Sport.ESPORTS,
        id: League.CSGO,
        label: 'CS2',
        logoClass: 'icon-homepage league--csgo',
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
        priority: 801,
        hidden: false,
    },
    [League.DOTA2]: {
        sport: Sport.ESPORTS,
        id: League.DOTA2,
        label: 'DOTA 2',
        logoClass: 'icon-homepage league--dota2',
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
        priority: 802,
        hidden: false,
    },
    [League.SUMMER_OLYMPICS_BASKETBALL_3X3]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_BASKETBALL_3X3,
        label: 'Olympic Games Basketball 3x3',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 307,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN,
        label: 'Olympic Games Basketball 3x3 Women',
        logoClass: 'icon-homepage league--paris2024',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 307,
        hidden: true,
    },
    [League.SUMMER_OLYMPICS_QUALIFICATION]: {
        sport: Sport.BASKETBALL,
        id: League.SUMMER_OLYMPICS_QUALIFICATION,
        label: 'Summer Olympics Qualification',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 306,
        hidden: true,
    },
    [League.LOL]: {
        sport: Sport.ESPORTS,
        id: League.LOL,
        label: 'LOL',
        logoClass: 'icon-homepage league--lol',
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
        priority: 803,
        hidden: false,
    },
    [League.CONMEBOL_WC_QUALIFICATIONS]: {
        sport: Sport.SOCCER,
        id: League.CONMEBOL_WC_QUALIFICATIONS,
        label: 'CONMEBOL WC Qualification',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 109,
        hidden: false,
    },
    [League.UEFA_CONFERENCE_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CONFERENCE_LEAGUE,
        label: 'UEFA Conference League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 105,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.NON_TITLE_BOXING]: {
        sport: Sport.FIGHTING,
        id: League.NON_TITLE_BOXING,
        label: 'Boxing',
        logoClass: 'icon-homepage league--boxing',
        scoringType: ScoringType.ROUNDS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.ROUND,
        isDrawAvailable: false,
        priority: 603,
        hidden: false,
    },
    [League.UEFA_CHAMPIONS_LEAGUE_QUALIFICATION]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CHAMPIONS_LEAGUE_QUALIFICATION,
        label: 'UEFA Champions League Qualification',
        logo: `/logos/leagueLogos/ucl-white.webp`,
        logoClass: 'icon-homepage league--ucl',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 103,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.UEFA_EUROPA_LEAGUE_QUALIFICATION]: {
        sport: Sport.SOCCER,
        id: League.UEFA_EUROPA_LEAGUE_QUALIFICATION,
        label: 'UEFA Europa League Qualification',
        logoClass: 'icon-homepage league--uel',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 104,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.UEFA_CONFERENCE_LEAGUE_QUALIFICATION]: {
        sport: Sport.SOCCER,
        id: League.UEFA_CONFERENCE_LEAGUE_QUALIFICATION,
        label: 'UEFA Conference League Qualification',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 105,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.US_ELECTION]: {
        sport: Sport.POLITICS,
        id: League.US_ELECTION,
        label: 'US Election 2024',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1701,
        hidden: false,
        tooltipKey: 'common.election-tooltip',
    },
    [League.UEFA_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.UEFA_SUPER_CUP,
        label: 'UEFA Super Cup',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 102,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.BRAZIL_CUP]: {
        sport: Sport.SOCCER,
        id: League.BRAZIL_CUP,
        label: 'Copa do Brasil',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 135,
        hidden: false,
        tooltipKey: 'common.football-tooltip',
    },
    [League.ENGLAND_CHAMPIONSHIP]: {
        sport: Sport.SOCCER,
        id: League.ENGLAND_CHAMPIONSHIP,
        label: 'EFL Championship',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 125,
        hidden: false,
    },
    [League.SCOTLAND_PREMIERSHIP]: {
        sport: Sport.SOCCER,
        id: League.SCOTLAND_PREMIERSHIP,
        label: 'Scotland Premiership',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 151,
        hidden: false,
    },
    [League.BELGIUM_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.BELGIUM_LEAGUE,
        label: 'Belgium Pro League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 152,
        hidden: false,
    },
    [League.CZECH_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.CZECH_LEAGUE,
        label: 'Czech Republic FNL',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 153,
        hidden: true,
    },
    [League.CHILE_PRIMERA]: {
        sport: Sport.SOCCER,
        id: League.CHILE_PRIMERA,
        label: 'Chile Primera Division',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 154,
        hidden: true,
    },
    [League.FINLAND_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.FINLAND_LEAGUE,
        label: 'Finland Veikkausliiga',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 155,
        hidden: true,
    },
    [League.ARGENTINA_PRIMERA]: {
        sport: Sport.SOCCER,
        id: League.ARGENTINA_PRIMERA,
        label: 'Argentina Primera Division',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 156,
        hidden: false,
    },
    [League.RUSSIA_PREMIER]: {
        sport: Sport.SOCCER,
        id: League.RUSSIA_PREMIER,
        label: 'Russia Premier League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 157,
        hidden: true,
    },
    [League.TURKEY_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.TURKEY_SUPER_LEAGUE,
        label: 'Turkey Super Lig',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 158,
        hidden: false,
    },
    [League.SERBIA_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.SERBIA_SUPER_LEAGUE,
        label: 'Serbia Super Liga',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 159,
        hidden: true,
    },
    [League.GREECE_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.GREECE_SUPER_LEAGUE,
        label: 'Greece Super League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 160,
        hidden: true,
    },
    [League.INDIA_PREMIER]: {
        sport: Sport.SOCCER,
        id: League.INDIA_PREMIER,
        label: 'India Calcutta Premier Division',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 161,
        hidden: true,
    },
    [League.CHINA_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.CHINA_SUPER_LEAGUE,
        label: 'China Super League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 162,
        hidden: false,
    },
    [League.AUSTRALIA_A_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.AUSTRALIA_A_LEAGUE,
        label: 'Australia A-League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 163,
        hidden: false,
    },
    [League.SWITZERLAND_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.SWITZERLAND_SUPER_LEAGUE,
        label: 'Switzerland Super League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 164,
        hidden: false,
    },
    [League.BUNDESLIGA_2]: {
        sport: Sport.SOCCER,
        id: League.BUNDESLIGA_2,
        label: 'Bundesliga 2',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 165,
        hidden: false,
    },
    [League.LA_LIGA_2]: {
        sport: Sport.SOCCER,
        id: League.LA_LIGA_2,
        label: 'La Liga 2',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 166,
        hidden: false,
    },
    [League.SERIE_B]: {
        sport: Sport.SOCCER,
        id: League.SERIE_B,
        label: 'Serie B',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 167,
        hidden: false,
    },
    [League.INDIA_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.INDIA_SUPER_LEAGUE,
        label: 'India Super League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 168,
        hidden: true,
    },
    [League.LIGUE_2]: {
        sport: Sport.SOCCER,
        id: League.LIGUE_2,
        label: 'Ligue 2',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 169,
        hidden: false,
    },
    [League.AUSTRIA_BUNDESLIGA]: {
        sport: Sport.SOCCER,
        id: League.AUSTRIA_BUNDESLIGA,
        label: 'Austria Bundesliga',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 170,
        hidden: false,
    },
    [League.DENMARK_SUPER_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.DENMARK_SUPER_LEAGUE,
        label: 'Denmark Superliga',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 171,
        hidden: true,
    },
    [League.POLAND_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.POLAND_LEAGUE,
        label: 'Poland Ekstraklasa',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 172,
        hidden: true,
    },
    [League.SWEDEN_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.SWEDEN_LEAGUE,
        label: 'Sweden Allsvenskan',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 173,
        hidden: true,
    },
    [League.COLOMBIA_PRIMERA_A]: {
        sport: Sport.SOCCER,
        id: League.COLOMBIA_PRIMERA_A,
        label: 'Colombia Primera A',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 174,
        hidden: true,
    },
    [League.ENGLAND_EFL_CUP]: {
        sport: Sport.SOCCER,
        id: League.ENGLAND_EFL_CUP,
        label: 'England EFL Cup',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 175,
        hidden: false,
    },
    [League.ENGLAND_LEGAUE_1]: {
        sport: Sport.SOCCER,
        id: League.ENGLAND_LEGAUE_1,
        label: 'England League 1',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 176,
        hidden: false,
    },
    [League.URUGUAY_PRIMERA_DIVISION]: {
        sport: Sport.SOCCER,
        id: League.URUGUAY_PRIMERA_DIVISION,
        label: 'Uruguay Primera Division',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 177,
        hidden: true,
    },
    [League.AFC_CHAMPIONS_LEAGUE]: {
        sport: Sport.SOCCER,
        id: League.AFC_CHAMPIONS_LEAGUE,
        label: 'AFC Champions League',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 178,
        hidden: false,
    },
    [League.ITALY_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.ITALY_SUPER_CUP,
        label: 'Italy Super Cup',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 179,
        hidden: false,
    },
    [League.FRANCE_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.FRANCE_SUPER_CUP,
        label: 'France Super Cup',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 180,
        hidden: false,
    },
    [League.SPAIN_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.SPAIN_SUPER_CUP,
        label: 'Spain Super Cup',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 181,
        hidden: false,
    },
    [League.GERMANY_SUPER_CUP]: {
        sport: Sport.SOCCER,
        id: League.GERMANY_SUPER_CUP,
        label: 'Germany Super Cup',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 182,
        hidden: false,
    },
    [League.PORTUGAL_LEAGUE_CUP]: {
        sport: Sport.SOCCER,
        id: League.PORTUGAL_LEAGUE_CUP,
        label: 'Portugal League Cup',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 183,
        hidden: false,
    },
    [League.THAILAND_LEAGUE_1]: {
        sport: Sport.SOCCER,
        id: League.THAILAND_LEAGUE_1,
        label: 'Thai League 1',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 184,
        hidden: false,
    },
    [League.NETHERLANDS_CUP]: {
        sport: Sport.SOCCER,
        id: League.NETHERLANDS_CUP,
        label: 'Netherlands KNVB Beker',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 185,
        hidden: false,
    },
    [League.PORTUGAL_CUP]: {
        sport: Sport.SOCCER,
        id: League.PORTUGAL_CUP,
        label: 'Taca de Portugal',
        scoringType: ScoringType.GOALS,
        matchResolveType: MatchResolveType.REGULAR,
        periodType: PeriodType.HALF,
        isDrawAvailable: true,
        priority: 186,
        hidden: false,
    },
    [League.EUROCUP]: {
        sport: Sport.BASKETBALL,
        id: League.EUROCUP,
        label: 'Eurocup',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 304,
        hidden: false,
    },
    [League.SPAIN_LIGA_ACB]: {
        sport: Sport.BASKETBALL,
        id: League.SPAIN_LIGA_ACB,
        label: 'Spain Liga ACB',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 308,
        hidden: false,
    },
    [League.ITALY_LEGA_BASKET_SERIE_A]: {
        sport: Sport.BASKETBALL,
        id: League.ITALY_LEGA_BASKET_SERIE_A,
        label: 'Italy Lega Basket Serie A',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 309,
        hidden: false,
    },
    [League.GERMANY_BBL]: {
        sport: Sport.BASKETBALL,
        id: League.GERMANY_BBL,
        label: 'Germany BBL',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 310,
        hidden: false,
    },
    [League.FRANCE_LNB_PRO_A]: {
        sport: Sport.BASKETBALL,
        id: League.FRANCE_LNB_PRO_A,
        label: 'France LNB Pro A',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 311,
        hidden: false,
    },
    [League.CHINA_CBA]: {
        sport: Sport.BASKETBALL,
        id: League.CHINA_CBA,
        label: 'China CBA',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 312,
        hidden: false,
    },
    [League.AUSTRALIA_NBL]: {
        sport: Sport.BASKETBALL,
        id: League.AUSTRALIA_NBL,
        label: 'Australia NBL',
        scoringType: ScoringType.POINTS,
        matchResolveType: MatchResolveType.OVERTIME,
        periodType: PeriodType.QUARTER,
        isDrawAvailable: false,
        priority: 313,
        hidden: false,
    },
    [League.VALORANT]: {
        sport: Sport.ESPORTS,
        id: League.VALORANT,
        label: 'Valorant',
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
        priority: 804,
        hidden: false,
    },
    [League.ROCKET_LEAGUE]: {
        sport: Sport.ESPORTS,
        id: League.ROCKET_LEAGUE,
        label: 'Rocket League',
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
        priority: 805,
        hidden: false,
    },
    [League.CALL_OF_DUTY]: {
        sport: Sport.ESPORTS,
        id: League.CALL_OF_DUTY,
        label: 'Call of Duty',
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
        priority: 806,
        hidden: false,
    },
    [League.STARCRAFT]: {
        sport: Sport.ESPORTS,
        id: League.STARCRAFT,
        label: 'Starcraft',
        scoringType: ScoringType.MAPS,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.MAP,
        isDrawAvailable: false,
        priority: 807,
        hidden: false,
    },
    [League.NFL_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.NFL_FUTURES,
        label: 'NFL Futures',
        logo: `/logos/leagueLogos/nfl.webp`,
        logoClass: 'icon-homepage league--nfl',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1801,
        hidden: false,
    },
    [League.NHL_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.NHL_FUTURES,
        label: 'NHL Futures',
        logo: `/logos/leagueLogos/nhl.webp`,
        logoClass: 'icon-homepage league--nhl',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1803,
        hidden: false,
    },
    [League.NBA_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.NBA_FUTURES,
        label: 'NBA Futures',
        logo: `/logos/leagueLogos/nba.webp`,
        logoClass: 'icon-homepage league--nba',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1802,
        hidden: false,
    },
    [League.EPL_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.EPL_FUTURES,
        label: 'EPL Futures',
        logo: `/logos/leagueLogos/EPL.webp`,
        logoClass: 'icon-homepage league--epl',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1811,
        hidden: false,
    },
    [League.LIGUE_ONE_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.LIGUE_ONE_FUTURES,
        label: 'Ligue 1 Futures',
        logo: `/logos/leagueLogos/Ligue1.webp`,
        logoClass: 'icon-homepage league--ligue1',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1815,
        hidden: false,
    },
    [League.BUNDESLIGA_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.BUNDESLIGA_FUTURES,
        label: 'Bundesliga Futures',
        logo: '/logos/leagueLogos/bundesliga.webp',
        logoClass: 'icon-homepage league--bundesliga',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1814,
        hidden: false,
    },
    [League.LA_LIGA_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.LA_LIGA_FUTURES,
        label: 'La Liga Futures',
        logo: `/logos/leagueLogos/LaLiga.webp`,
        logoClass: 'icon-homepage league--la-liga',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1812,
        hidden: false,
    },
    [League.SERIE_A_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.SERIE_A_FUTURES,
        label: 'Serie A Futures',
        logo: `/logos/leagueLogos/seriea.webp`,
        logoClass: 'icon-homepage league--serie-a',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1813,
        hidden: false,
    },
    [League.UEFA_CHAMPIONS_LEAGUE_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.UEFA_CHAMPIONS_LEAGUE_FUTURES,
        label: 'UEFA Champions League Futures',
        logo: `/logos/leagueLogos/ucl-white.webp`,
        logoClass: 'icon-homepage league--ucl',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1810,
        hidden: false,
    },
    [League.EUROLEAGUE_FUTURES]: {
        sport: Sport.FUTURES,
        id: League.EUROLEAGUE_FUTURES,
        label: 'Euroleague Futures',
        logoClass: 'icon-homepage league--euroleague',
        logo: `/logos/leagueLogos/euroleague.webp`,
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1820,
        hidden: false,
    },
    [League.GOLF_H2H]: {
        sport: Sport.GOLF,
        id: League.GOLF_H2H,
        label: 'Golf head-to-head',
        logoClass: 'icon-homepage league--pga',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1101,
        hidden: false,
    },
    [League.GOLF_WINNER]: {
        sport: Sport.GOLF,
        id: League.GOLF_WINNER,
        label: 'Golf Tournament Winner',
        logoClass: 'icon-homepage league--pga',
        scoringType: ScoringType.EMPTY,
        matchResolveType: MatchResolveType.EMPTY,
        periodType: PeriodType.EMPTY,
        isDrawAvailable: false,
        priority: 1102,
        hidden: false,
    },
};

export const BOXING_LEAGUES = [League.BOXING, League.NON_TITLE_BOXING];

export const UFC_LEAGUE_IDS = [701, 702, 703, 704];

export const INTERNATIONAL_LEAGUES = [
    League.FIFA_WC,
    League.IIHF_WORLD_CHAMPIONSHIP,
    League.UEFA_EURO,
    League.FIFA_WC_WOMEN,
    League.UEFA_EURO_U21,
    League.FIFA_WORLD_CUP_U20,
    League.FIBA_WORLD_CUP,
    League.UEFA_NATIONS_LEAGUE,
    League.CONCACAF_NATIONS_LEAGUE,
    League.CONMEBOL_WC_QUALIFICATIONS,
    League.COPA_AMERICA,
    League.SUMMER_OLYMPICS_QUALIFICATION,
    League.SUMMER_OLYMPICS_BASKETBALL,
    League.SUMMER_OLYMPICS_BASKETBALL_WOMEN,
    League.SUMMER_OLYMPICS_BASKETBALL_3X3,
    League.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN,
    League.SUMMER_OLYMPICS_SOCCER,
    League.SUMMER_OLYMPICS_SOCCER_WOMEN,
    League.SUMMER_OLYMPICS_RUGBY,
    League.SUMMER_OLYMPICS_RUGBY_WOMEN,
    League.SUMMER_OLYMPICS_VOLEYBALL,
    League.SUMMER_OLYMPICS_VOLEYBALL_WOMEN,
    League.SUMMER_OLYMPICS_HANDBALL,
    League.SUMMER_OLYMPICS_HANDBALL_WOMEN,
    League.SUMMER_OLYMPICS_WATERPOLO,
    League.SUMMER_OLYMPICS_BEACH_VOLEYBALL,
    League.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN,
    League.SUMMER_OLYMPICS_HOCKEY,
    League.SUMMER_OLYMPICS_HOCKEY_WOMEN,
];

export const OLYMPIC_LEAGUES = [
    League.SUMMER_OLYMPICS_BASKETBALL,
    League.SUMMER_OLYMPICS_BASKETBALL_WOMEN,
    League.SUMMER_OLYMPICS_BASKETBALL_3X3,
    League.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN,
    League.SUMMER_OLYMPICS_SOCCER,
    League.SUMMER_OLYMPICS_SOCCER_WOMEN,
    League.SUMMER_OLYMPICS_RUGBY,
    League.SUMMER_OLYMPICS_RUGBY_WOMEN,
    League.SUMMER_OLYMPICS_VOLEYBALL,
    League.SUMMER_OLYMPICS_VOLEYBALL_WOMEN,
    League.SUMMER_OLYMPICS_HANDBALL,
    League.SUMMER_OLYMPICS_HANDBALL_WOMEN,
    League.SUMMER_OLYMPICS_WATERPOLO,
    League.SUMMER_OLYMPICS_BEACH_VOLEYBALL,
    League.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN,
    League.SUMMER_OLYMPICS_HOCKEY,
    League.SUMMER_OLYMPICS_HOCKEY_WOMEN,
    League.SUMMER_OLYMPICS_TENNIS,
    League.SUMMER_OLYMPICS_TABLE_TENNIS,
];

export const PLAYER_PROPS_COMBINING_ENABLED_LEAGUES = [League.NBA, League.WNBA, League.EUROLEAGUE];

export const PLAYER_PROPS_MARKETS_PER_SPORT_MAP: Record<Sport, MarketType[]> = {
    [Sport.SOCCER]: [
        MarketType.PLAYER_PROPS_OVER_GOALS,
        MarketType.PLAYER_PROPS_TOTAL_SHOTS,
        MarketType.PLAYER_PROPS_ASSISTS,
    ],
    [Sport.FOOTBALL]: [],
    [Sport.BASKETBALL]: [
        MarketType.PLAYER_PROPS_POINTS,
        MarketType.PLAYER_PROPS_REBOUNDS,
        MarketType.PLAYER_PROPS_ASSISTS,
    ],
    [Sport.BASEBALL]: [],
    [Sport.HOCKEY]: [MarketType.PLAYER_PROPS_POINTS, MarketType.PLAYER_PROPS_SHOTS, MarketType.PLAYER_PROPS_ASSISTS],
    [Sport.FIGHTING]: [],
    [Sport.TENNIS]: [],
    [Sport.TABLE_TENNIS]: [],
    [Sport.ESPORTS]: [],
    [Sport.RUGBY]: [],
    [Sport.VOLLEYBALL]: [],
    [Sport.HANDBALL]: [],
    [Sport.WATERPOLO]: [],
    [Sport.CRICKET]: [],
    [Sport.MOTOSPORT]: [],
    [Sport.GOLF]: [],
    [Sport.POLITICS]: [],
    [Sport.FUTURES]: [],
    [Sport.EMPTY]: [],
};

// IMPORTANT: first element of MarketType[] must be unique for that entry
export const PLAYER_PROPS_MARKETS_PER_PROP_MAP: Record<number, MarketType[]> = {
    [MarketType.PLAYER_PROPS_PASSING_YARDS]: [
        MarketType.PLAYER_PROPS_PASSING_YARDS,
        MarketType.PLAYER_PROPS_PASSING_TOUCHDOWNS,
        MarketType.PLAYER_PROPS_TOUCHDOWN_SCORER,
    ],
    [MarketType.PLAYER_PROPS_RECEIVING_YARDS]: [
        MarketType.PLAYER_PROPS_RUSHING_YARDS,
        MarketType.PLAYER_PROPS_RECEIVING_YARDS,
        MarketType.PLAYER_PROPS_TOUCHDOWN_SCORER,
    ],
};

export const PLAYER_PROPS_SPECIAL_SPORTS = [Sport.FOOTBALL];

// lower index => higher priority
export const LEAGUES_SORT_PRIORITY = [
    League.EPL,
    League.LA_LIGA,
    League.SERIE_A,
    League.BUNDESLIGA,
    League.LIGUE_ONE,
    League.NBA,
    League.NFL,
    League.NHL,
    League.MLB,
    League.EREDIVISIE,
    League.PRIMEIRA_LIGA,
    League.BELGIUM_LEAGUE,
    League.NCAAF,
    League.NCAAB,
];
