export const LOCAL_STORAGE_KEYS = {
    SELECTED_WALLET: 'selectedWallet',
    UI_THEME: 'ui-theme',
    SORT_DIRECTION: 'sortDirection',
    SORT_BY: 'sortBy',
    FILTER_GLOBAL: 'filterGlobal',
    FILTER_MARKET_SEARCH: 'filterMarketSearch',
    FILTER_TAGS: 'tagsFilter',
    FILTER_DATE: 'filterDate',
    FILTER_DATE_PERIOD: 'filterDatePeriod',
    FILTER_SPORT: 'filterSport',
    FILTER_ACTIVE: 'filterActive',
    FILTER_BET_TYPE: 'filterBetType',
    LIST_VIEW: 'listView',
    ODDS_TYPE: 'typeOdds',
    STOP_PULSING: 'stopPulsing',
    FAVOURITE_LEAGUES: 'favouriteLeagues',
    PARLAY: 'parlay',
    COMBINED_POSITIONS: 'combinedPositions',
    MULTI_SINGLE: 'multiSingle',
    IS_MULTI_SINGLE: 'isMultiSingle',
    BRACKETS: 'brackets',
    COLLATERAL_INDEX: 'collateralIndex',
    KEEP_SELECTION: 'keepSelection',
    SELECTED_MARKET: 'selectedMarket',
    IS_THREE_WAY_VIEW: 'isThreeWayView',
};
