import { BetType, BetTypeGroup, SportFilterEnum } from 'enums/markets';
import { MarketSport, SportsMap, SportsTagsMap, Tags } from 'types/markets';

export const TAGS_LIST: Tags = [
    {
        id: 9001,
        label: 'NCAA Football',
        logo: `/logos/leagueLogos/ncaa.webp`,
        logoClass: 'icon-league league--ncaa',
        favourite: false,
        hidden: false,
        priority: 202,
        live: false,
    },
    {
        id: 9002,
        label: 'NFL',
        logo: `/logos/leagueLogos/nfl.webp`,
        logoClass: 'icon-league league--nfl',
        favourite: false,
        hidden: false,
        priority: 201,
        live: false,
    },
    {
        id: 9003,
        label: 'MLB',
        logo: `/logos/leagueLogos/mlb.webp`,
        logoClass: 'icon-league league--mlb',
        favourite: false,
        hidden: false,
        priority: 401,
        live: false,
    },
    {
        id: 9004,
        label: 'NBA',
        logo: `/logos/leagueLogos/nba.webp`,
        logoClass: 'icon-league league--nba',
        favourite: false,
        hidden: false,
        priority: 301,
        live: true,
    },
    {
        id: 9005,
        label: 'NCAA Basketball',
        logoClass: 'icon-league league--ncaa',
        favourite: false,
        hidden: false,
        priority: 302,
        live: false,
    },
    {
        id: 9006,
        label: 'NHL',
        logo: `/logos/leagueLogos/nhl.webp`,
        logoClass: 'icon-league league--nhl',
        favourite: false,
        hidden: false,
        priority: 501,
        live: true,
    },
    {
        id: 9007,
        label: 'UFC',
        logo: '/logos/leagueLogos/ufc.webp',
        logoClass: 'icon-league league--ufc',
        favourite: false,
        hidden: false,
        priority: 601,
        live: false,
    },
    {
        id: 9008,
        label: 'WNBA',
        logoClass: 'icon-league league--wnba',
        favourite: false,
        hidden: false,
        priority: 304,
        live: false,
    },
    {
        id: 9010,
        label: 'MLS',
        logo: `/logos/leagueLogos/mls.webp`,
        logoClass: 'icon-league league--mls',
        favourite: false,
        hidden: false,
        priority: 106,
        live: false,
    },
    {
        id: 9011,
        label: 'EPL',
        logo: `/logos/leagueLogos/EPL.webp`,
        logoClass: 'icon-league league--epl',
        favourite: false,
        hidden: false,
        priority: 101,
        live: true,
    },
    {
        id: 9012,
        label: 'Ligue 1',
        logo: `/logos/leagueLogos/Ligue1.webp`,
        logoClass: 'icon-league league--ligue1',
        favourite: false,
        hidden: false,
        priority: 105,
        live: true,
    },
    {
        id: 9013,
        label: 'Bundesliga',
        logo: '/logos/leagueLogos/bundesliga.webp',
        logoClass: 'icon-league league--bundesliga',
        favourite: false,
        hidden: false,
        priority: 104,
        live: false,
    },
    {
        id: 9014,
        label: 'La Liga',
        logo: `/logos/leagueLogos/LaLiga.webp`,
        logoClass: 'icon-league league--la-liga',
        favourite: false,
        hidden: false,
        priority: 102,
        live: false,
    },
    {
        id: 9015,
        label: 'Serie A',
        logo: `/logos/leagueLogos/seriea.webp`,
        logoClass: 'icon-league league--serie-a',
        favourite: false,
        hidden: false,
        priority: 103,
        live: false,
    },
    {
        id: 9016,
        label: 'UEFA Champions League',
        logo: `/logos/leagueLogos/ucl-white.webp`,
        logoClass: 'icon-league league--ucl',
        favourite: false,
        hidden: false,
        priority: 110,
        live: false,
    },
    {
        id: 9017,
        label: 'UEFA Europa League',
        logo: ``,
        logoClass: 'icon-league league--uel',
        favourite: false,
        hidden: false,
        priority: 111,
        live: false,
    },
    {
        id: 9018,
        label: 'FIFA World Cup',
        logo: ``,
        logoClass: 'icon-league league--fifa-world-cup',
        favourite: false,
        hidden: true,
        priority: 0,
        live: false,
    },
    {
        id: 9019,
        label: 'J1 League',
        logo: ``,
        logoClass: 'icon-league league--j1',
        favourite: false,
        hidden: false,
        priority: 109,
        live: false,
    },
    // {
    //     id: 9445,
    //     label: 'Formula 1',
    //     logo: '/logos/leagueLogos/f1.webp',
    //     logoClass: 'icon-league league--f1',
    //     favourite: false,
    //     hidden: false,
    //     priority: 701,
    // },
    // {
    //     id: 9497,
    //     label: 'MotoGP',
    //     logo: `/logos/leagueLogos/motogp.webp`,
    //     logoClass: 'icon-league league--motogp',
    //     favourite: false,
    //     hidden: false,
    //     priority: 702,
    // },
    {
        id: 9153,
        label: 'Grand Slam',
        logo: `/logos/Tennis/atp.png`,
        logoClass: 'icon-league league--atp',
        favourite: false,
        hidden: false,
        priority: 602,
        live: false,
    },
    {
        id: 9156,
        label: 'ATP Events',
        logo: `/logos/Tennis/atp.png`,
        logoClass: 'icon-league league--atp',
        favourite: false,
        hidden: false,
        priority: 603,
        live: false,
    },
    {
        id: 18977,
        label: 'CS GO',
        logoClass: 'icon-league league--csgo',
        favourite: false,
        hidden: false,
        priority: 801,
        live: false,
    },
    {
        id: 18983,
        label: 'DOTA 2',
        logoClass: 'icon-league league--dota2',
        favourite: false,
        hidden: false,
        priority: 802,
        live: false,
    },
    {
        id: 19138,
        label: 'LOL',
        logoClass: 'icon-league league--lol',
        favourite: false,
        hidden: false,
        priority: 803,
        live: false,
    },
    {
        id: 9020,
        label: 'Indian Premier League',
        logoClass: 'icon-league league--ipl',
        favourite: false,
        hidden: false,
        priority: 901,
        live: false,
    },
    {
        id: 9399,
        label: 'Euroleague',
        logoClass: 'icon-league league--euroleague',
        favourite: false,
        hidden: false,
        priority: 303,
        live: false,
    },
    {
        id: 18196,
        label: 'Boxing',
        logoClass: 'icon-league league--boxing',
        favourite: false,
        hidden: false,
        priority: 602,
        live: false,
    },
    {
        id: 19595,
        label: 'Boxing',
        logoClass: 'icon-league league--boxing',
        favourite: false,
        hidden: true,
        priority: 603,
        live: false,
    },
    {
        id: 9057,
        label: 'Eredivisie',
        logoClass: 'icon-league league--eredivisie',
        favourite: false,
        hidden: false,
        priority: 107,
        live: false,
    },
    {
        id: 9061,
        label: 'Primeira Liga',
        logoClass: 'icon-league league--portugal',
        favourite: false,
        hidden: false,
        priority: 108,
        live: false,
    },
    {
        id: 9045,
        label: 'Copa Libertadores',
        logoClass: 'icon-league league--copa-libertadores',
        favourite: false,
        hidden: false,
        priority: 112,
        live: false,
    },
    {
        id: 9033,
        label: 'IIHF World Championship',
        logoClass: 'icon-league league--iihf',
        favourite: false,
        hidden: false,
        priority: 502,
        live: false,
    },
    {
        id: 9296,
        label: 'FIFA World Cup U20',
        logoClass: 'icon-league league--fifa-world-cup-u20',
        favourite: false,
        hidden: false,
        priority: 121,
        live: false,
    },
    {
        id: 9021,
        label: 'T20 Blast',
        logoClass: 'icon-league league--t20',
        favourite: false,
        hidden: false,
        priority: 902,
        live: false,
    },
    {
        id: 9050,
        label: 'UEFA EURO Qualifications',
        logoClass: 'icon-league league--uefa',
        favourite: false,
        hidden: false,
        priority: 113,
        live: false,
    },
    {
        id: 109021,
        label: 'Golf head-to-head',
        logoClass: 'icon-league league--pga',
        favourite: false,
        hidden: false,
        priority: 1001,
        live: false,
    },
    {
        id: 109121,
        label: 'Golf Tournament Winner',
        logoClass: 'icon-league league--pga',
        favourite: false,
        hidden: false,
        priority: 1002,
        live: false,
    },
    {
        id: 18806,
        label: 'UEFA Nations League',
        logoClass: 'icon-league league--uefa-nations',
        favourite: false,
        hidden: false,
        priority: 114,
        live: false,
    },
    {
        id: 18821,
        label: 'CONCACAF Nations League',
        logoClass: 'icon-league league--concacaf-nations',
        favourite: false,
        hidden: false,
        priority: 115,
        live: false,
    },
    {
        id: 9288,
        label: 'UEFA EURO U21',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 120,
        live: false,
    },
    {
        id: 9042,
        label: 'UEFA Champions League Qualification',
        logoClass: 'icon-league league--ucl',
        favourite: false,
        hidden: false,
        priority: 111,
        live: false,
    },
    {
        id: 19216,
        label: 'UEFA Conference League',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 118,
        live: false,
    },
    {
        id: 9076,
        label: 'FIFA World Cup Women',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 119,
        live: false,
    },
    {
        id: 9073,
        label: 'UEFA Europa League',
        logoClass: 'icon-league league--uel',
        favourite: false,
        hidden: true,
        priority: 117,
        live: false,
    },
    {
        id: 9409,
        label: 'FIBA World Cup',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 303,
        live: false,
    },
    {
        id: 9536,
        label: 'Saudi Professional League',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 109,
        live: true,
    },
    {
        id: 9268,
        label: 'Serie A',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 109,
        live: true,
    },
    {
        id: 19199,
        label: 'CONMEBOL WC Qualification',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 110,
        live: false,
    },
    {
        id: 9132,
        label: 'FA Cup',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 122,
    },
    {
        id: 9134,
        label: 'Coupe de France',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 124,
    },
    {
        id: 9138,
        label: 'Copa del Rey',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 123,
    },
    {
        id: 9209,
        label: 'DFB Pokal',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 125,
    },
    {
        id: 9141,
        label: 'Coppa Italia',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 126,
    },
];

export const SPORTS_MAP: SportsMap = {
    9001: 'Football',
    9002: 'Football',
    9003: 'Baseball',
    9004: 'Basketball',
    9005: 'Basketball',
    9006: 'Hockey',
    9007: 'MMA',
    9008: 'Basketball',
    9010: 'Soccer',
    9011: 'Soccer',
    9012: 'Soccer',
    9013: 'Soccer',
    9014: 'Soccer',
    9015: 'Soccer',
    9016: 'Soccer',
    9017: 'Soccer',
    9018: 'Soccer',
    9019: 'Soccer',
    9445: 'Motosport',
    9497: 'Motosport',
    9153: 'Tennis',
    9156: 'Tennis',
    18977: 'eSports',
    18983: 'eSports',
    19138: 'eSports',
    9020: 'Cricket',
    9399: 'Basketball',
    18196: 'MMA',
    19595: 'MMA',
    9057: 'Soccer',
    9061: 'Soccer',
    9045: 'Soccer',
    9033: 'Hockey',
    9296: 'Soccer',
    9021: 'Cricket',
    9050: 'Soccer',
    109021: 'Golf',
    109121: 'Golf',
    18806: 'Soccer',
    18821: 'Soccer',
    9288: 'Soccer',
    9042: 'Soccer',
    19216: 'Soccer',
    9076: 'Soccer',
    9073: 'Soccer',
    9409: 'Basketball',
    9536: 'Soccer',
    9268: 'Soccer',
    19199: 'Soccer',
    9132: 'Soccer',
    9134: 'Soccer',
    9138: 'Soccer',
    9141: 'Soccer',
    9209: 'Soccer',
};

export const TAGS_OF_MARKETS_WITHOUT_DRAW_ODDS = [
    9001,
    9002,
    9003,
    9004,
    9005,
    9006,
    9008,
    9007,
    9445,
    9497,
    9153,
    9156,
    18977,
    18983,
    19138,
    9020,
    9399,
    18196,
    9021,
    109021,
    109121,
    9409,
    19595,
];

export const SPORTS_TAGS_MAP: SportsTagsMap = {
    Football: [9001, 9002],
    Baseball: [9003],
    Basketball: [9004, 9005, 9008, 9399, 9409],
    Hockey: [9006, 9033],
    Soccer: [
        9010,
        9011,
        9012,
        9013,
        9014,
        9015,
        9016,
        9017,
        9018,
        9019,
        9057,
        9061,
        9045,
        9296,
        9050,
        18806,
        18821,
        9288,
        9042,
        19216,
        9076,
        9073,
        9536,
        9268,
        19199,
        9132,
        9134,
        9138,
        9141,
        9209,
    ],
    MMA: [9007, 18196, 19595],
    Motosport: [9445, 9497],
    Tennis: [9153, 9156],
    eSports: [18977, 18983, 19138],
    Cricket: [9020, 9021],
    Golf: [109021, 109121],
    Live: [9004, 9011],
};

export const ENETPULSE_SPORTS = [
    9006,
    9011,
    9012,
    9013,
    9014,
    9015,
    9016,
    9017,
    9153,
    9156,
    18977,
    18983,
    19138,
    9399,
    18196,
    9057,
    9061,
    9045,
    9445,
    9033,
    9296,
    9050,
    9497,
    18806,
    18821,
    9288,
    9042,
    19216,
    9076,
    9073,
    9409,
    9536,
    9268,
    19199,
    19595,
    9132,
    9134,
    9138,
    9141,
    9209,
];

export const JSON_ODDS_SPORTS = [109021, 109121];

export const FIFA_WC_TAG = 9018;
export const FIFA_WC_U20_TAG = 9296;
export const IIHF_WC_TAG = 9033;
export const UEFA_TAGS = [9016, 9017, 18806, 18821, 9288, 9042, 19216, 9076, 9073];
export const MOTOSPORT_TAGS = [9445, 9497];
export const GOLF_TAGS = [109021, 109121];
export const GOLF_TOURNAMENT_WINNER_TAG = 109121;
export const EUROPA_LEAGUE_TAGS = [9017, 9073];
export const INTERNATIONAL_SPORTS = [18821, 19199, 9409, 9033, 9050, 9288, 18806, 9018, 9296, 9076];
export const BOXING_TAGS = [18196, 19595];

export const BetTypeNameMap: Record<BetType, string> = {
    [BetType.WINNER]: 'Winner',
    [BetType.SPREAD]: 'Handicap',
    [BetType.TOTAL]: 'Total',
    [BetType.DOUBLE_CHANCE]: 'Double chance',
    [BetType.WINNER_TOTAL]: 'Winner + Total',
    [BetType.TOTAL_ODD_EVEN]: 'Total odd/even',
    [BetType.HALFTIME_FULLTIME]: 'Half-time/Full-time',
    [BetType.GOALS]: 'Goals',
    [BetType.HALFTIME_FULLTIME_GOALS]: 'Half-time/Full-time + Goals',
    [BetType.BOTH_TEAMS_TO_SCORE]: 'Both teams to score',
    [BetType.WINNER2]: 'Winner',
    [BetType.WINNER3]: 'Winner',
    [BetType.SPREAD2]: 'Handicap',
    [BetType.TOTAL2]: 'Total',
    [BetType.PLAYER_PROPS_STRIKEOUTS]: 'Strikeouts',
    [BetType.PLAYER_PROPS_HOMERUNS]: 'Home runs',
    [BetType.PLAYER_PROPS_PASSING_YARDS]: 'Passing yards',
    [BetType.PLAYER_PROPS_PASSING_TOUCHDOWNS]: 'Passing touchdowns',
    [BetType.PLAYER_PROPS_RUSHING_YARDS]: 'Rushing yards',
    [BetType.PLAYER_PROPS_RECEIVING_YARDS]: 'Receiving yards',
    [BetType.PLAYER_PROPS_TOUCHDOWNS]: 'Scoring touchdown',
    [BetType.PLAYER_PROPS_FIELD_GOALS_MADE]: 'Field goals made',
    [BetType.PLAYER_PROPS_PITCHER_HITS_ALLOWED]: 'Pitcher hits allowed',
    [BetType.PLAYER_PROPS_POINTS]: 'Points',
    [BetType.PLAYER_PROPS_SHOTS]: 'Shots',
    [BetType.PLAYER_PROPS_GOALS]: 'Goals',
    [BetType.PLAYER_PROPS_HITS_RECORDED]: 'Hits recorded',
    [BetType.PLAYER_PROPS_REBOUNDS]: 'Rebounds',
    [BetType.PLAYER_PROPS_ASSISTS]: 'Assists',
    [BetType.PLAYER_PROPS_DOUBLE_DOUBLE]: 'Double double',
    [BetType.PLAYER_PROPS_TRIPLE_DOUBLE]: 'Triple double',
    [BetType.PLAYER_PROPS_RECEPTIONS]: 'Receptions',
    [BetType.PLAYER_PROPS_FIRST_TOUCHDOWN]: 'First touchdown',
    [BetType.PLAYER_PROPS_LAST_TOUCHDOWN]: 'Last touchdown',
    [BetType.PLAYER_PROPS_3PTS_MADE]: '3-points made',

    [BetType.FIRST_PERIOD_WINNER]: 'Winner 1st',
    [BetType.SECOND_PERIOD_WINNER]: 'Winner 2nd',
    [BetType.THIRD_PERIOD_WINNER]: 'Winner 3rd',
    [BetType.FOURTH_PERIOD_WINNER]: 'Winner 4th',
    [BetType.FIFTH_PERIOD_WINNER]: 'Winner 5th',
    [BetType.SIXTH_PERIOD_WINNER]: 'Winner 6th',
    [BetType.SEVENTH_PERIOD_WINNER]: 'Winner 7th',
    [BetType.EIGHTH_PERIOD_WINNER]: 'Winner 8th',
    [BetType.NINTH_PERIOD_WINNER]: 'Winner 9th',
    [BetType.FIRST_PERIOD_TOTAL]: 'Total 1st',
    [BetType.SECOND_PERIOD_TOTAL]: 'Total 2nd',
    [BetType.THIRD_PERIOD_TOTAL]: 'Total 3rd',
    [BetType.FOURTH_PERIOD_TOTAL]: 'Total 4th',
    [BetType.FIFTH_PERIOD_TOTAL]: 'Total 5th',
    [BetType.SIXTH_PERIOD_TOTAL]: 'Total 6th',
    [BetType.SEVENTH_PERIOD_TOTAL]: 'Total 7th',
    [BetType.EIGHTH_PERIOD_TOTAL]: 'Total 8th',
    [BetType.NINTH_PERIOD_TOTAL]: 'Total 9th',
    [BetType.FIRST_PERIOD_SPREAD]: 'Handicap 1st',
    [BetType.SECOND_PERIOD_SPREAD]: 'Handicap 2nd',
    [BetType.THIRD_PERIOD_SPREAD]: 'Handicap 3rd',
    [BetType.FOURTH_PERIOD_SPREAD]: 'Handicap 4th',
    [BetType.FIFTH_PERIOD_SPREAD]: 'Handicap 5th',
    [BetType.SIXTH_PERIOD_SPREAD]: 'Handicap 6th',
    [BetType.SEVENTH_PERIOD_SPREAD]: 'Handicap 7th',
    [BetType.EIGHTH_PERIOD_SPREAD]: 'Handicap 8th',
    [BetType.NINTH_PERIOD_SPREAD]: 'Handicap 9th',

    [BetType.FIRST_PERIOD_WINNER2]: 'Winner 1st',
    [BetType.SECOND_PERIOD_WINNER2]: 'Winner 2nd',
    [BetType.THIRD_PERIOD_WINNER2]: 'Winner 3rd',
    [BetType.FOURTH_PERIOD_WINNER2]: 'Winner 4th',
    [BetType.FIFTH_PERIOD_WINNER2]: 'Winner 5th',
    [BetType.SIXTH_PERIOD_WINNER2]: 'Winner 6th',
    [BetType.SEVENTH_PERIOD_WINNER2]: 'Winner 7th',
    [BetType.EIGHTH_PERIOD_WINNER2]: 'Winner 8th',
    [BetType.NINTH_PERIOD_WINNER2]: 'Winner 9th',
    [BetType.FIRST_PERIOD_TOTAL2]: 'Total 1st',
    [BetType.SECOND_PERIOD_TOTAL2]: 'Total 2nd',
    [BetType.THIRD_PERIOD_TOTAL2]: 'Total 3rd',
    [BetType.FOURTH_PERIOD_TOTAL2]: 'Total 4th',
    [BetType.FIFTH_PERIOD_TOTAL2]: 'Total 5th',
    [BetType.SIXTH_PERIOD_TOTAL2]: 'Total 6th',
    [BetType.SEVENTH_PERIOD_TOTAL2]: 'Total 7th',
    [BetType.EIGHTH_PERIOD_TOTAL2]: 'Total 8th',
    [BetType.NINTH_PERIOD_TOTAL2]: 'Total 9th',
    [BetType.FIRST_PERIOD_SPREAD2]: 'Handicap 1st',
    [BetType.SECOND_PERIOD_SPREAD2]: 'Handicap 2nd',
    [BetType.THIRD_PERIOD_SPREAD2]: 'Handicap 3rd',
    [BetType.FOURTH_PERIOD_SPREAD2]: 'Handicap 4th',
    [BetType.FIFTH_PERIOD_SPREAD2]: 'Handicap 5th',
    [BetType.SIXTH_PERIOD_SPREAD2]: 'Handicap 6th',
    [BetType.SEVENTH_PERIOD_SPREAD2]: 'Handicap 7th',
    [BetType.EIGHTH_PERIOD_SPREAD2]: 'Handicap 8th',
    [BetType.NINTH_PERIOD_SPREAD2]: 'Handicap 9th',

    [BetType.FIRST_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 1st',
    [BetType.SECOND_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 2nd',
    [BetType.THIRD_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 3rd',
    [BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 4th',
    [BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 5th',
    [BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 6th',
    [BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 7th',
    [BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 8th',
    [BetType.NINTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 9th',
    [BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 1st',
    [BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 2nd',
    [BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 3rd',
    [BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 4th',
    [BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 5th',
    [BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 6th',
    [BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 7th',
    [BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 8th',
    [BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 9th',

    [BetType.FIRST_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 1st',
    [BetType.SECOND_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 2nd',
    [BetType.THIRD_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 3rd',
    [BetType.FOURTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 4th',
    [BetType.FIFTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 5th',
    [BetType.SIXTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 6th',
    [BetType.SEVENTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 7th',
    [BetType.EIGHTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 8th',
    [BetType.NINTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 9th',
};

export const BetTypeTitleMap: Record<BetType, string> = {
    [BetType.WINNER]: 'winner',
    [BetType.SPREAD]: 'handicap',
    [BetType.TOTAL]: 'total',
    [BetType.DOUBLE_CHANCE]: 'double chance',
    [BetType.WINNER_TOTAL]: 'winner + total',
    [BetType.TOTAL_ODD_EVEN]: 'total odd/even',
    [BetType.HALFTIME_FULLTIME]: 'half-time/full-time',
    [BetType.GOALS]: 'goals',
    [BetType.HALFTIME_FULLTIME_GOALS]: 'half-time/full-time + goals',
    [BetType.BOTH_TEAMS_TO_SCORE]: 'Both teams to score',
    [BetType.WINNER2]: 'winner',
    [BetType.WINNER3]: 'winner',
    [BetType.SPREAD2]: 'handicap',
    [BetType.TOTAL2]: 'total',
    [BetType.PLAYER_PROPS_STRIKEOUTS]: 'strikeouts',
    [BetType.PLAYER_PROPS_HOMERUNS]: 'home runs',
    [BetType.PLAYER_PROPS_PASSING_YARDS]: 'passing yards',
    [BetType.PLAYER_PROPS_PASSING_TOUCHDOWNS]: 'passing touchdowns',
    [BetType.PLAYER_PROPS_RUSHING_YARDS]: 'rushing yards',
    [BetType.PLAYER_PROPS_RECEIVING_YARDS]: 'receiving yards',
    [BetType.PLAYER_PROPS_TOUCHDOWNS]: 'Who will score a touchdown in the game?',
    [BetType.PLAYER_PROPS_FIELD_GOALS_MADE]: 'field goals made',
    [BetType.PLAYER_PROPS_PITCHER_HITS_ALLOWED]: 'pitcher hits allowed',
    [BetType.PLAYER_PROPS_POINTS]: 'points',
    [BetType.PLAYER_PROPS_SHOTS]: 'shots',
    [BetType.PLAYER_PROPS_GOALS]: 'Who will score a goal in the game?',
    [BetType.PLAYER_PROPS_HITS_RECORDED]: 'hits recorded',
    [BetType.PLAYER_PROPS_REBOUNDS]: 'rebounds',
    [BetType.PLAYER_PROPS_ASSISTS]: 'assists',
    [BetType.PLAYER_PROPS_DOUBLE_DOUBLE]: 'double double',
    [BetType.PLAYER_PROPS_TRIPLE_DOUBLE]: 'triple double',
    [BetType.PLAYER_PROPS_RECEPTIONS]: 'receptions',
    [BetType.PLAYER_PROPS_FIRST_TOUCHDOWN]: 'Who will score the first touchdown in the game? (incl. OT)',
    [BetType.PLAYER_PROPS_LAST_TOUCHDOWN]: 'Who will score the last touchdown in the game?',
    [BetType.PLAYER_PROPS_3PTS_MADE]: '3-points made',

    [BetType.FIRST_PERIOD_WINNER]: 'winner',
    [BetType.SECOND_PERIOD_WINNER]: 'winner',
    [BetType.THIRD_PERIOD_WINNER]: 'winner',
    [BetType.FOURTH_PERIOD_WINNER]: 'winner',
    [BetType.FIFTH_PERIOD_WINNER]: 'winner',
    [BetType.SIXTH_PERIOD_WINNER]: 'winner',
    [BetType.SEVENTH_PERIOD_WINNER]: 'winner',
    [BetType.EIGHTH_PERIOD_WINNER]: 'winner',
    [BetType.NINTH_PERIOD_WINNER]: 'winner',
    [BetType.FIRST_PERIOD_TOTAL]: 'total',
    [BetType.SECOND_PERIOD_TOTAL]: 'total',
    [BetType.THIRD_PERIOD_TOTAL]: 'total',
    [BetType.FOURTH_PERIOD_TOTAL]: 'total',
    [BetType.FIFTH_PERIOD_TOTAL]: 'total',
    [BetType.SIXTH_PERIOD_TOTAL]: 'total',
    [BetType.SEVENTH_PERIOD_TOTAL]: 'total',
    [BetType.EIGHTH_PERIOD_TOTAL]: 'total',
    [BetType.NINTH_PERIOD_TOTAL]: 'total',
    [BetType.FIRST_PERIOD_SPREAD]: 'handicap',
    [BetType.SECOND_PERIOD_SPREAD]: 'handicap',
    [BetType.THIRD_PERIOD_SPREAD]: 'handicap',
    [BetType.FOURTH_PERIOD_SPREAD]: 'handicap',
    [BetType.FIFTH_PERIOD_SPREAD]: 'handicap',
    [BetType.SIXTH_PERIOD_SPREAD]: 'handicap',
    [BetType.SEVENTH_PERIOD_SPREAD]: 'handicap',
    [BetType.EIGHTH_PERIOD_SPREAD]: 'handicap',
    [BetType.NINTH_PERIOD_SPREAD]: 'handicap',

    [BetType.FIRST_PERIOD_WINNER2]: 'winner',
    [BetType.SECOND_PERIOD_WINNER2]: 'winner',
    [BetType.THIRD_PERIOD_WINNER2]: 'winner',
    [BetType.FOURTH_PERIOD_WINNER2]: 'winner',
    [BetType.FIFTH_PERIOD_WINNER2]: 'winner',
    [BetType.SIXTH_PERIOD_WINNER2]: 'winner',
    [BetType.SEVENTH_PERIOD_WINNER2]: 'winner',
    [BetType.EIGHTH_PERIOD_WINNER2]: 'winner',
    [BetType.NINTH_PERIOD_WINNER2]: 'winner',
    [BetType.FIRST_PERIOD_TOTAL2]: 'total',
    [BetType.SECOND_PERIOD_TOTAL2]: 'total',
    [BetType.THIRD_PERIOD_TOTAL2]: 'total',
    [BetType.FOURTH_PERIOD_TOTAL2]: 'total',
    [BetType.FIFTH_PERIOD_TOTAL2]: 'total',
    [BetType.SIXTH_PERIOD_TOTAL2]: 'total',
    [BetType.SEVENTH_PERIOD_TOTAL2]: 'total',
    [BetType.EIGHTH_PERIOD_TOTAL2]: 'total',
    [BetType.NINTH_PERIOD_TOTAL2]: 'total',
    [BetType.FIRST_PERIOD_SPREAD2]: 'handicap',
    [BetType.SECOND_PERIOD_SPREAD2]: 'handicap',
    [BetType.THIRD_PERIOD_SPREAD2]: 'handicap',
    [BetType.FOURTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.FIFTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.SIXTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.SEVENTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.EIGHTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.NINTH_PERIOD_SPREAD2]: 'handicap',

    [BetType.FIRST_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 1st',
    [BetType.SECOND_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 2nd',
    [BetType.THIRD_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 3rd',
    [BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 4th',
    [BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 5th',
    [BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 6th',
    [BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 7th',
    [BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 8th',
    [BetType.NINTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 9th',
    [BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 1st',
    [BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 2nd',
    [BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 3rd',
    [BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 4th',
    [BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 5th',
    [BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 6th',
    [BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 7th',
    [BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 8th',
    [BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 9th',

    [BetType.FIRST_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 1st',
    [BetType.SECOND_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 2nd',
    [BetType.THIRD_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 3rd',
    [BetType.FOURTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 4th',
    [BetType.FIFTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 5th',
    [BetType.SIXTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 6th',
    [BetType.SEVENTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 7th',
    [BetType.EIGHTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 8th',
    [BetType.NINTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 9th',
};

export const BetTypeMap: Record<BetType, string> = {
    [BetType.WINNER]: 'winner',
    [BetType.SPREAD]: 'spread',
    [BetType.TOTAL]: 'total',
    [BetType.DOUBLE_CHANCE]: 'doubleChance',
    [BetType.WINNER_TOTAL]: 'winnerTotal',
    [BetType.TOTAL_ODD_EVEN]: 'totalOddEven',
    [BetType.HALFTIME_FULLTIME]: 'halftimeFulltime',
    [BetType.BOTH_TEAMS_TO_SCORE]: 'bothTeamsToScore',
    [BetType.GOALS]: 'goals',
    [BetType.HALFTIME_FULLTIME_GOALS]: 'halftimeFulltimeGoals',
    [BetType.WINNER2]: 'winner2',
    [BetType.WINNER3]: 'winner3',
    [BetType.SPREAD2]: 'handicap2',
    [BetType.TOTAL2]: 'total2',
    [BetType.PLAYER_PROPS_HOMERUNS]: 'homeruns',
    [BetType.PLAYER_PROPS_STRIKEOUTS]: 'strikeouts',
    [BetType.PLAYER_PROPS_PASSING_YARDS]: 'passingYards',
    [BetType.PLAYER_PROPS_PASSING_TOUCHDOWNS]: 'passingTouchdowns',
    [BetType.PLAYER_PROPS_RUSHING_YARDS]: 'rushingYards',
    [BetType.PLAYER_PROPS_RECEIVING_YARDS]: 'receivingYards',
    [BetType.PLAYER_PROPS_TOUCHDOWNS]: 'touchdowns',
    [BetType.PLAYER_PROPS_FIELD_GOALS_MADE]: 'fieldGoalsMade',
    [BetType.PLAYER_PROPS_PITCHER_HITS_ALLOWED]: 'pitcherHitsAllowed',
    [BetType.PLAYER_PROPS_POINTS]: 'points',
    [BetType.PLAYER_PROPS_SHOTS]: 'shots',
    [BetType.PLAYER_PROPS_GOALS]: 'goals',
    [BetType.PLAYER_PROPS_HITS_RECORDED]: 'hitsRecorded',
    [BetType.PLAYER_PROPS_REBOUNDS]: 'rebounds',
    [BetType.PLAYER_PROPS_ASSISTS]: 'assists',
    [BetType.PLAYER_PROPS_DOUBLE_DOUBLE]: 'doubleDouble',
    [BetType.PLAYER_PROPS_TRIPLE_DOUBLE]: 'tripleDouble',
    [BetType.PLAYER_PROPS_RECEPTIONS]: 'receptions',
    [BetType.PLAYER_PROPS_FIRST_TOUCHDOWN]: 'firstTouchdown',
    [BetType.PLAYER_PROPS_LAST_TOUCHDOWN]: 'lastTouchdown',
    [BetType.PLAYER_PROPS_3PTS_MADE]: 'threePointsMade',

    [BetType.FIRST_PERIOD_WINNER]: 'firstPeriodWinner',
    [BetType.SECOND_PERIOD_WINNER]: 'secondPeriodWinner',
    [BetType.THIRD_PERIOD_WINNER]: 'thirdPeriodWinner',
    [BetType.FOURTH_PERIOD_WINNER]: 'fourthPeriodWinner',
    [BetType.FIFTH_PERIOD_WINNER]: 'fifthPeriodWinner',
    [BetType.SIXTH_PERIOD_WINNER]: 'sixthPeriodWinner',
    [BetType.SEVENTH_PERIOD_WINNER]: 'seventhPeriodWinner',
    [BetType.EIGHTH_PERIOD_WINNER]: 'eightPeriodWinner',
    [BetType.NINTH_PERIOD_WINNER]: 'ninthPeriodWinner',
    [BetType.FIRST_PERIOD_TOTAL]: 'firstPeriodTotal',
    [BetType.SECOND_PERIOD_TOTAL]: 'secondPeriodTotal',
    [BetType.THIRD_PERIOD_TOTAL]: 'thirdPeriodTotal',
    [BetType.FOURTH_PERIOD_TOTAL]: 'fourthPeriodTotal',
    [BetType.FIFTH_PERIOD_TOTAL]: 'fifthPeriodTotal',
    [BetType.SIXTH_PERIOD_TOTAL]: 'sixthPeriodTotal',
    [BetType.SEVENTH_PERIOD_TOTAL]: 'seventhPeriodTotal',
    [BetType.EIGHTH_PERIOD_TOTAL]: 'eightPeriodTotal',
    [BetType.NINTH_PERIOD_TOTAL]: 'ninthPeriodTotal',
    [BetType.FIRST_PERIOD_SPREAD]: 'firstPeriodSpread',
    [BetType.SECOND_PERIOD_SPREAD]: 'secondPeriodSpread',
    [BetType.THIRD_PERIOD_SPREAD]: 'thirdPeriodSpread',
    [BetType.FOURTH_PERIOD_SPREAD]: 'fourthPeriodSpread',
    [BetType.FIFTH_PERIOD_SPREAD]: 'fifthPeriodSpread',
    [BetType.SIXTH_PERIOD_SPREAD]: 'sixthPeriodSpread',
    [BetType.SEVENTH_PERIOD_SPREAD]: 'seventhPeriodSpread',
    [BetType.EIGHTH_PERIOD_SPREAD]: 'eightPeriodSpread',
    [BetType.NINTH_PERIOD_SPREAD]: 'ninthPeriodSpread',

    [BetType.FIRST_PERIOD_WINNER2]: 'firstPeriodWinner2',
    [BetType.SECOND_PERIOD_WINNER2]: 'secondPeriodWinner2',
    [BetType.THIRD_PERIOD_WINNER2]: 'thirdPeriodWinner2',
    [BetType.FOURTH_PERIOD_WINNER2]: 'fourthPeriodWinner2',
    [BetType.FIFTH_PERIOD_WINNER2]: 'fifthPeriodWinner2',
    [BetType.SIXTH_PERIOD_WINNER2]: 'sixthPeriodWinner2',
    [BetType.SEVENTH_PERIOD_WINNER2]: 'seventhPeriodWinner2',
    [BetType.EIGHTH_PERIOD_WINNER2]: 'eightPeriodWinner2',
    [BetType.NINTH_PERIOD_WINNER2]: 'ninthPeriodWinner2',
    [BetType.FIRST_PERIOD_TOTAL2]: 'firstPeriodTotal2',
    [BetType.SECOND_PERIOD_TOTAL2]: 'secondPeriodTotal2',
    [BetType.THIRD_PERIOD_TOTAL2]: 'thirdPeriodTotal2',
    [BetType.FOURTH_PERIOD_TOTAL2]: 'fourthPeriodTotal2',
    [BetType.FIFTH_PERIOD_TOTAL2]: 'fifthPeriodTotal2',
    [BetType.SIXTH_PERIOD_TOTAL2]: 'sixthPeriodTotal2',
    [BetType.SEVENTH_PERIOD_TOTAL2]: 'seventhPeriodTotal2',
    [BetType.EIGHTH_PERIOD_TOTAL2]: 'eightPeriodTotal2',
    [BetType.NINTH_PERIOD_TOTAL2]: 'ninthPeriodTotal2',
    [BetType.FIRST_PERIOD_SPREAD2]: 'firstPeriodSpread2',
    [BetType.SECOND_PERIOD_SPREAD2]: 'secondPeriodSpread2',
    [BetType.THIRD_PERIOD_SPREAD2]: 'thirdPeriodSpread2',
    [BetType.FOURTH_PERIOD_SPREAD2]: 'fourthPeriodSpread2',
    [BetType.FIFTH_PERIOD_SPREAD2]: 'fifthPeriodSpread2',
    [BetType.SIXTH_PERIOD_SPREAD2]: 'sixthPeriodSpread2',
    [BetType.SEVENTH_PERIOD_SPREAD2]: 'seventhPeriodSpread2',
    [BetType.EIGHTH_PERIOD_SPREAD2]: 'eightPeriodSpread2',
    [BetType.NINTH_PERIOD_SPREAD2]: 'ninthPeriodSpread2',

    [BetType.FIRST_PERIOD_TOTAL_ODD_EVEN]: 'firstPeriodTotalOddEven',
    [BetType.SECOND_PERIOD_TOTAL_ODD_EVEN]: 'secondPeriodTotalOddEven',
    [BetType.THIRD_PERIOD_TOTAL_ODD_EVEN]: 'thirdPeriodTotalOddEven',
    [BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN]: 'fourthPeriodTotalOddEven',
    [BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN]: 'fifthPeriodTotalOddEven',
    [BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN]: 'sixthPeriodTotalOddEven',
    [BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN]: 'seventhPeriodTotalOddEven',
    [BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN]: 'eightPeriodTotalOddEven',
    [BetType.NINTH_PERIOD_TOTAL_ODD_EVEN]: 'ninthPeriodTotalOddEven',
    [BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN]: 'firstPeriodTotal2OddEven',
    [BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN]: 'secondPeriodTotal2OddEven',
    [BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN]: 'thirdPeriodTotal2OddEven',
    [BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN]: 'fourthPeriodTotal2OddEven',
    [BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN]: 'fifthPeriodTotal2OddEven',
    [BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN]: 'sixthPeriodTotal2OddEven',
    [BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN]: 'seventhPeriodTotal2OddEven',
    [BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN]: 'eightPeriodTotal2OddEven',
    [BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN]: 'ninthPeriodTotal2OddEven',

    [BetType.FIRST_PERIOD_BOTH_TEAMS_TO_SCORE]: 'firstPeriodBothTeamsToScore',
    [BetType.SECOND_PERIOD_BOTH_TEAMS_TO_SCORE]: 'secondPeriodBothTeamsToScore',
    [BetType.THIRD_PERIOD_BOTH_TEAMS_TO_SCORE]: 'thirdPeriodBothTeamsToScore',
    [BetType.FOURTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'fourthPeriodBothTeamsToScore',
    [BetType.FIFTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'fifthPeriodBothTeamsToScore',
    [BetType.SIXTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'sixthPeriodBothTeamsToScore',
    [BetType.SEVENTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'seventhPeriodBothTeamsToScore',
    [BetType.EIGHTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'eightPeriodBothTeamsToScore',
    [BetType.NINTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'ninthPeriodBothTeamsToScore',
};

export const SCORING_MAP: SportsMap = {
    9001: 'points',
    9002: 'points',
    9003: 'points',
    9004: 'points',
    9005: 'points',
    9006: 'goals',
    9007: 'rounds',
    9008: 'points',
    9010: 'goals',
    9011: 'goals',
    9012: 'goals',
    9013: 'goals',
    9014: 'goals',
    9015: 'goals',
    9016: 'goals',
    9017: 'goals',
    9018: 'goals',
    9019: 'goals',
    9445: '',
    9497: '',
    9153: 'sets',
    9156: 'sets',
    18977: 'round',
    18983: 'round',
    19138: 'round',
    9020: 'points',
    9399: 'points',
    18196: 'rounds',
    9057: 'goals',
    9061: 'goals',
    9045: 'goals',
    9033: 'goals',
    9296: 'goals',
    9021: 'points',
    9050: 'goals',
    109021: '',
    109121: '',
    18806: 'goals',
    18821: 'goals',
    9288: 'goals',
    9042: 'goals',
    19216: 'goals',
    9076: 'goals',
    9073: 'goals',
    9409: 'points',
    9536: 'goals',
    9268: 'goals',
    19199: 'goals',
    19595: 'rounds',
    9132: 'goals',
    9134: 'goals',
    9138: 'goals',
    9141: 'goals',
    9209: 'goals',
};

export const MATCH_RESOLVE_MAP: SportsMap = {
    9001: 'overtime',
    9002: 'overtime',
    9003: 'overtime',
    9004: 'overtime',
    9005: 'overtime',
    9006: 'overtime',
    9007: '',
    9008: 'overtime',
    9010: 'regular',
    9011: 'regular',
    9012: 'regular',
    9013: 'regular',
    9014: 'regular',
    9015: 'regular',
    9016: 'regular',
    9017: 'regular',
    9018: 'regular',
    9019: 'regular',
    9445: '',
    9497: '',
    9153: '',
    9156: '',
    18977: '',
    18983: '',
    19138: '',
    9020: '',
    9399: 'overtime',
    18196: '',
    9057: 'regular',
    9061: 'regular',
    9045: 'regular',
    9033: 'regular',
    9296: 'regular',
    9021: '',
    9050: 'regular',
    109021: '',
    109121: '',
    18806: 'regular',
    18821: 'regular',
    9288: 'regular',
    9042: 'regular',
    19216: 'regular',
    9076: 'regular',
    9073: 'regular',
    9409: 'overtime',
    9536: 'regular',
    9268: 'regular',
    19199: 'regular',
    19595: '',
    9132: 'regular',
    9134: 'regular',
    9138: 'regular',
    9141: 'regular',
    9209: 'regular',
};

export const SPORT_PERIODS_MAP: SportsMap = {
    9001: 'quarter',
    9002: 'quarter',
    9003: 'inning',
    9004: 'quarter',
    9005: 'half',
    9006: 'period',
    9007: 'round',
    9008: 'quarter',
    9010: 'half',
    9011: 'half',
    9012: 'half',
    9013: 'half',
    9014: 'half',
    9015: 'half',
    9016: 'half',
    9017: 'half',
    9018: 'half',
    9019: 'half',
    9153: 'set',
    9156: 'set',
    18977: 'round',
    18983: 'round',
    19138: 'round',
    9020: 'inning',
    9399: 'quarter',
    18196: 'round',
    9057: 'half',
    9061: 'half',
    9045: 'half',
    9033: 'period',
    9296: 'half',
    9021: 'inning',
    9050: 'half',
    109021: '',
    109121: '',
    18806: 'half',
    18821: 'half',
    9288: 'half',
    9042: 'half',
    19216: 'half',
    9076: 'half',
    9073: 'half',
    9409: 'quarter',
    9536: 'half',
    9268: 'half',
    19199: 'half',
    19595: 'round',
    9132: 'half',
    9134: 'half',
    9138: 'half',
    9141: 'half',
    9209: 'half',
};

export const LIVE_SUPPORTED_LEAGUES = [9004, 9011, 9012, 9015, 9536];

export const BET_TYPES_BY_SPORT: Record<SportFilterEnum, BetType[]> = {
    [SportFilterEnum.Live]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Favourites]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.All]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Soccer]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Football]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Basketball]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Baseball]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Hockey]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.MMA]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Tennis]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.eSports]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Cricket]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Golf]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
};

export const BET_TYPE_GROUPS_BY_SPORT: Record<MarketSport, Partial<Record<BetTypeGroup, BetType[]>>> = {
    Soccer: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
        [BetTypeGroup.HANDICAP]: [
            BetType.SPREAD,
            BetType.SPREAD2,
            BetType.FIRST_PERIOD_SPREAD,
            BetType.SECOND_PERIOD_SPREAD,
            BetType.THIRD_PERIOD_SPREAD,
            BetType.FOURTH_PERIOD_SPREAD,
            BetType.FIFTH_PERIOD_SPREAD,
            BetType.SIXTH_PERIOD_SPREAD,
            BetType.SEVENTH_PERIOD_SPREAD,
            BetType.EIGHTH_PERIOD_SPREAD,
            BetType.NINTH_PERIOD_SPREAD,
            BetType.FIRST_PERIOD_SPREAD2,
            BetType.SECOND_PERIOD_SPREAD2,
            BetType.THIRD_PERIOD_SPREAD2,
            BetType.FOURTH_PERIOD_SPREAD2,
            BetType.FIFTH_PERIOD_SPREAD2,
            BetType.SIXTH_PERIOD_SPREAD2,
            BetType.SEVENTH_PERIOD_SPREAD2,
            BetType.EIGHTH_PERIOD_SPREAD2,
            BetType.NINTH_PERIOD_SPREAD2,
        ],
    },
    Basketball: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
        [BetTypeGroup.HANDICAP]: [
            BetType.SPREAD,
            BetType.SPREAD2,
            BetType.FIRST_PERIOD_SPREAD,
            BetType.SECOND_PERIOD_SPREAD,
            BetType.THIRD_PERIOD_SPREAD,
            BetType.FOURTH_PERIOD_SPREAD,
            BetType.FIFTH_PERIOD_SPREAD,
            BetType.SIXTH_PERIOD_SPREAD,
            BetType.SEVENTH_PERIOD_SPREAD,
            BetType.EIGHTH_PERIOD_SPREAD,
            BetType.NINTH_PERIOD_SPREAD,
            BetType.FIRST_PERIOD_SPREAD2,
            BetType.SECOND_PERIOD_SPREAD2,
            BetType.THIRD_PERIOD_SPREAD2,
            BetType.FOURTH_PERIOD_SPREAD2,
            BetType.FIFTH_PERIOD_SPREAD2,
            BetType.SIXTH_PERIOD_SPREAD2,
            BetType.SEVENTH_PERIOD_SPREAD2,
            BetType.EIGHTH_PERIOD_SPREAD2,
            BetType.NINTH_PERIOD_SPREAD2,
        ],
    },
    MMA: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Tennis: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Football: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Baseball: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Hockey: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Esports: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Cricket: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Golf: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
};

export const SPORT_ID_MAP_ENETPULSE: Record<number, number> = {
    18: 320, // Hockey Norway
    24: 6, // NHL
    33: 33, // Hockey World Championship
    16: 42, // Champions League
    45: 45, // Copa Libertadores
    11: 47, // EPL
    50: 50, // EURO Qualification
    12: 53, // France League 1
    13: 54, // Bundesliga
    15: 55, // Seria A
    57: 57, // Netherlands League 1
    61: 61, // Portugal League 1
    17: 73, // Europa League
    76: 76, // World Cup Woman
    14: 87, // La Liga
    153: 153, // Tennis GS
    156: 156, // Tennis Masters 1000
    132: 132, // FA Cup
    134: 134, // Coupe de France
    138: 138, // Copa del Rey
    141: 141, // Coppa Italia
    209: 209, // DFB Pokal
    268: 268, // Brazil Football League
    288: 288, // EURO U21
    296: 296, // FIFA WC U20
    310: 310, // Hockey Czech
    319: 319, // Hockey Finland
    322: 322, // Hockey Germany
    327: 327, // Hockey Switzerland
    399: 399, // EuroLeague
    409: 409, // FIBA World Cup
    445: 445, // F1
    497: 497, // Moto GP
    536: 536, // Saudi Arabia Football League
    9196: 9196, // Boxing
    9806: 9806, // UEFA League of Nations
    9821: 9821, // CONCACAF League of Nations
    9977: 9977, // CsGo
    9983: 9983, // Dota
    10138: 10138, // LOL
    10199: 10199, // World Cup Qualifications CONMBOL
    10216: 10216, // Europa Conference League
    10595: 10595, // Non-Title Boxing
};
