import { BetType, BetTypeGroup, SportFilterEnum } from 'enums/markets';
import { MarketSport, SportsMap, SportsTagsMap, Tags } from 'types/markets';

export const TAGS_LIST: Tags = [
    {
        id: 1,
        label: 'NCAA Football',
        logo: `/logos/leagueLogos/ncaa.webp`,
        logoClass: 'icon-league league--ncaa',
        favourite: false,
        hidden: false,
        priority: 202,
        live: false,
    },
    {
        id: 2,
        label: 'NFL',
        logo: `/logos/leagueLogos/nfl.webp`,
        logoClass: 'icon-league league--nfl',
        favourite: false,
        hidden: false,
        priority: 201,
        live: false,
    },
    {
        id: 3,
        label: 'MLB',
        logo: `/logos/leagueLogos/mlb.webp`,
        logoClass: 'icon-league league--mlb',
        favourite: false,
        hidden: false,
        priority: 401,
        live: false,
    },
    {
        id: 4,
        label: 'NBA',
        logo: `/logos/leagueLogos/nba.webp`,
        logoClass: 'icon-league league--nba',
        favourite: false,
        hidden: false,
        priority: 301,
        live: true,
    },
    {
        id: 5,
        label: 'NCAA Basketball',
        logoClass: 'icon-league league--ncaa',
        favourite: false,
        hidden: false,
        priority: 302,
        live: false,
    },
    {
        id: 6,
        label: 'NHL',
        logo: `/logos/leagueLogos/nhl.webp`,
        logoClass: 'icon-league league--nhl',
        favourite: false,
        hidden: false,
        priority: 501,
        live: true,
    },
    {
        id: 7,
        label: 'UFC',
        logo: '/logos/leagueLogos/ufc.webp',
        logoClass: 'icon-league league--ufc',
        favourite: false,
        hidden: false,
        priority: 601,
        live: false,
    },
    {
        id: 8,
        label: 'WNBA',
        logoClass: 'icon-league league--wnba',
        favourite: false,
        hidden: false,
        priority: 304,
        live: false,
    },
    {
        id: 10,
        label: 'MLS',
        logo: `/logos/leagueLogos/mls.webp`,
        logoClass: 'icon-league league--mls',
        favourite: false,
        hidden: false,
        priority: 106,
        live: false,
    },
    {
        id: 11,
        label: 'EPL',
        logo: `/logos/leagueLogos/EPL.webp`,
        logoClass: 'icon-league league--epl',
        favourite: false,
        hidden: false,
        priority: 101,
        live: true,
    },
    {
        id: 12,
        label: 'Ligue 1',
        logo: `/logos/leagueLogos/Ligue1.webp`,
        logoClass: 'icon-league league--ligue1',
        favourite: false,
        hidden: false,
        priority: 105,
        live: true,
    },
    {
        id: 13,
        label: 'Bundesliga',
        logo: '/logos/leagueLogos/bundesliga.webp',
        logoClass: 'icon-league league--bundesliga',
        favourite: false,
        hidden: false,
        priority: 104,
        live: false,
    },
    {
        id: 14,
        label: 'La Liga',
        logo: `/logos/leagueLogos/LaLiga.webp`,
        logoClass: 'icon-league league--la-liga',
        favourite: false,
        hidden: false,
        priority: 102,
        live: false,
    },
    {
        id: 15,
        label: 'Serie A',
        logo: `/logos/leagueLogos/seriea.webp`,
        logoClass: 'icon-league league--serie-a',
        favourite: false,
        hidden: false,
        priority: 103,
        live: true,
    },
    {
        id: 16,
        label: 'UEFA Champions League',
        logo: `/logos/leagueLogos/ucl-white.webp`,
        logoClass: 'icon-league league--ucl',
        favourite: false,
        hidden: false,
        priority: 110,
        live: false,
    },
    {
        id: 17,
        label: 'UEFA Europa League',
        logo: ``,
        logoClass: 'icon-league league--uel',
        favourite: false,
        hidden: false,
        priority: 111,
        live: false,
    },
    {
        id: 18,
        label: 'FIFA World Cup',
        logo: ``,
        logoClass: 'icon-league league--fifa-world-cup',
        favourite: false,
        hidden: true,
        priority: 0,
        live: false,
    },
    {
        id: 19,
        label: 'J1 League',
        logo: ``,
        logoClass: 'icon-league league--j1',
        favourite: false,
        hidden: false,
        priority: 109,
        live: true,
    },
    // {
    //     id: 9445,
    //     label: 'Formula 1',
    //     logo: '/logos/leagueLogos/f1.webp',
    //     logoClass: 'icon-league league--f1',
    //     favourite: false,
    //     hidden: false,
    //     priority: 701,
    // },
    // {
    //     id: 9497,
    //     label: 'MotoGP',
    //     logo: `/logos/leagueLogos/motogp.webp`,
    //     logoClass: 'icon-league league--motogp',
    //     favourite: false,
    //     hidden: false,
    //     priority: 702,
    // },
    {
        id: 9153,
        label: 'Grand Slam',
        logo: `/logos/Tennis/atp.png`,
        logoClass: 'icon-league league--atp',
        favourite: false,
        hidden: false,
        priority: 602,
        live: false,
    },
    {
        id: 9156,
        label: 'ATP Events',
        logo: `/logos/Tennis/atp.png`,
        logoClass: 'icon-league league--atp',
        favourite: false,
        hidden: false,
        priority: 603,
        live: false,
    },
    {
        id: 18977,
        label: 'CS GO',
        logoClass: 'icon-league league--csgo',
        favourite: false,
        hidden: false,
        priority: 801,
        live: false,
    },
    {
        id: 18983,
        label: 'DOTA 2',
        logoClass: 'icon-league league--dota2',
        favourite: false,
        hidden: false,
        priority: 802,
        live: false,
    },
    {
        id: 19138,
        label: 'LOL',
        logoClass: 'icon-league league--lol',
        favourite: false,
        hidden: false,
        priority: 803,
        live: false,
    },
    {
        id: 20,
        label: 'Indian Premier League',
        logoClass: 'icon-league league--ipl',
        favourite: false,
        hidden: false,
        priority: 901,
        live: false,
    },
    {
        id: 399,
        label: 'Euroleague',
        logoClass: 'icon-league league--euroleague',
        favourite: false,
        hidden: false,
        priority: 303,
        live: false,
    },
    {
        id: 9196,
        label: 'Boxing',
        logoClass: 'icon-league league--boxing',
        favourite: false,
        hidden: false,
        priority: 602,
        live: false,
    },
    {
        id: 10595,
        label: 'Boxing',
        logoClass: 'icon-league league--boxing',
        favourite: false,
        hidden: true,
        priority: 603,
        live: false,
    },
    {
        id: 57,
        label: 'Eredivisie',
        logoClass: 'icon-league league--eredivisie',
        favourite: false,
        hidden: false,
        priority: 107,
        live: false,
    },
    {
        id: 61,
        label: 'Primeira Liga',
        logoClass: 'icon-league league--portugal',
        favourite: false,
        hidden: false,
        priority: 108,
        live: false,
    },
    {
        id: 45,
        label: 'Copa Libertadores',
        logoClass: 'icon-league league--copa-libertadores',
        favourite: false,
        hidden: false,
        priority: 112,
        live: false,
    },
    {
        id: 33,
        label: 'IIHF World Championship',
        logoClass: 'icon-league league--iihf',
        favourite: false,
        hidden: false,
        priority: 502,
        live: false,
    },
    {
        id: 296,
        label: 'FIFA World Cup U20',
        logoClass: 'icon-league league--fifa-world-cup-u20',
        favourite: false,
        hidden: false,
        priority: 121,
        live: false,
    },
    {
        id: 21,
        label: 'T20 Blast',
        logoClass: 'icon-league league--t20',
        favourite: false,
        hidden: false,
        priority: 902,
        live: false,
    },
    {
        id: 50,
        label: 'UEFA EURO Qualifications',
        logoClass: 'icon-league league--uefa',
        favourite: false,
        hidden: false,
        priority: 113,
        live: false,
    },
    {
        id: 100021,
        label: 'Golf head-to-head',
        logoClass: 'icon-league league--pga',
        favourite: false,
        hidden: false,
        priority: 1001,
        live: false,
    },
    {
        id: 100121,
        label: 'Golf Tournament Winner',
        logoClass: 'icon-league league--pga',
        favourite: false,
        hidden: false,
        priority: 1002,
        live: false,
    },
    {
        id: 9806,
        label: 'UEFA Nations League',
        logoClass: 'icon-league league--uefa-nations',
        favourite: false,
        hidden: false,
        priority: 114,
        live: false,
    },
    {
        id: 9821,
        label: 'CONCACAF Nations League',
        logoClass: 'icon-league league--concacaf-nations',
        favourite: false,
        hidden: false,
        priority: 115,
        live: false,
    },
    {
        id: 288,
        label: 'UEFA EURO U21',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 120,
        live: false,
    },
    {
        id: 42,
        label: 'UEFA Champions League Qualification',
        logoClass: 'icon-league league--ucl',
        favourite: false,
        hidden: false,
        priority: 111,
        live: false,
    },
    {
        id: 10216,
        label: 'UEFA Conference League',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 118,
        live: false,
    },
    {
        id: 76,
        label: 'FIFA World Cup Women',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 119,
        live: false,
    },
    {
        id: 73,
        label: 'UEFA Europa League',
        logoClass: 'icon-league league--uel',
        favourite: false,
        hidden: true,
        priority: 117,
        live: false,
    },
    {
        id: 409,
        label: 'FIBA World Cup',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 303,
        live: false,
    },
    {
        id: 536,
        label: 'Saudi Professional League',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 109,
        live: true,
    },
    {
        id: 268,
        label: 'Serie A',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 109,
        live: true,
    },
    {
        id: 10199,
        label: 'CONMEBOL WC Qualification',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 110,
        live: false,
    },
    {
        id: 132,
        label: 'FA Cup',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 122,
    },
    {
        id: 134,
        label: 'Coupe de France',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 124,
    },
    {
        id: 138,
        label: 'Copa del Rey',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 123,
    },
    {
        id: 209,
        label: 'DFB Pokal',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 125,
    },
    {
        id: 141,
        label: 'Coppa Italia',
        logoClass: '',
        favourite: false,
        hidden: false,
        priority: 126,
    },
];

export const SPORTS_MAP: SportsMap = {
    1: 'Football',
    2: 'Football',
    3: 'Baseball',
    4: 'Basketball',
    5: 'Basketball',
    6: 'Hockey',
    7: 'MMA',
    8: 'Basketball',
    10: 'Soccer',
    11: 'Soccer',
    12: 'Soccer',
    13: 'Soccer',
    14: 'Soccer',
    15: 'Soccer',
    16: 'Soccer',
    17: 'Soccer',
    18: 'Soccer',
    19: 'Soccer',
    445: 'Motosport',
    497: 'Motosport',
    153: 'Tennis',
    156: 'Tennis',
    9977: 'eSports',
    9983: 'eSports',
    10138: 'eSports',
    20: 'Cricket',
    399: 'Basketball',
    9196: 'MMA',
    10595: 'MMA',
    57: 'Soccer',
    61: 'Soccer',
    45: 'Soccer',
    33: 'Hockey',
    296: 'Soccer',
    21: 'Cricket',
    50: 'Soccer',
    100021: 'Golf',
    100121: 'Golf',
    9806: 'Soccer',
    9821: 'Soccer',
    288: 'Soccer',
    42: 'Soccer',
    10216: 'Soccer',
    76: 'Soccer',
    73: 'Soccer',
    409: 'Basketball',
    536: 'Soccer',
    268: 'Soccer',
    10199: 'Soccer',
    132: 'Soccer',
    134: 'Soccer',
    138: 'Soccer',
    141: 'Soccer',
    209: 'Soccer',
};

export const TAGS_OF_MARKETS_WITHOUT_DRAW_ODDS = [
    1,
    2,
    3,
    4,
    5,
    6,
    8,
    7,
    445,
    497,
    153,
    156,
    9977,
    9983,
    10138,
    20,
    399,
    9196,
    21,
    100021,
    100121,
    409,
    10595,
];

export const SPORTS_TAGS_MAP: SportsTagsMap = {
    Football: [1, 2],
    Baseball: [3],
    Basketball: [4, 5, 8, 399, 409],
    Hockey: [6, 33],
    Soccer: [
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        57,
        61,
        45,
        296,
        50,
        9806,
        9821,
        288,
        42,
        10216,
        76,
        73,
        536,
        268,
        10199,
        132,
        134,
        138,
        141,
        209,
    ],
    MMA: [7, 9196, 9595],
    Motosport: [445, 497],
    Tennis: [153, 156],
    eSports: [9977, 9983, 10138],
    Cricket: [20, 21],
    Golf: [100021, 100121],
    Live: [4, 11],
};

export const ENETPULSE_SPORTS = [
    6,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    153,
    156,
    9977,
    9983,
    10138,
    399,
    196,
    57,
    61,
    45,
    445,
    33,
    296,
    50,
    497,
    9806,
    9821,
    288,
    42,
    10216,
    76,
    73,
    409,
    536,
    268,
    10199,
    10595,
    132,
    134,
    138,
    141,
    209,
];

export const JSON_ODDS_SPORTS = [100021, 100121];

export const FIFA_WC_TAG = 18;
export const FIFA_WC_U20_TAG = 296;
export const IIHF_WC_TAG = 33;
export const UEFA_TAGS = [16, 17, 9806, 9821, 288, 42, 10216, 76, 73];
export const MOTOSPORT_TAGS = [445, 497];
export const GOLF_TAGS = [100021, 100121];
export const GOLF_TOURNAMENT_WINNER_TAG = 100121;
export const EUROPA_LEAGUE_TAGS = [17, 73];
export const INTERNATIONAL_SPORTS = [9821, 10199, 409, 33, 50, 288, 9806, 18, 296, 76];
export const BOXING_TAGS = [9196, 10595];

export const BetTypeNameMap: Record<BetType, string> = {
    [BetType.WINNER]: 'Winner',
    [BetType.SPREAD]: 'Handicap',
    [BetType.TOTAL]: 'Total',
    [BetType.DOUBLE_CHANCE]: 'Double chance',
    [BetType.WINNER_TOTAL]: 'Winner + Total',
    [BetType.TOTAL_ODD_EVEN]: 'Total odd/even',
    [BetType.HALFTIME_FULLTIME]: 'Half-time/Full-time',
    [BetType.GOALS]: 'Goals',
    [BetType.HALFTIME_FULLTIME_GOALS]: 'Half-time/Full-time + Goals',
    [BetType.BOTH_TEAMS_TO_SCORE]: 'Both teams to score',
    [BetType.WINNER2]: 'Winner',
    [BetType.WINNER3]: 'Winner',
    [BetType.SPREAD2]: 'Handicap',
    [BetType.TOTAL2]: 'Total',
    [BetType.FIRST_PERIOD_DOUBLE_CHANCE]: 'Double chance 1st',
    [BetType.SECOND_PERIOD_DOUBLE_CHANCE]: 'Double chance 2nd',
    [BetType.TOTAL_HOME_TEAM]: 'Total home team',
    [BetType.TOTAL_AWAY_TEAM]: 'Total away team',
    [BetType.PLAYER_PROPS_STRIKEOUTS]: 'Strikeouts',
    [BetType.PLAYER_PROPS_HOMERUNS]: 'Home runs',
    [BetType.PLAYER_PROPS_PASSING_YARDS]: 'Passing yards',
    [BetType.PLAYER_PROPS_PASSING_TOUCHDOWNS]: 'Passing touchdowns',
    [BetType.PLAYER_PROPS_RUSHING_YARDS]: 'Rushing yards',
    [BetType.PLAYER_PROPS_RECEIVING_YARDS]: 'Receiving yards',
    [BetType.PLAYER_PROPS_TOUCHDOWNS]: 'Scoring touchdown',
    [BetType.PLAYER_PROPS_FIELD_GOALS_MADE]: 'Field goals made',
    [BetType.PLAYER_PROPS_PITCHER_HITS_ALLOWED]: 'Pitcher hits allowed',
    [BetType.PLAYER_PROPS_POINTS]: 'Points',
    [BetType.PLAYER_PROPS_SHOTS]: 'Shots',
    [BetType.PLAYER_PROPS_GOALS]: 'Goals',
    [BetType.PLAYER_PROPS_HITS_RECORDED]: 'Hits recorded',
    [BetType.PLAYER_PROPS_REBOUNDS]: 'Rebounds',
    [BetType.PLAYER_PROPS_ASSISTS]: 'Assists',
    [BetType.PLAYER_PROPS_DOUBLE_DOUBLE]: 'Double double',
    [BetType.PLAYER_PROPS_TRIPLE_DOUBLE]: 'Triple double',
    [BetType.PLAYER_PROPS_RECEPTIONS]: 'Receptions',
    [BetType.PLAYER_PROPS_FIRST_TOUCHDOWN]: 'First touchdown',
    [BetType.PLAYER_PROPS_LAST_TOUCHDOWN]: 'Last touchdown',
    [BetType.PLAYER_PROPS_3PTS_MADE]: '3-points made',

    [BetType.FIRST_PERIOD_WINNER]: 'Winner 1st',
    [BetType.SECOND_PERIOD_WINNER]: 'Winner 2nd',
    [BetType.THIRD_PERIOD_WINNER]: 'Winner 3rd',
    [BetType.FOURTH_PERIOD_WINNER]: 'Winner 4th',
    [BetType.FIFTH_PERIOD_WINNER]: 'Winner 5th',
    [BetType.SIXTH_PERIOD_WINNER]: 'Winner 6th',
    [BetType.SEVENTH_PERIOD_WINNER]: 'Winner 7th',
    [BetType.EIGHTH_PERIOD_WINNER]: 'Winner 8th',
    [BetType.NINTH_PERIOD_WINNER]: 'Winner 9th',
    [BetType.FIRST_PERIOD_TOTAL]: 'Total 1st',
    [BetType.SECOND_PERIOD_TOTAL]: 'Total 2nd',
    [BetType.THIRD_PERIOD_TOTAL]: 'Total 3rd',
    [BetType.FOURTH_PERIOD_TOTAL]: 'Total 4th',
    [BetType.FIFTH_PERIOD_TOTAL]: 'Total 5th',
    [BetType.SIXTH_PERIOD_TOTAL]: 'Total 6th',
    [BetType.SEVENTH_PERIOD_TOTAL]: 'Total 7th',
    [BetType.EIGHTH_PERIOD_TOTAL]: 'Total 8th',
    [BetType.NINTH_PERIOD_TOTAL]: 'Total 9th',
    [BetType.FIRST_PERIOD_SPREAD]: 'Handicap 1st',
    [BetType.SECOND_PERIOD_SPREAD]: 'Handicap 2nd',
    [BetType.THIRD_PERIOD_SPREAD]: 'Handicap 3rd',
    [BetType.FOURTH_PERIOD_SPREAD]: 'Handicap 4th',
    [BetType.FIFTH_PERIOD_SPREAD]: 'Handicap 5th',
    [BetType.SIXTH_PERIOD_SPREAD]: 'Handicap 6th',
    [BetType.SEVENTH_PERIOD_SPREAD]: 'Handicap 7th',
    [BetType.EIGHTH_PERIOD_SPREAD]: 'Handicap 8th',
    [BetType.NINTH_PERIOD_SPREAD]: 'Handicap 9th',

    [BetType.FIRST_PERIOD_WINNER2]: 'Winner 1st',
    [BetType.SECOND_PERIOD_WINNER2]: 'Winner 2nd',
    [BetType.THIRD_PERIOD_WINNER2]: 'Winner 3rd',
    [BetType.FOURTH_PERIOD_WINNER2]: 'Winner 4th',
    [BetType.FIFTH_PERIOD_WINNER2]: 'Winner 5th',
    [BetType.SIXTH_PERIOD_WINNER2]: 'Winner 6th',
    [BetType.SEVENTH_PERIOD_WINNER2]: 'Winner 7th',
    [BetType.EIGHTH_PERIOD_WINNER2]: 'Winner 8th',
    [BetType.NINTH_PERIOD_WINNER2]: 'Winner 9th',
    [BetType.FIRST_PERIOD_TOTAL2]: 'Total 1st',
    [BetType.SECOND_PERIOD_TOTAL2]: 'Total 2nd',
    [BetType.THIRD_PERIOD_TOTAL2]: 'Total 3rd',
    [BetType.FOURTH_PERIOD_TOTAL2]: 'Total 4th',
    [BetType.FIFTH_PERIOD_TOTAL2]: 'Total 5th',
    [BetType.SIXTH_PERIOD_TOTAL2]: 'Total 6th',
    [BetType.SEVENTH_PERIOD_TOTAL2]: 'Total 7th',
    [BetType.EIGHTH_PERIOD_TOTAL2]: 'Total 8th',
    [BetType.NINTH_PERIOD_TOTAL2]: 'Total 9th',
    [BetType.FIRST_PERIOD_SPREAD2]: 'Handicap 1st',
    [BetType.SECOND_PERIOD_SPREAD2]: 'Handicap 2nd',
    [BetType.THIRD_PERIOD_SPREAD2]: 'Handicap 3rd',
    [BetType.FOURTH_PERIOD_SPREAD2]: 'Handicap 4th',
    [BetType.FIFTH_PERIOD_SPREAD2]: 'Handicap 5th',
    [BetType.SIXTH_PERIOD_SPREAD2]: 'Handicap 6th',
    [BetType.SEVENTH_PERIOD_SPREAD2]: 'Handicap 7th',
    [BetType.EIGHTH_PERIOD_SPREAD2]: 'Handicap 8th',
    [BetType.NINTH_PERIOD_SPREAD2]: 'Handicap 9th',

    [BetType.FIRST_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 1st',
    [BetType.SECOND_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 2nd',
    [BetType.THIRD_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 3rd',
    [BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 4th',
    [BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 5th',
    [BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 6th',
    [BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 7th',
    [BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 8th',
    [BetType.NINTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 9th',
    [BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 1st',
    [BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 2nd',
    [BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 3rd',
    [BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 4th',
    [BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 5th',
    [BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 6th',
    [BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 7th',
    [BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 8th',
    [BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 9th',

    [BetType.FIRST_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 1st',
    [BetType.SECOND_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 2nd',
    [BetType.THIRD_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 3rd',
    [BetType.FOURTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 4th',
    [BetType.FIFTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 5th',
    [BetType.SIXTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 6th',
    [BetType.SEVENTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 7th',
    [BetType.EIGHTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 8th',
    [BetType.NINTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 9th',

    [BetType.FIRST_PERIOD_HOME_TEAM]: 'Total home team 1st',
    [BetType.FIRST_PERIOD_AWAY_TEAM]: 'Total away team 2ns',
    [BetType.SECOND_PERIOD_HOME_TEAM]: 'Total home team 1st',
    [BetType.SECOND_PERIOD_AWAY_TEAM]: 'Total away team 2nd',
};

export const BetTypeTitleMap: Record<BetType, string> = {
    [BetType.WINNER]: 'winner',
    [BetType.SPREAD]: 'handicap',
    [BetType.TOTAL]: 'total',
    [BetType.DOUBLE_CHANCE]: 'double chance',
    [BetType.WINNER_TOTAL]: 'winner + total',
    [BetType.TOTAL_ODD_EVEN]: 'total odd/even',
    [BetType.HALFTIME_FULLTIME]: 'half-time/full-time',
    [BetType.GOALS]: 'goals',
    [BetType.HALFTIME_FULLTIME_GOALS]: 'half-time/full-time + goals',
    [BetType.BOTH_TEAMS_TO_SCORE]: 'Both teams to score',
    [BetType.WINNER2]: 'winner',
    [BetType.WINNER3]: 'winner',
    [BetType.SPREAD2]: 'handicap',
    [BetType.TOTAL2]: 'total',
    [BetType.FIRST_PERIOD_DOUBLE_CHANCE]: 'Double chance 1st',
    [BetType.SECOND_PERIOD_DOUBLE_CHANCE]: 'Double chance 2nd',
    [BetType.TOTAL_HOME_TEAM]: 'Total home team',
    [BetType.TOTAL_AWAY_TEAM]: 'Total away team',
    [BetType.PLAYER_PROPS_STRIKEOUTS]: 'strikeouts',
    [BetType.PLAYER_PROPS_HOMERUNS]: 'home runs',
    [BetType.PLAYER_PROPS_PASSING_YARDS]: 'passing yards',
    [BetType.PLAYER_PROPS_PASSING_TOUCHDOWNS]: 'passing touchdowns',
    [BetType.PLAYER_PROPS_RUSHING_YARDS]: 'rushing yards',
    [BetType.PLAYER_PROPS_RECEIVING_YARDS]: 'receiving yards',
    [BetType.PLAYER_PROPS_TOUCHDOWNS]: 'Who will score a touchdown in the game?',
    [BetType.PLAYER_PROPS_FIELD_GOALS_MADE]: 'field goals made',
    [BetType.PLAYER_PROPS_PITCHER_HITS_ALLOWED]: 'pitcher hits allowed',
    [BetType.PLAYER_PROPS_POINTS]: 'points',
    [BetType.PLAYER_PROPS_SHOTS]: 'shots',
    [BetType.PLAYER_PROPS_GOALS]: 'Who will score a goal in the game?',
    [BetType.PLAYER_PROPS_HITS_RECORDED]: 'hits recorded',
    [BetType.PLAYER_PROPS_REBOUNDS]: 'rebounds',
    [BetType.PLAYER_PROPS_ASSISTS]: 'assists',
    [BetType.PLAYER_PROPS_DOUBLE_DOUBLE]: 'double double',
    [BetType.PLAYER_PROPS_TRIPLE_DOUBLE]: 'triple double',
    [BetType.PLAYER_PROPS_RECEPTIONS]: 'receptions',
    [BetType.PLAYER_PROPS_FIRST_TOUCHDOWN]: 'Who will score the first touchdown in the game? (incl. OT)',
    [BetType.PLAYER_PROPS_LAST_TOUCHDOWN]: 'Who will score the last touchdown in the game?',
    [BetType.PLAYER_PROPS_3PTS_MADE]: '3-points made',

    [BetType.FIRST_PERIOD_WINNER]: 'winner',
    [BetType.SECOND_PERIOD_WINNER]: 'winner',
    [BetType.THIRD_PERIOD_WINNER]: 'winner',
    [BetType.FOURTH_PERIOD_WINNER]: 'winner',
    [BetType.FIFTH_PERIOD_WINNER]: 'winner',
    [BetType.SIXTH_PERIOD_WINNER]: 'winner',
    [BetType.SEVENTH_PERIOD_WINNER]: 'winner',
    [BetType.EIGHTH_PERIOD_WINNER]: 'winner',
    [BetType.NINTH_PERIOD_WINNER]: 'winner',
    [BetType.FIRST_PERIOD_TOTAL]: 'total',
    [BetType.SECOND_PERIOD_TOTAL]: 'total',
    [BetType.THIRD_PERIOD_TOTAL]: 'total',
    [BetType.FOURTH_PERIOD_TOTAL]: 'total',
    [BetType.FIFTH_PERIOD_TOTAL]: 'total',
    [BetType.SIXTH_PERIOD_TOTAL]: 'total',
    [BetType.SEVENTH_PERIOD_TOTAL]: 'total',
    [BetType.EIGHTH_PERIOD_TOTAL]: 'total',
    [BetType.NINTH_PERIOD_TOTAL]: 'total',
    [BetType.FIRST_PERIOD_SPREAD]: 'handicap',
    [BetType.SECOND_PERIOD_SPREAD]: 'handicap',
    [BetType.THIRD_PERIOD_SPREAD]: 'handicap',
    [BetType.FOURTH_PERIOD_SPREAD]: 'handicap',
    [BetType.FIFTH_PERIOD_SPREAD]: 'handicap',
    [BetType.SIXTH_PERIOD_SPREAD]: 'handicap',
    [BetType.SEVENTH_PERIOD_SPREAD]: 'handicap',
    [BetType.EIGHTH_PERIOD_SPREAD]: 'handicap',
    [BetType.NINTH_PERIOD_SPREAD]: 'handicap',

    [BetType.FIRST_PERIOD_WINNER2]: 'winner',
    [BetType.SECOND_PERIOD_WINNER2]: 'winner',
    [BetType.THIRD_PERIOD_WINNER2]: 'winner',
    [BetType.FOURTH_PERIOD_WINNER2]: 'winner',
    [BetType.FIFTH_PERIOD_WINNER2]: 'winner',
    [BetType.SIXTH_PERIOD_WINNER2]: 'winner',
    [BetType.SEVENTH_PERIOD_WINNER2]: 'winner',
    [BetType.EIGHTH_PERIOD_WINNER2]: 'winner',
    [BetType.NINTH_PERIOD_WINNER2]: 'winner',
    [BetType.FIRST_PERIOD_TOTAL2]: 'total',
    [BetType.SECOND_PERIOD_TOTAL2]: 'total',
    [BetType.THIRD_PERIOD_TOTAL2]: 'total',
    [BetType.FOURTH_PERIOD_TOTAL2]: 'total',
    [BetType.FIFTH_PERIOD_TOTAL2]: 'total',
    [BetType.SIXTH_PERIOD_TOTAL2]: 'total',
    [BetType.SEVENTH_PERIOD_TOTAL2]: 'total',
    [BetType.EIGHTH_PERIOD_TOTAL2]: 'total',
    [BetType.NINTH_PERIOD_TOTAL2]: 'total',
    [BetType.FIRST_PERIOD_SPREAD2]: 'handicap',
    [BetType.SECOND_PERIOD_SPREAD2]: 'handicap',
    [BetType.THIRD_PERIOD_SPREAD2]: 'handicap',
    [BetType.FOURTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.FIFTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.SIXTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.SEVENTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.EIGHTH_PERIOD_SPREAD2]: 'handicap',
    [BetType.NINTH_PERIOD_SPREAD2]: 'handicap',

    [BetType.FIRST_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 1st',
    [BetType.SECOND_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 2nd',
    [BetType.THIRD_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 3rd',
    [BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 4th',
    [BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 5th',
    [BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 6th',
    [BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 7th',
    [BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 8th',
    [BetType.NINTH_PERIOD_TOTAL_ODD_EVEN]: 'Total odd/even 9th',
    [BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 1st',
    [BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 2nd',
    [BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 3rd',
    [BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 4th',
    [BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 5th',
    [BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 6th',
    [BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 7th',
    [BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 8th',
    [BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN]: 'Total odd/even 9th',

    [BetType.FIRST_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 1st',
    [BetType.SECOND_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 2nd',
    [BetType.THIRD_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 3rd',
    [BetType.FOURTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 4th',
    [BetType.FIFTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 5th',
    [BetType.SIXTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 6th',
    [BetType.SEVENTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 7th',
    [BetType.EIGHTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 8th',
    [BetType.NINTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'Both teams to score 9th',

    [BetType.FIRST_PERIOD_HOME_TEAM]: 'Total home team 1st',
    [BetType.FIRST_PERIOD_AWAY_TEAM]: 'Total away team 2ns',
    [BetType.SECOND_PERIOD_HOME_TEAM]: 'Total home team 1st',
    [BetType.SECOND_PERIOD_AWAY_TEAM]: 'Total away team 2nd',
};

export const BetTypeMap: Record<BetType, string> = {
    [BetType.WINNER]: 'winner',
    [BetType.SPREAD]: 'spread',
    [BetType.TOTAL]: 'total',
    [BetType.DOUBLE_CHANCE]: 'doubleChance',
    [BetType.WINNER_TOTAL]: 'winnerTotal',
    [BetType.TOTAL_ODD_EVEN]: 'totalOddEven',
    [BetType.HALFTIME_FULLTIME]: 'halftimeFulltime',
    [BetType.BOTH_TEAMS_TO_SCORE]: 'bothTeamsToScore',
    [BetType.GOALS]: 'goals',
    [BetType.HALFTIME_FULLTIME_GOALS]: 'halftimeFulltimeGoals',
    [BetType.WINNER2]: 'winner2',
    [BetType.WINNER3]: 'winner3',
    [BetType.SPREAD2]: 'handicap2',
    [BetType.TOTAL2]: 'total2',
    [BetType.FIRST_PERIOD_DOUBLE_CHANCE]: 'firstPeriodDoubleChance',
    [BetType.SECOND_PERIOD_DOUBLE_CHANCE]: 'secondPeriodDoubleChance',
    [BetType.TOTAL_HOME_TEAM]: 'totalHomeTeam',
    [BetType.TOTAL_AWAY_TEAM]: 'totalAwayTeam',
    [BetType.PLAYER_PROPS_HOMERUNS]: 'homeruns',
    [BetType.PLAYER_PROPS_STRIKEOUTS]: 'strikeouts',
    [BetType.PLAYER_PROPS_PASSING_YARDS]: 'passingYards',
    [BetType.PLAYER_PROPS_PASSING_TOUCHDOWNS]: 'passingTouchdowns',
    [BetType.PLAYER_PROPS_RUSHING_YARDS]: 'rushingYards',
    [BetType.PLAYER_PROPS_RECEIVING_YARDS]: 'receivingYards',
    [BetType.PLAYER_PROPS_TOUCHDOWNS]: 'touchdowns',
    [BetType.PLAYER_PROPS_FIELD_GOALS_MADE]: 'fieldGoalsMade',
    [BetType.PLAYER_PROPS_PITCHER_HITS_ALLOWED]: 'pitcherHitsAllowed',
    [BetType.PLAYER_PROPS_POINTS]: 'points',
    [BetType.PLAYER_PROPS_SHOTS]: 'shots',
    [BetType.PLAYER_PROPS_GOALS]: 'goals',
    [BetType.PLAYER_PROPS_HITS_RECORDED]: 'hitsRecorded',
    [BetType.PLAYER_PROPS_REBOUNDS]: 'rebounds',
    [BetType.PLAYER_PROPS_ASSISTS]: 'assists',
    [BetType.PLAYER_PROPS_DOUBLE_DOUBLE]: 'doubleDouble',
    [BetType.PLAYER_PROPS_TRIPLE_DOUBLE]: 'tripleDouble',
    [BetType.PLAYER_PROPS_RECEPTIONS]: 'receptions',
    [BetType.PLAYER_PROPS_FIRST_TOUCHDOWN]: 'firstTouchdown',
    [BetType.PLAYER_PROPS_LAST_TOUCHDOWN]: 'lastTouchdown',
    [BetType.PLAYER_PROPS_3PTS_MADE]: 'threePointsMade',

    [BetType.FIRST_PERIOD_WINNER]: 'firstPeriodWinner',
    [BetType.SECOND_PERIOD_WINNER]: 'secondPeriodWinner',
    [BetType.THIRD_PERIOD_WINNER]: 'thirdPeriodWinner',
    [BetType.FOURTH_PERIOD_WINNER]: 'fourthPeriodWinner',
    [BetType.FIFTH_PERIOD_WINNER]: 'fifthPeriodWinner',
    [BetType.SIXTH_PERIOD_WINNER]: 'sixthPeriodWinner',
    [BetType.SEVENTH_PERIOD_WINNER]: 'seventhPeriodWinner',
    [BetType.EIGHTH_PERIOD_WINNER]: 'eightPeriodWinner',
    [BetType.NINTH_PERIOD_WINNER]: 'ninthPeriodWinner',
    [BetType.FIRST_PERIOD_TOTAL]: 'firstPeriodTotal',
    [BetType.SECOND_PERIOD_TOTAL]: 'secondPeriodTotal',
    [BetType.THIRD_PERIOD_TOTAL]: 'thirdPeriodTotal',
    [BetType.FOURTH_PERIOD_TOTAL]: 'fourthPeriodTotal',
    [BetType.FIFTH_PERIOD_TOTAL]: 'fifthPeriodTotal',
    [BetType.SIXTH_PERIOD_TOTAL]: 'sixthPeriodTotal',
    [BetType.SEVENTH_PERIOD_TOTAL]: 'seventhPeriodTotal',
    [BetType.EIGHTH_PERIOD_TOTAL]: 'eightPeriodTotal',
    [BetType.NINTH_PERIOD_TOTAL]: 'ninthPeriodTotal',
    [BetType.FIRST_PERIOD_SPREAD]: 'firstPeriodSpread',
    [BetType.SECOND_PERIOD_SPREAD]: 'secondPeriodSpread',
    [BetType.THIRD_PERIOD_SPREAD]: 'thirdPeriodSpread',
    [BetType.FOURTH_PERIOD_SPREAD]: 'fourthPeriodSpread',
    [BetType.FIFTH_PERIOD_SPREAD]: 'fifthPeriodSpread',
    [BetType.SIXTH_PERIOD_SPREAD]: 'sixthPeriodSpread',
    [BetType.SEVENTH_PERIOD_SPREAD]: 'seventhPeriodSpread',
    [BetType.EIGHTH_PERIOD_SPREAD]: 'eightPeriodSpread',
    [BetType.NINTH_PERIOD_SPREAD]: 'ninthPeriodSpread',

    [BetType.FIRST_PERIOD_WINNER2]: 'firstPeriodWinner2',
    [BetType.SECOND_PERIOD_WINNER2]: 'secondPeriodWinner2',
    [BetType.THIRD_PERIOD_WINNER2]: 'thirdPeriodWinner2',
    [BetType.FOURTH_PERIOD_WINNER2]: 'fourthPeriodWinner2',
    [BetType.FIFTH_PERIOD_WINNER2]: 'fifthPeriodWinner2',
    [BetType.SIXTH_PERIOD_WINNER2]: 'sixthPeriodWinner2',
    [BetType.SEVENTH_PERIOD_WINNER2]: 'seventhPeriodWinner2',
    [BetType.EIGHTH_PERIOD_WINNER2]: 'eightPeriodWinner2',
    [BetType.NINTH_PERIOD_WINNER2]: 'ninthPeriodWinner2',
    [BetType.FIRST_PERIOD_TOTAL2]: 'firstPeriodTotal2',
    [BetType.SECOND_PERIOD_TOTAL2]: 'secondPeriodTotal2',
    [BetType.THIRD_PERIOD_TOTAL2]: 'thirdPeriodTotal2',
    [BetType.FOURTH_PERIOD_TOTAL2]: 'fourthPeriodTotal2',
    [BetType.FIFTH_PERIOD_TOTAL2]: 'fifthPeriodTotal2',
    [BetType.SIXTH_PERIOD_TOTAL2]: 'sixthPeriodTotal2',
    [BetType.SEVENTH_PERIOD_TOTAL2]: 'seventhPeriodTotal2',
    [BetType.EIGHTH_PERIOD_TOTAL2]: 'eightPeriodTotal2',
    [BetType.NINTH_PERIOD_TOTAL2]: 'ninthPeriodTotal2',
    [BetType.FIRST_PERIOD_SPREAD2]: 'firstPeriodSpread2',
    [BetType.SECOND_PERIOD_SPREAD2]: 'secondPeriodSpread2',
    [BetType.THIRD_PERIOD_SPREAD2]: 'thirdPeriodSpread2',
    [BetType.FOURTH_PERIOD_SPREAD2]: 'fourthPeriodSpread2',
    [BetType.FIFTH_PERIOD_SPREAD2]: 'fifthPeriodSpread2',
    [BetType.SIXTH_PERIOD_SPREAD2]: 'sixthPeriodSpread2',
    [BetType.SEVENTH_PERIOD_SPREAD2]: 'seventhPeriodSpread2',
    [BetType.EIGHTH_PERIOD_SPREAD2]: 'eightPeriodSpread2',
    [BetType.NINTH_PERIOD_SPREAD2]: 'ninthPeriodSpread2',

    [BetType.FIRST_PERIOD_TOTAL_ODD_EVEN]: 'firstPeriodTotalOddEven',
    [BetType.SECOND_PERIOD_TOTAL_ODD_EVEN]: 'secondPeriodTotalOddEven',
    [BetType.THIRD_PERIOD_TOTAL_ODD_EVEN]: 'thirdPeriodTotalOddEven',
    [BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN]: 'fourthPeriodTotalOddEven',
    [BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN]: 'fifthPeriodTotalOddEven',
    [BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN]: 'sixthPeriodTotalOddEven',
    [BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN]: 'seventhPeriodTotalOddEven',
    [BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN]: 'eightPeriodTotalOddEven',
    [BetType.NINTH_PERIOD_TOTAL_ODD_EVEN]: 'ninthPeriodTotalOddEven',
    [BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN]: 'firstPeriodTotal2OddEven',
    [BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN]: 'secondPeriodTotal2OddEven',
    [BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN]: 'thirdPeriodTotal2OddEven',
    [BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN]: 'fourthPeriodTotal2OddEven',
    [BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN]: 'fifthPeriodTotal2OddEven',
    [BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN]: 'sixthPeriodTotal2OddEven',
    [BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN]: 'seventhPeriodTotal2OddEven',
    [BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN]: 'eightPeriodTotal2OddEven',
    [BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN]: 'ninthPeriodTotal2OddEven',

    [BetType.FIRST_PERIOD_BOTH_TEAMS_TO_SCORE]: 'firstPeriodBothTeamsToScore',
    [BetType.SECOND_PERIOD_BOTH_TEAMS_TO_SCORE]: 'secondPeriodBothTeamsToScore',
    [BetType.THIRD_PERIOD_BOTH_TEAMS_TO_SCORE]: 'thirdPeriodBothTeamsToScore',
    [BetType.FOURTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'fourthPeriodBothTeamsToScore',
    [BetType.FIFTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'fifthPeriodBothTeamsToScore',
    [BetType.SIXTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'sixthPeriodBothTeamsToScore',
    [BetType.SEVENTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'seventhPeriodBothTeamsToScore',
    [BetType.EIGHTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'eightPeriodBothTeamsToScore',
    [BetType.NINTH_PERIOD_BOTH_TEAMS_TO_SCORE]: 'ninthPeriodBothTeamsToScore',

    [BetType.FIRST_PERIOD_HOME_TEAM]: 'firstPeriodTotalHomeTeam',
    [BetType.FIRST_PERIOD_AWAY_TEAM]: 'firstPeriodTotalAwayTeam',
    [BetType.SECOND_PERIOD_HOME_TEAM]: 'secondPeriodTotalHomeTeam',
    [BetType.SECOND_PERIOD_AWAY_TEAM]: 'secondPeriodTotalAwayTeam',
};

export const SCORING_MAP: SportsMap = {
    1: 'points',
    2: 'points',
    3: 'points',
    4: 'points',
    5: 'points',
    6: 'goals',
    7: 'rounds',
    8: 'points',
    10: 'goals',
    11: 'goals',
    12: 'goals',
    13: 'goals',
    14: 'goals',
    15: 'goals',
    16: 'goals',
    17: 'goals',
    18: 'goals',
    19: 'goals',
    445: '',
    497: '',
    153: 'sets',
    156: 'sets',
    9977: 'round',
    9983: 'round',
    10138: 'round',
    20: 'points',
    399: 'points',
    9196: 'rounds',
    57: 'goals',
    61: 'goals',
    45: 'goals',
    33: 'goals',
    296: 'goals',
    21: 'points',
    50: 'goals',
    100021: '',
    100121: '',
    9806: 'goals',
    9821: 'goals',
    288: 'goals',
    42: 'goals',
    10216: 'goals',
    76: 'goals',
    73: 'goals',
    409: 'points',
    536: 'goals',
    268: 'goals',
    10199: 'goals',
    10595: 'rounds',
    132: 'goals',
    134: 'goals',
    138: 'goals',
    141: 'goals',
    209: 'goals',
};

export const MATCH_RESOLVE_MAP: SportsMap = {
    1: 'overtime',
    2: 'overtime',
    3: 'overtime',
    4: 'overtime',
    5: 'overtime',
    6: 'overtime',
    7: '',
    8: 'overtime',
    10: 'regular',
    11: 'regular',
    12: 'regular',
    13: 'regular',
    14: 'regular',
    15: 'regular',
    16: 'regular',
    17: 'regular',
    18: 'regular',
    19: 'regular',
    445: '',
    497: '',
    153: '',
    156: '',
    9977: '',
    9983: '',
    10138: '',
    20: '',
    399: 'overtime',
    9196: '',
    57: 'regular',
    61: 'regular',
    45: 'regular',
    33: 'regular',
    296: 'regular',
    21: '',
    50: 'regular',
    100021: '',
    100121: '',
    9806: 'regular',
    9821: 'regular',
    288: 'regular',
    42: 'regular',
    10216: 'regular',
    76: 'regular',
    73: 'regular',
    409: 'overtime',
    536: 'regular',
    268: 'regular',
    10199: 'regular',
    10595: '',
    132: 'regular',
    134: 'regular',
    138: 'regular',
    141: 'regular',
    209: 'regular',
};

export const SPORT_PERIODS_MAP: SportsMap = {
    1: 'quarter',
    2: 'quarter',
    3: 'inning',
    4: 'quarter',
    5: 'half',
    6: 'period',
    7: 'round',
    8: 'quarter',
    10: 'half',
    11: 'half',
    12: 'half',
    13: 'half',
    14: 'half',
    15: 'half',
    16: 'half',
    17: 'half',
    18: 'half',
    19: 'half',
    153: 'set',
    156: 'set',
    9977: 'round',
    9983: 'round',
    10138: 'round',
    20: 'inning',
    399: 'quarter',
    9196: 'round',
    57: 'half',
    61: 'half',
    45: 'half',
    33: 'period',
    296: 'half',
    21: 'inning',
    50: 'half',
    100021: '',
    100121: '',
    9806: 'half',
    9821: 'half',
    288: 'half',
    42: 'half',
    10216: 'half',
    76: 'half',
    73: 'half',
    409: 'quarter',
    536: 'half',
    268: 'half',
    10199: 'half',
    10595: 'round',
    132: 'half',
    134: 'half',
    138: 'half',
    141: 'half',
    209: 'half',
};

export const LIVE_SUPPORTED_LEAGUES = [4, 11, 12, 15, 536];

export const BET_TYPES_BY_SPORT: Record<SportFilterEnum, BetType[]> = {
    [SportFilterEnum.Live]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Favourites]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.All]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Soccer]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Football]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Basketball]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Baseball]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Hockey]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.MMA]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Tennis]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.eSports]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Cricket]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
    [SportFilterEnum.Golf]: [BetType.WINNER, BetType.SPREAD, BetType.TOTAL],
};

export const BET_TYPE_GROUPS_BY_SPORT: Record<MarketSport, Partial<Record<BetTypeGroup, BetType[]>>> = {
    Soccer: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
        [BetTypeGroup.HANDICAP]: [
            BetType.SPREAD,
            BetType.SPREAD2,
            BetType.FIRST_PERIOD_SPREAD,
            BetType.SECOND_PERIOD_SPREAD,
            BetType.THIRD_PERIOD_SPREAD,
            BetType.FOURTH_PERIOD_SPREAD,
            BetType.FIFTH_PERIOD_SPREAD,
            BetType.SIXTH_PERIOD_SPREAD,
            BetType.SEVENTH_PERIOD_SPREAD,
            BetType.EIGHTH_PERIOD_SPREAD,
            BetType.NINTH_PERIOD_SPREAD,
            BetType.FIRST_PERIOD_SPREAD2,
            BetType.SECOND_PERIOD_SPREAD2,
            BetType.THIRD_PERIOD_SPREAD2,
            BetType.FOURTH_PERIOD_SPREAD2,
            BetType.FIFTH_PERIOD_SPREAD2,
            BetType.SIXTH_PERIOD_SPREAD2,
            BetType.SEVENTH_PERIOD_SPREAD2,
            BetType.EIGHTH_PERIOD_SPREAD2,
            BetType.NINTH_PERIOD_SPREAD2,
        ],
    },
    Basketball: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
        [BetTypeGroup.HANDICAP]: [
            BetType.SPREAD,
            BetType.SPREAD2,
            BetType.FIRST_PERIOD_SPREAD,
            BetType.SECOND_PERIOD_SPREAD,
            BetType.THIRD_PERIOD_SPREAD,
            BetType.FOURTH_PERIOD_SPREAD,
            BetType.FIFTH_PERIOD_SPREAD,
            BetType.SIXTH_PERIOD_SPREAD,
            BetType.SEVENTH_PERIOD_SPREAD,
            BetType.EIGHTH_PERIOD_SPREAD,
            BetType.NINTH_PERIOD_SPREAD,
            BetType.FIRST_PERIOD_SPREAD2,
            BetType.SECOND_PERIOD_SPREAD2,
            BetType.THIRD_PERIOD_SPREAD2,
            BetType.FOURTH_PERIOD_SPREAD2,
            BetType.FIFTH_PERIOD_SPREAD2,
            BetType.SIXTH_PERIOD_SPREAD2,
            BetType.SEVENTH_PERIOD_SPREAD2,
            BetType.EIGHTH_PERIOD_SPREAD2,
            BetType.NINTH_PERIOD_SPREAD2,
        ],
    },
    MMA: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Tennis: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Football: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Baseball: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Hockey: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Esports: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Cricket: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
    Golf: {
        [BetTypeGroup.TOTALS]: [
            BetType.TOTAL,
            BetType.TOTAL2,
            BetType.FIRST_PERIOD_TOTAL,
            BetType.SECOND_PERIOD_TOTAL,
            BetType.THIRD_PERIOD_TOTAL,
            BetType.FOURTH_PERIOD_TOTAL,
            BetType.FIFTH_PERIOD_TOTAL,
            BetType.SIXTH_PERIOD_TOTAL,
            BetType.SEVENTH_PERIOD_TOTAL,
            BetType.EIGHTH_PERIOD_TOTAL,
            BetType.NINTH_PERIOD_TOTAL,
            BetType.FIRST_PERIOD_TOTAL2,
            BetType.SECOND_PERIOD_TOTAL2,
            BetType.THIRD_PERIOD_TOTAL2,
            BetType.FOURTH_PERIOD_TOTAL2,
            BetType.FIFTH_PERIOD_TOTAL2,
            BetType.SIXTH_PERIOD_TOTAL2,
            BetType.SEVENTH_PERIOD_TOTAL2,
            BetType.EIGHTH_PERIOD_TOTAL2,
            BetType.NINTH_PERIOD_TOTAL2,
            BetType.FIRST_PERIOD_TOTAL_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL_ODD_EVEN,
            BetType.FIRST_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SECOND_PERIOD_TOTAL2_ODD_EVEN,
            BetType.THIRD_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FOURTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.FIFTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SIXTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.SEVENTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.EIGHTH_PERIOD_TOTAL2_ODD_EVEN,
            BetType.NINTH_PERIOD_TOTAL2_ODD_EVEN,
        ],
    },
};

export const SPORT_ID_MAP_ENETPULSE: Record<number, number> = {
    18: 320, // Hockey Norway
    24: 6, // NHL
    33: 33, // Hockey World Championship
    16: 42, // Champions League
    45: 45, // Copa Libertadores
    11: 47, // EPL
    50: 50, // EURO Qualification
    12: 53, // France League 1
    13: 54, // Bundesliga
    15: 55, // Seria A
    57: 57, // Netherlands League 1
    61: 61, // Portugal League 1
    17: 73, // Europa League
    76: 76, // World Cup Woman
    14: 87, // La Liga
    153: 153, // Tennis GS
    156: 156, // Tennis Masters 1000
    132: 132, // FA Cup
    134: 134, // Coupe de France
    138: 138, // Copa del Rey
    141: 141, // Coppa Italia
    209: 209, // DFB Pokal
    268: 268, // Brazil Football League
    288: 288, // EURO U21
    296: 296, // FIFA WC U20
    310: 310, // Hockey Czech
    319: 319, // Hockey Finland
    322: 322, // Hockey Germany
    327: 327, // Hockey Switzerland
    399: 399, // EuroLeague
    409: 409, // FIBA World Cup
    445: 445, // F1
    497: 497, // Moto GP
    536: 536, // Saudi Arabia Football League
    9196: 9196, // Boxing
    9806: 9806, // UEFA League of Nations
    9821: 9821, // CONCACAF League of Nations
    9977: 9977, // CsGo
    9983: 9983, // Dota
    10138: 10138, // LOL
    10199: 10199, // World Cup Qualifications CONMBOL
    10216: 10216, // Europa Conference League
    10595: 10595, // Non-Title Boxing
};
