import { TeamAbbreviationsMap } from 'types/markets';

export const TEAM_ABBREVIATIONS_MAP: TeamAbbreviationsMap = {
    'bayer leverkusen': 'B04',
    'bayern munich': 'FCB',
    'borussia dortmund': 'BVB',
    "borussia m'gladbach": 'BMG',
    'fc cologne': 'KOE',
    'vfl bochum': 'BOC',
    'fc augsburg': 'FCA',
    'tsg hoffenheim': 'TSG',
    'rb leipzig': 'RBL',
    'hertha berlin': 'BSC',
    'vfb stuttgart': 'VFB',
    mainz: 'M05',
    'vfl wolfsburg': 'WOB',
    'werder bremen': 'SVW',
    'schalke 04': 'S04',
    'fc union berlin': 'FCU',
    'sc freiburg': 'SCF',
    'eintracht frankfurt': 'SGE',
    'manchester city': 'MCI',
    fulham: 'FUL',
    wolves: 'WOL',
    'brighton & hove albion': 'BHA',
    'nottingham forest': 'NFO',
    'brentford fc': 'BRE',
    'leeds united': 'LEE',
    bournemouth: 'BOU',
    everton: 'EVE',
    'leicester city': 'LEI',
    chelsea: 'CHE',
    'arsenal fc': 'ARS',
    'aston villa': 'AVL',
    'manchester united': 'MUN',
    'west ham united': 'WHU',
    'crystal palace': 'CRY',
    southampton: 'SOU',
    'newcastle united': 'NEW',
    'tottenham hotspur': 'TOT',
    liverpool: 'LIV',
    'real madrid': 'RMA',
    'rayo vallecano': 'RAY',
    sevilla: 'SEV',
    'real betis': 'BET',
    mallorca: 'MLL',
    villarreal: 'VIL',
    valencia: 'VAL',
    osasuna: 'OSA',
    'real sociedad': 'RSO',
    espanyol: 'ESP',
    'atletico madrid': 'ATM',
    almería: 'ALM',
    barcelona: 'BAR',
    'celta vigo': 'CEL',
    elche: 'ELC',
    'real valladolid': 'VLL',
    cádiz: 'CAD',
    getafe: 'GET',
    'athletic bilbao': 'ATH',
    girona: 'GIR',
    'aj auxerre': 'AUX',
    troyes: 'TRO',
    'ac ajaccio': 'ACA',
    strasbourg: 'STR',
    angers: 'ANG',
    lens: 'LEN',
    lorient: 'LOR',
    'paris saint-germain': 'PSG',
    nice: 'NCE',
    brest: 'B29',
    'stade de reims': 'REI',
    nantes: 'NAN',
    'clermont foot': 'CLE',
    montpellier: 'MPL',
    toulouse: 'TOU',
    'as monaco': 'AMO',
    lille: 'LOSC',
    marseille: 'OM',
    lyon: 'LYO',
    'stade rennes': 'REN',
    'atlanta united fc': 'ATL',
    'austin fc': 'ATX',
    'cf montréal': 'MTL',
    'charlotte fc': 'CLT',
    'chicago fire': 'CHI',
    'colorado rapids': 'COL',
    'columbus crew': 'CLB',
    'dc united': 'DC',
    'fc cincinnati': 'CIN',
    'fc dallas': 'DAL',
    'houston dynamo': 'HOU',
    'inter miami cf': 'MIA',
    'los angeles fc': 'LAFC',
    'los angeles galaxy': 'LA',
    'minnesota united fc': 'MIN',
    'nashville sc': 'NSH',
    'new england revolution': 'NE',
    'new york city fc': 'NYC',
    'new york red bulls': 'RBNY',
    'orlando city fc': 'ORL',
    'philadelphia union': 'PHI',
    'portland timbers': 'PORT',
    'real salt lake': 'RSL',
    'san jose earthquakes': 'SJ',
    'seattle sounders': 'SEA',
    'sporting kansas city': 'SKC',
    'toronto fc': 'TOR',
    'vancouver whitecaps fc': 'VAN',
    udinese: 'UDI',
    lecce: 'LEC',
    empoli: 'EMP',
    sassuolo: 'SAS',
    salernitana: 'SAL',
    cremonese: 'CRE',
    atalanta: 'ATL',
    napoli: 'NAP',
    'ac milan': 'ACM',
    spezia: 'SPZ',
    bologna: 'BOL',
    torino: 'TOR',
    monza: 'MON',
    'hellas verona': 'HEL',
    sampdoria: 'SAM',
    fiorentina: 'FIO',
    'as roma': 'ROM',
    lazio: 'LAZ',
    juventus: 'JUV',
    'inter milan': 'INT',
    'club brugge': 'BRU',
    'fc porto': 'POR',
    'sporting cp': 'Sli',
    internazionale: 'INT',
    'viktoria plzen': 'VPL',
    rangers: 'RFC',
    'ajax amsterdam': 'AJA',
    celtic: 'CEL',
    'shakhtar donetsk': 'SHK',
    'dinamo zagreb': 'DZA',
    'fc salzburg': 'RBS',
    'fc copenhagen': 'COP',
    'maccabi haifa': 'MAC',
    benfica: 'SLB',
    'arizona cardinals': 'ARI',
    'atlanta falcons': 'ATL',
    'baltimore ravens': 'BAL',
    'buffalo bills': 'BUF',
    'carolina panthers': 'CAR',
    'chicago bears': 'CHI',
    'cincinnati bengals': 'CIN',
    'cleveland browns': 'CLE',
    'dallas cowboys': 'DAL',
    'denver broncos': 'DEN',
    'detroit lions': 'DET',
    'green bay packers': 'GB',
    'houston texans': 'HOU',
    'indianapolis colts': 'IND',
    'jacksonville jaguars': 'JAX',
    'kansas city chiefs': 'KC',
    'las vegas raider': 'LV',
    'los angeles chargers': 'LAC',
    'los angeles rams': 'LAR',
    'miami dolphins': 'MIA',
    'minnesota vikings': 'MIN',
    'new england patriots': 'NE',
    'new orleans saints': 'NO',
    'new york giants': 'NYG',
    'new york jets': 'NYJ',
    'philadelphia eagles': 'PHI',
    'pittsburgh steelers': 'PIT',
    'san francisco 49ers': 'SF',
    'seattle seahawks': 'SEA',
    'tampa bay buccaneers': 'TB',
    'tennessee titans': 'TEN',
    'washington commanders': 'WAS',
    'air force falcons': 'AFA',
    'akron zips': 'AKR',
    'alabama crimson tide': 'ALA',
    'appalachian state mountaineers': 'APP',
    'arizona state sun devils': '',
    'arizona wildcats': 'ARIZ',
    'arkansas razorbacks': 'ARK',
    'arkansas state red wolves': 'ARST',
    'army black knights': 'ARMY',
    'auburn tigers': 'AUB',
    'ball state cardinals': 'BALL',
    'baylor bears': 'BAY',
    'boise state broncos': 'BSU',
    'boston college eagles': 'BC',
    'bowling green falcons': 'BGSU',
    'buffalo bulls': 'BUFF',
    'byu cougars': 'BYU',
    'california golden bears': 'CAL',
    'central michigan chippewas': 'CMU',
    'charlotte 49ers': 'CHAR',
    'cincinnati bearcats': 'CIN',
    'clemson tigers': 'CLEM',
    'coastal carolina chanticleers': 'CCAR',
    'colorado buffaloes': 'COLO',
    'colorado state rams': 'CSU',
    'duke blue devils': 'DUKE',
    'east carolina pirates': 'ECU',
    'eastern michigan eagles': 'EMU',
    'florida atlantic owls': 'FAMU',
    'florida gators': 'FL',
    'florida international panthers': 'FLI',
    'florida state seminoles': 'FSU',
    'fresno state bulldogs': 'FRES',
    'georgia bulldogs': 'UGA',
    'georgia southern eagles': 'GASO',
    'georgia state panthers': 'GSU',
    'georgia tech yellow jackets': 'GT',
    'hawaii rainbow warriors': 'HAW',
    'houston cougars': 'HOU',
    'illinois fighting illini': 'ILL',
    'indiana hoosiers': 'IND',
    'iowa hawkeyes': 'IOWA',
    'iowa state cyclones': 'ISU',
    'james madison dukes': 'JMU',
    'kansas jayhawks': 'KU',
    'kansas state wildcats': 'KSU',
    'kent state golden flashes': 'KENT',
    'kentucky wildcats': 'UK',
    'liberty flames': 'LIB',
    'louisiana ragin cajuns': 'LOU',
    'louisiana tech bulldogs': 'LT',
    'louisville cardinals': 'LOU',
    'lsu tigers': 'LSU',
    'marshall thundering herd': 'MRSH',
    'maryland terrapins': 'UMD',
    'memphis tigers': 'MEM',
    'miami hurricanes': 'MIA',
    'miami redhawks': 'M-OH',
    'michigan state spartans': 'MSU',
    'michigan wolverines': 'MICH',
    'middle tennessee blue raiders': 'MTSU',
    'minnesota golden gophers': 'MIN',
    'mississippi state bulldogs': 'MSST',
    'missouri tigers': 'MIZ',
    'navy midshipmen': 'NAVY',
    'nebraska cornhuskers': 'NEB',
    'nevada wolf pack': 'NEV',
    'new mexico lobos': 'UNM',
    'new mexico state aggies': 'NMSU',
    'north carolina tar heels': 'UNC',
    'north texas mean green': 'UNT',
    'northern illinois huskies': 'NIU',
    'northwestern wildcats': 'NWST',
    'notre dame fighting irish': 'ND',
    'ohio bobcats': 'OHIO',
    'ohio state buckeyes': 'OSU',
    'oklahoma sooners': 'OKLA',
    'oklahoma state cowboys': 'OKST',
    'old dominion monarchs': 'ODU',
    'ole miss rebels': 'MISS',
    'oregon ducks': 'ORE',
    'oregon state beavers': 'ORST',
    'penn state nittany lions': 'PSU',
    'pittsburgh panthers': 'PITT',
    'purdue boilermakers': 'PUR',
    'rice owls': 'RICE',
    'rutgers scarlet knights': 'RUTG',
    'san diego state aztecs': 'SDSU',
    'san jose state spartans': 'SJSU',
    'smu mustangs': 'SMU',
    'south alabama jaguars': 'USA',
    'south carolina gamecocks': 'SCAR',
    'south florida bulls': 'USF',
    'southern miss golden eagles': 'USM',
    'stanford cardinal': 'STAN',
    'syracuse orange': 'SYR',
    'tcu horned frogs': 'TCU',
    'temple owls': 'TEM',
    'tennessee volunteers': 'TENN',
    'texas a&m aggies': 'TAMU',
    'texas longhorns': 'TEX',
    'texas state bobcats': 'TXST',
    'texas tech red raiders': 'TTU',
    'toledo rockets': 'TOL',
    'troy trojans': 'TROY',
    'tulane green waves': 'TULN',
    'tulsa golden hurricane': 'TLSA',
    'uab blazers': 'UAB',
    'ucf knights': 'UCF',
    'ucla bruins': 'UCLA',
    'uconn huskies': 'CONN',
    'ul monroe warhawks': 'ULM',
    'umass minutemen': 'UMASS',
    'unlv rebels': 'UNLV',
    'usc trojans': 'USC',
    'utah state aggies': 'USU',
    'utah utes': 'UTAH',
    'utep miners': 'UTEP',
    'utsa roadrunners': 'UTSA',
    'vanderbilt commodores': 'VAN',
    'virginia cavaliers': 'UVA',
    'virginia tech hokies': 'VT',
    'wake forest demon deacons': 'WAKE',
    'washington huskies': 'WASH',
    'washington state cougars': 'WSU',
    'west virginia mountaineers': 'WVU',
    'western kentucky hilltoppers': 'WKU',
    'western michigan broncos': 'WMU',
    'wisconsin badgers': 'WIS',
    'wyoming cowboys': 'WYO',
    'arizona diamondbacks': 'ARI',
    'atlanta braves': 'ATK',
    'baltimore orioles': 'BAL',
    'boston red sox': 'BOS',
    'chicago cubs': 'CHC',
    'chicago white sox': 'CHW',
    'cincinnati reds': 'CIN',
    'cleveland guardians': 'CLE',
    'colorado rockies': 'COL',
    'detroit tigers': 'DET',
    'houston astros': 'HOU',
    'kansas city royals': 'KC',
    'los angeles angels': 'LAA',
    'los angeles dodgers': 'LAD',
    'miami marlins': 'MIA',
    'milwaukee brewers': 'MIL',
    'minnesota twins': 'MIN',
    'new york mets': 'NYM',
    'new york yankees': 'NYY',
    'oakland athletics': 'OAK',
    'philadelphia phillies': 'PHI',
    'pittsburgh pirates': 'PIT',
    'san diego padres': 'SD',
    'san francisco giants': 'SF',
    'seattle mariners': 'SEA',
    'st. louis cardinals': 'STL',
    'tampa bay rays': 'TB',
    'texas rangers': 'TEX',
    'toronto blue jays': 'TOR',
    'washington nationals': 'WAS',
    'atlanta hawks': 'ATL',
    'boston celtics': 'BOS',
    'brooklyn nets': 'BKN',
    'charlotte hornets': 'CHA',
    'chicago bulls': 'CHU',
    'cleveland cavaliers': 'CLE',
    'dallas mavericks': 'DAL',
    'denver nuggets': 'DEN',
    'detroit pistons': 'DET',
    'golden state warriors': 'GSW',
    'houston rockets': 'HOU',
    'indiana pacers': 'IND',
    'la clippers': 'LAC',
    'los angeles lakers': 'LAL',
    'memphis grizzlies': 'MEM',
    'miami heat': 'MIA',
    'milwaukee bucks': 'MIL',
    'minnesota timberwolves': 'MIN',
    'new orleans pelicans': 'NOP',
    'new york knicks': 'NYK',
    'oklahoma city thunder': 'OKC',
    'orlando magic': 'ORL',
    'philadelphia 76ers': 'PHI',
    'phoenix suns': 'PHO',
    'portland trailblazers': 'POR',
    'sacramento kings': 'SAC',
    'san antonio spurs': 'SAS',
    'toronto raptors': 'TOR',
    'utah jazz': 'UTA',
    'washington wizards': 'WAS',
    'anaheim ducks': 'ANA',
    'arizona coyotes': 'ARI',
    'boston bruins': 'BOS',
    'buffalo sabres': 'BUF',
    'calgary flames': 'CGY',
    'carolina hurricanes': 'CAR',
    'chicago blackhawks': 'CHI',
    'colorado avalanche': 'COL',
    'columbus blue jackets': 'CBJ',
    'dallas stars': 'DAL',
    'detroit red wings': 'DET',
    'edmonton oilers': 'EDM',
    'florida panthers': 'FLO',
    'los angeles kings': 'LAK',
    'minnesota wild': 'MIN',
    'montreal canadiens': 'MTL',
    'nashville predators': 'NSH',
    'new jersey devils': 'NJD',
    'new york islanders': 'NYI',
    'new york rangers': 'NYR',
    'ottawa senators': 'OTW',
    'philadelphia flyers': 'PHI',
    'pittsburgh penguins': 'PIT',
    'san jose sharks': 'SJS',
    'seattle kraken': 'SEA',
    'st. louis blues': 'STL',
    'tampa bay lightning': 'TBL',
    'toronto maple leafs': 'TOR',
    'vancouver canucks': 'VAN',
    'vegas golden knights': 'VGK',
    'washington capitals': 'WAS',
    'winnipeg jets': 'WPG',
};
