import { BracketMatch, MarchMadTeam, ResultMatch } from 'types/marchMadness';

export const initialBracketsData: BracketMatch[] = [
    {
        id: 0,
        homeTeamId: 0,
        awayTeamId: 15,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 1,
        homeTeamId: 7,
        awayTeamId: 8,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 2,
        homeTeamId: 4,
        awayTeamId: 11,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 3,
        homeTeamId: 3,
        awayTeamId: 12,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 4,
        homeTeamId: 5,
        awayTeamId: 10,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 5,
        homeTeamId: 2,
        awayTeamId: 13,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 6,
        homeTeamId: 6,
        awayTeamId: 9,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 7,
        homeTeamId: 1,
        awayTeamId: 14,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 8,
        homeTeamId: 16,
        awayTeamId: 31,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 9,
        homeTeamId: 23,
        awayTeamId: 24,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 10,
        homeTeamId: 20,
        awayTeamId: 27,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 11,
        homeTeamId: 19,
        awayTeamId: 28,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 12,
        homeTeamId: 21,
        awayTeamId: 26,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 13,
        homeTeamId: 18,
        awayTeamId: 29,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 14,
        homeTeamId: 22,
        awayTeamId: 25,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 15,
        homeTeamId: 17,
        awayTeamId: 30,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 16,
        homeTeamId: 32,
        awayTeamId: 47,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 17,
        homeTeamId: 39,
        awayTeamId: 40,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 18,
        homeTeamId: 36,
        awayTeamId: 43,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 19,
        homeTeamId: 35,
        awayTeamId: 44,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 20,
        homeTeamId: 37,
        awayTeamId: 42,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 21,
        homeTeamId: 34,
        awayTeamId: 45,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 22,
        homeTeamId: 38,
        awayTeamId: 41,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 23,
        homeTeamId: 33,
        awayTeamId: 46,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 24,
        homeTeamId: 48,
        awayTeamId: 63,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 25,
        homeTeamId: 55,
        awayTeamId: 56,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 26,
        homeTeamId: 52,
        awayTeamId: 59,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 27,
        homeTeamId: 51,
        awayTeamId: 60,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 28,
        homeTeamId: 53,
        awayTeamId: 58,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 29,
        homeTeamId: 50,
        awayTeamId: 61,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 30,
        homeTeamId: 54,
        awayTeamId: 57,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 31,
        homeTeamId: 49,
        awayTeamId: 62,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 32,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 0,
        awayTeamParentMatchId: 1,
    },
    {
        id: 33,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 2,
        awayTeamParentMatchId: 3,
    },
    {
        id: 34,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 4,
        awayTeamParentMatchId: 5,
    },
    {
        id: 35,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 6,
        awayTeamParentMatchId: 7,
    },
    {
        id: 36,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 8,
        awayTeamParentMatchId: 9,
    },
    {
        id: 37,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 10,
        awayTeamParentMatchId: 11,
    },
    {
        id: 38,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 12,
        awayTeamParentMatchId: 13,
    },
    {
        id: 39,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 14,
        awayTeamParentMatchId: 15,
    },
    {
        id: 40,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 16,
        awayTeamParentMatchId: 17,
    },
    {
        id: 41,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 18,
        awayTeamParentMatchId: 19,
    },
    {
        id: 42,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 20,
        awayTeamParentMatchId: 21,
    },
    {
        id: 43,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 22,
        awayTeamParentMatchId: 23,
    },
    {
        id: 44,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 24,
        awayTeamParentMatchId: 25,
    },
    {
        id: 45,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 26,
        awayTeamParentMatchId: 27,
    },
    {
        id: 46,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 28,
        awayTeamParentMatchId: 29,
    },
    {
        id: 47,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 30,
        awayTeamParentMatchId: 31,
    },
    {
        id: 48,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 32,
        awayTeamParentMatchId: 33,
    },
    {
        id: 49,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 34,
        awayTeamParentMatchId: 35,
    },
    {
        id: 50,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 36,
        awayTeamParentMatchId: 37,
    },
    {
        id: 51,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 38,
        awayTeamParentMatchId: 39,
    },
    {
        id: 52,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 40,
        awayTeamParentMatchId: 41,
    },
    {
        id: 53,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 42,
        awayTeamParentMatchId: 43,
    },
    {
        id: 54,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 44,
        awayTeamParentMatchId: 45,
    },
    {
        id: 55,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 46,
        awayTeamParentMatchId: 47,
    },
    {
        id: 56,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 48,
        awayTeamParentMatchId: 49,
    },
    {
        id: 57,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 50,
        awayTeamParentMatchId: 51,
    },
    {
        id: 58,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 52,
        awayTeamParentMatchId: 53,
    },
    {
        id: 59,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 54,
        awayTeamParentMatchId: 55,
    },
    {
        id: 60,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 56,
        awayTeamParentMatchId: 57,
    },
    {
        id: 61,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 58,
        awayTeamParentMatchId: 59,
    },
    {
        id: 62,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 60,
        awayTeamParentMatchId: 61,
    },
];

// TODO: populate
export const teamsData: MarchMadTeam[] = [
    {
        id: 0,
        name: 'Purdue Boilermakers',
        displayName: 'Purdue',
        region: 'East',
        position: 1,
    },
    {
        id: 1,
        name: 'Baylor Bears',
        displayName: 'Baylor',
        region: 'East',
        position: 2,
    },
    {
        id: 2,
        name: 'Tennessee Volunteers',
        displayName: 'Tennessee',
        region: 'East',
        position: 3,
    },
    {
        id: 3,
        name: 'Gonzaga Bulldogs',
        displayName: 'Gonzaga',
        region: 'East',
        position: 4,
    },
    {
        id: 4,
        name: 'Uconn Huskies',
        displayName: 'Uconn',
        region: 'East',
        position: 5,
    },
    {
        id: 5,
        name: 'Duke Blue Devils',
        displayName: 'Duke',
        region: 'East',
        position: 6,
    },
    {
        id: 6,
        name: 'Providence Friars',
        displayName: 'Providence',
        region: 'East',
        position: 7,
    },
    {
        id: 7,
        name: 'Kentucky Wildcats',
        displayName: 'Kentucky',
        region: 'East',
        position: 8,
    },
    {
        id: 8,
        name: 'Pittsburgh Panthers',
        displayName: 'Pittsburgh',
        region: 'East',
        position: 9,
    },
    {
        id: 9,
        name: 'Auburn Tigers',
        displayName: 'Auburn',
        region: 'East',
        position: 10,
    },
    {
        id: 10,
        name: 'West Virginia Mountaineers',
        displayName: 'West Virginia',
        region: 'East',
        position: 11,
    },
    {
        id: 11,
        name: '',
        displayName: 'Wild Card',
        region: 'East',
        position: 12,
    },
    {
        id: 12,
        name: 'Iona Gaels',
        displayName: 'Iona',
        region: 'East',
        position: 13,
    },
    {
        id: 13,
        name: 'Hofstra Pride',
        displayName: 'Hofstra',
        region: 'East',
        position: 14,
    },
    {
        id: 14,
        name: 'Vermont Catamounts',
        displayName: 'Vermont',
        region: 'East',
        position: 15,
    },
    {
        id: 15,
        name: 'Howard Bison',
        displayName: 'Howard',
        region: 'East',
        position: 16,
    },
    {
        id: 16,
        name: '',
        displayName: '',
        region: 'West',
        position: 1,
    },
    {
        id: 17,
        name: '',
        displayName: '',
        region: 'West',
        position: 2,
    },
    {
        id: 18,
        name: '',
        displayName: '',
        region: 'West',
        position: 3,
    },
    {
        id: 19,
        name: '',
        displayName: '',
        region: 'West',
        position: 4,
    },
    {
        id: 20,
        name: '',
        displayName: '',
        region: 'West',
        position: 5,
    },
    {
        id: 21,
        name: '',
        displayName: '',
        region: 'West',
        position: 6,
    },
    {
        id: 22,
        name: '',
        displayName: '',
        region: 'West',
        position: 7,
    },
    {
        id: 23,
        name: '',
        displayName: '',
        region: 'West',
        position: 8,
    },
    {
        id: 24,
        name: '',
        displayName: '',
        region: 'West',
        position: 9,
    },
    {
        id: 25,
        name: '',
        displayName: '',
        region: 'West',
        position: 10,
    },
    {
        id: 26,
        name: '',
        displayName: 'Wild Card',
        region: 'West',
        position: 11,
    },
    {
        id: 27,
        name: '',
        displayName: '',
        region: 'West',
        position: 12,
    },
    {
        id: 28,
        name: '',
        displayName: '',
        region: 'West',
        position: 13,
    },
    {
        id: 29,
        name: '',
        displayName: '',
        region: 'West',
        position: 14,
    },
    {
        id: 30,
        name: '',
        displayName: '',
        region: 'West',
        position: 15,
    },
    {
        id: 31,
        name: '',
        displayName: '',
        region: 'West',
        position: 16,
    },
    {
        id: 32,
        name: '',
        displayName: '',
        region: 'South',
        position: 1,
    },
    {
        id: 33,
        name: '',
        displayName: '',
        region: 'South',
        position: 2,
    },
    {
        id: 34,
        name: '',
        displayName: '',
        region: 'South',
        position: 3,
    },
    {
        id: 35,
        name: '',
        displayName: '',
        region: 'South',
        position: 4,
    },
    {
        id: 36,
        name: '',
        displayName: '',
        region: 'South',
        position: 5,
    },
    {
        id: 37,
        name: '',
        displayName: '',
        region: 'South',
        position: 6,
    },
    {
        id: 38,
        name: '',
        displayName: '',
        region: 'South',
        position: 7,
    },
    {
        id: 39,
        name: '',
        displayName: '',
        region: 'South',
        position: 8,
    },
    {
        id: 40,
        name: '',
        displayName: '',
        region: 'South',
        position: 9,
    },
    {
        id: 41,
        name: '',
        displayName: '',
        region: 'South',
        position: 10,
    },
    {
        id: 42,
        name: '',
        displayName: '',
        region: 'South',
        position: 11,
    },
    {
        id: 43,
        name: '',
        displayName: '',
        region: 'South',
        position: 12,
    },
    {
        id: 44,
        name: '',
        displayName: '',
        region: 'South',
        position: 13,
    },
    {
        id: 45,
        name: '',
        displayName: '',
        region: 'South',
        position: 14,
    },
    {
        id: 46,
        name: '',
        displayName: '',
        region: 'South',
        position: 15,
    },
    {
        id: 47,
        name: '',
        displayName: 'Wild Card',
        region: 'South',
        position: 16,
    },
    {
        id: 48,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 1,
    },
    {
        id: 49,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 2,
    },
    {
        id: 50,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 3,
    },
    {
        id: 51,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 4,
    },
    {
        id: 52,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 5,
    },
    {
        id: 53,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 6,
    },
    {
        id: 54,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 7,
    },
    {
        id: 55,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 8,
    },
    {
        id: 56,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 9,
    },
    {
        id: 57,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 10,
    },
    {
        id: 58,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 11,
    },
    {
        id: 59,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 12,
    },
    {
        id: 60,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 13,
    },
    {
        id: 61,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 14,
    },
    {
        id: 62,
        name: '',
        displayName: '',
        region: 'Midwest',
        position: 15,
    },
    {
        id: 63,
        name: '',
        displayName: 'Wild Card',
        region: 'Midwest',
        position: 16,
    },
];

export const wildCardTeams: MarchMadTeam[] = [
    {
        id: 0,
        name: '',
        displayName: 'Oral Roberts',
        region: 'East',
        position: 1,
    },
    {
        id: 1,
        name: '',
        displayName: 'Southern Miss',
        region: 'East',
        position: 2,
    },
    {
        id: 2,
        name: '',
        displayName: 'USC',
        region: 'West',
        position: 3,
    },
    {
        id: 3,
        name: '',
        displayName: 'Wake Forest',
        region: 'West',
        position: 4,
    },
    {
        id: 4,
        name: '',
        displayName: 'Morehead St.',
        region: 'South',
        position: 5,
    },
    {
        id: 5,
        name: '',
        displayName: 'Alcorn St.',
        region: 'South',
        position: 6,
    },
    {
        id: 6,
        name: '',
        displayName: 'TAMU-CC',
        region: 'Midwest',
        position: 7,
    },
    {
        id: 7,
        name: '',
        displayName: 'Fairleigh Dickinson',
        region: 'Midwest',
        position: 8,
    },
];

// TODO: remove after integration with contract
export const userSampleBracketsData: BracketMatch[] = [
    {
        id: 0,
        homeTeamId: 0,
        awayTeamId: 15,
        isHomeTeamSelected: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 1,
        homeTeamId: 7,
        awayTeamId: 8,
        isHomeTeamSelected: true,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 2,
        homeTeamId: 4,
        awayTeamId: 11,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 3,
        homeTeamId: 3,
        awayTeamId: 12,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 4,
        homeTeamId: 5,
        awayTeamId: 10,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 5,
        homeTeamId: 2,
        awayTeamId: 13,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 6,
        homeTeamId: 6,
        awayTeamId: 9,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 7,
        homeTeamId: 1,
        awayTeamId: 14,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 8,
        homeTeamId: 16,
        awayTeamId: 31,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 9,
        homeTeamId: 23,
        awayTeamId: 24,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 10,
        homeTeamId: 20,
        awayTeamId: 27,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 11,
        homeTeamId: 19,
        awayTeamId: 28,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 12,
        homeTeamId: 21,
        awayTeamId: 26,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 13,
        homeTeamId: 18,
        awayTeamId: 29,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 14,
        homeTeamId: 22,
        awayTeamId: 25,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 15,
        homeTeamId: 17,
        awayTeamId: 30,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 16,
        homeTeamId: 32,
        awayTeamId: 47,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 17,
        homeTeamId: 39,
        awayTeamId: 40,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 18,
        homeTeamId: 36,
        awayTeamId: 43,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 19,
        homeTeamId: 35,
        awayTeamId: 44,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 20,
        homeTeamId: 37,
        awayTeamId: 42,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 21,
        homeTeamId: 34,
        awayTeamId: 45,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 22,
        homeTeamId: 38,
        awayTeamId: 41,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 23,
        homeTeamId: 33,
        awayTeamId: 46,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 24,
        homeTeamId: 48,
        awayTeamId: 63,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 25,
        homeTeamId: 55,
        awayTeamId: 56,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 26,
        homeTeamId: 52,
        awayTeamId: 59,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 27,
        homeTeamId: 51,
        awayTeamId: 60,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 28,
        homeTeamId: 53,
        awayTeamId: 58,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 29,
        homeTeamId: 50,
        awayTeamId: 61,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 30,
        homeTeamId: 54,
        awayTeamId: 57,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 31,
        homeTeamId: 49,
        awayTeamId: 62,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 32,
        homeTeamId: 15,
        awayTeamId: 7,
        isHomeTeamSelected: false,
        homeTeamParentMatchId: 0,
        awayTeamParentMatchId: 1,
    },
    {
        id: 33,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 2,
        awayTeamParentMatchId: 3,
    },
    {
        id: 34,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 4,
        awayTeamParentMatchId: 5,
    },
    {
        id: 35,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 6,
        awayTeamParentMatchId: 7,
    },
    {
        id: 36,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 8,
        awayTeamParentMatchId: 9,
    },
    {
        id: 37,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 10,
        awayTeamParentMatchId: 11,
    },
    {
        id: 38,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 12,
        awayTeamParentMatchId: 13,
    },
    {
        id: 39,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 14,
        awayTeamParentMatchId: 15,
    },
    {
        id: 40,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 16,
        awayTeamParentMatchId: 17,
    },
    {
        id: 41,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 18,
        awayTeamParentMatchId: 19,
    },
    {
        id: 42,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 20,
        awayTeamParentMatchId: 21,
    },
    {
        id: 43,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 22,
        awayTeamParentMatchId: 23,
    },
    {
        id: 44,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 24,
        awayTeamParentMatchId: 25,
    },
    {
        id: 45,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 26,
        awayTeamParentMatchId: 27,
    },
    {
        id: 46,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 28,
        awayTeamParentMatchId: 29,
    },
    {
        id: 47,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 30,
        awayTeamParentMatchId: 31,
    },
    {
        id: 48,
        homeTeamId: 7,
        awayTeamId: undefined,
        isHomeTeamSelected: true,
        homeTeamParentMatchId: 32,
        awayTeamParentMatchId: 33,
    },
    {
        id: 49,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 34,
        awayTeamParentMatchId: 35,
    },
    {
        id: 50,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 36,
        awayTeamParentMatchId: 37,
    },
    {
        id: 51,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 38,
        awayTeamParentMatchId: 39,
    },
    {
        id: 52,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 40,
        awayTeamParentMatchId: 41,
    },
    {
        id: 53,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 42,
        awayTeamParentMatchId: 43,
    },
    {
        id: 54,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 44,
        awayTeamParentMatchId: 45,
    },
    {
        id: 55,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 46,
        awayTeamParentMatchId: 47,
    },
    {
        id: 56,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 48,
        awayTeamParentMatchId: 49,
    },
    {
        id: 57,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 50,
        awayTeamParentMatchId: 51,
    },
    {
        id: 58,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 52,
        awayTeamParentMatchId: 53,
    },
    {
        id: 59,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 54,
        awayTeamParentMatchId: 55,
    },
    {
        id: 60,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 56,
        awayTeamParentMatchId: 57,
    },
    {
        id: 61,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 58,
        awayTeamParentMatchId: 59,
    },
    {
        id: 62,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamParentMatchId: 60,
        awayTeamParentMatchId: 61,
    },
];

// TODO: remove after integration with contract
export const resultSampleBracketsData: ResultMatch[] = [
    {
        id: 0,
        homeTeamId: 0,
        awayTeamId: 15,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 1,
        homeTeamId: 7,
        awayTeamId: 8,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 2,
        homeTeamId: 4,
        awayTeamId: 11,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 3,
        homeTeamId: 3,
        awayTeamId: 12,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 4,
        homeTeamId: 5,
        awayTeamId: 10,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 5,
        homeTeamId: 2,
        awayTeamId: 13,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 6,
        homeTeamId: 6,
        awayTeamId: 9,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 7,
        homeTeamId: 1,
        awayTeamId: 14,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 8,
        homeTeamId: 16,
        awayTeamId: 31,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 9,
        homeTeamId: 23,
        awayTeamId: 24,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 10,
        homeTeamId: 20,
        awayTeamId: 27,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 11,
        homeTeamId: 19,
        awayTeamId: 28,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 12,
        homeTeamId: 21,
        awayTeamId: 26,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 13,
        homeTeamId: 18,
        awayTeamId: 29,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 14,
        homeTeamId: 22,
        awayTeamId: 25,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 15,
        homeTeamId: 17,
        awayTeamId: 30,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 16,
        homeTeamId: 32,
        awayTeamId: 47,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 17,
        homeTeamId: 39,
        awayTeamId: 40,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 18,
        homeTeamId: 36,
        awayTeamId: 43,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 19,
        homeTeamId: 35,
        awayTeamId: 44,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 20,
        homeTeamId: 37,
        awayTeamId: 42,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 21,
        homeTeamId: 34,
        awayTeamId: 45,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 22,
        homeTeamId: 38,
        awayTeamId: 41,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 23,
        homeTeamId: 33,
        awayTeamId: 46,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 24,
        homeTeamId: 48,
        awayTeamId: 63,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 25,
        homeTeamId: 55,
        awayTeamId: 56,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 26,
        homeTeamId: 52,
        awayTeamId: 59,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 27,
        homeTeamId: 51,
        awayTeamId: 60,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 28,
        homeTeamId: 53,
        awayTeamId: 58,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 29,
        homeTeamId: 50,
        awayTeamId: 61,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 30,
        homeTeamId: 54,
        awayTeamId: 57,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 31,
        homeTeamId: 49,
        awayTeamId: 62,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 32,
        homeTeamId: 15,
        awayTeamId: 7,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 0,
        awayTeamParentMatchId: 1,
    },
    {
        id: 33,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 2,
        awayTeamParentMatchId: 3,
    },
    {
        id: 34,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 4,
        awayTeamParentMatchId: 5,
    },
    {
        id: 35,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 6,
        awayTeamParentMatchId: 7,
    },
    {
        id: 36,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 8,
        awayTeamParentMatchId: 9,
    },
    {
        id: 37,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 10,
        awayTeamParentMatchId: 11,
    },
    {
        id: 38,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 12,
        awayTeamParentMatchId: 13,
    },
    {
        id: 39,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 14,
        awayTeamParentMatchId: 15,
    },
    {
        id: 40,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 16,
        awayTeamParentMatchId: 17,
    },
    {
        id: 41,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 18,
        awayTeamParentMatchId: 19,
    },
    {
        id: 42,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 20,
        awayTeamParentMatchId: 21,
    },
    {
        id: 43,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 22,
        awayTeamParentMatchId: 23,
    },
    {
        id: 44,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 24,
        awayTeamParentMatchId: 25,
    },
    {
        id: 45,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 26,
        awayTeamParentMatchId: 27,
    },
    {
        id: 46,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 28,
        awayTeamParentMatchId: 29,
    },
    {
        id: 47,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 30,
        awayTeamParentMatchId: 31,
    },
    {
        id: 48,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 32,
        awayTeamParentMatchId: 33,
    },
    {
        id: 49,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 34,
        awayTeamParentMatchId: 35,
    },
    {
        id: 50,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 36,
        awayTeamParentMatchId: 37,
    },
    {
        id: 51,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 38,
        awayTeamParentMatchId: 39,
    },
    {
        id: 52,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 40,
        awayTeamParentMatchId: 41,
    },
    {
        id: 53,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 42,
        awayTeamParentMatchId: 43,
    },
    {
        id: 54,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 44,
        awayTeamParentMatchId: 45,
    },
    {
        id: 55,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 46,
        awayTeamParentMatchId: 47,
    },
    {
        id: 56,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 48,
        awayTeamParentMatchId: 49,
    },
    {
        id: 57,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 50,
        awayTeamParentMatchId: 51,
    },
    {
        id: 58,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 52,
        awayTeamParentMatchId: 53,
    },
    {
        id: 59,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 54,
        awayTeamParentMatchId: 55,
    },
    {
        id: 60,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 56,
        awayTeamParentMatchId: 57,
    },
    {
        id: 61,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 58,
        awayTeamParentMatchId: 59,
    },
    {
        id: 62,
        homeTeamId: undefined,
        awayTeamId: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: undefined,
        homeTeamParentMatchId: 60,
        awayTeamParentMatchId: 61,
    },
];
