import { MarchMadMatch, MarchMadTeam } from 'types/marchMadness';

export const initialMatchesData: MarchMadMatch[] = [
    {
        id: 0,
        homeTeamId: 0,
        awayTeamId: 15,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 1,
        homeTeamId: 7,
        awayTeamId: 8,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 2,
        homeTeamId: 4,
        awayTeamId: 11,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 3,
        homeTeamId: 3,
        awayTeamId: 12,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 4,
        homeTeamId: 5,
        awayTeamId: 10,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 5,
        homeTeamId: 2,
        awayTeamId: 13,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 6,
        homeTeamId: 6,
        awayTeamId: 9,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 7,
        homeTeamId: 1,
        awayTeamId: 14,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 8,
        homeTeamId: 16,
        awayTeamId: 31,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 9,
        homeTeamId: 23,
        awayTeamId: 24,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 10,
        homeTeamId: 20,
        awayTeamId: 27,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 11,
        homeTeamId: 19,
        awayTeamId: 28,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 12,
        homeTeamId: 21,
        awayTeamId: 26,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 13,
        homeTeamId: 18,
        awayTeamId: 29,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 14,
        homeTeamId: 22,
        awayTeamId: 25,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 15,
        homeTeamId: 17,
        awayTeamId: 30,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 16,
        homeTeamId: 32,
        awayTeamId: 47,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 17,
        homeTeamId: 39,
        awayTeamId: 40,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 18,
        homeTeamId: 36,
        awayTeamId: 43,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 19,
        homeTeamId: 35,
        awayTeamId: 44,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 20,
        homeTeamId: 37,
        awayTeamId: 42,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 21,
        homeTeamId: 34,
        awayTeamId: 45,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 22,
        homeTeamId: 38,
        awayTeamId: 41,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 23,
        homeTeamId: 33,
        awayTeamId: 46,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 24,
        homeTeamId: 48,
        awayTeamId: 63,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 25,
        homeTeamId: 55,
        awayTeamId: 56,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 26,
        homeTeamId: 52,
        awayTeamId: 59,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 27,
        homeTeamId: 51,
        awayTeamId: 60,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 28,
        homeTeamId: 53,
        awayTeamId: 58,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 29,
        homeTeamId: 50,
        awayTeamId: 61,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 30,
        homeTeamId: 54,
        awayTeamId: 57,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 31,
        homeTeamId: 49,
        awayTeamId: 62,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: undefined,
        awayTeamParentMatchId: undefined,
    },
    {
        id: 32,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 0,
        awayTeamParentMatchId: 1,
    },
    {
        id: 33,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 2,
        awayTeamParentMatchId: 3,
    },
    {
        id: 34,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 4,
        awayTeamParentMatchId: 5,
    },
    {
        id: 35,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 6,
        awayTeamParentMatchId: 7,
    },
    {
        id: 36,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 8,
        awayTeamParentMatchId: 9,
    },
    {
        id: 37,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 10,
        awayTeamParentMatchId: 11,
    },
    {
        id: 38,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 12,
        awayTeamParentMatchId: 13,
    },
    {
        id: 39,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 14,
        awayTeamParentMatchId: 15,
    },
    {
        id: 40,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 16,
        awayTeamParentMatchId: 17,
    },
    {
        id: 41,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 18,
        awayTeamParentMatchId: 19,
    },
    {
        id: 42,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 20,
        awayTeamParentMatchId: 21,
    },
    {
        id: 43,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 22,
        awayTeamParentMatchId: 23,
    },
    {
        id: 44,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 24,
        awayTeamParentMatchId: 25,
    },
    {
        id: 45,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 26,
        awayTeamParentMatchId: 27,
    },
    {
        id: 46,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 28,
        awayTeamParentMatchId: 29,
    },
    {
        id: 47,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 30,
        awayTeamParentMatchId: 31,
    },
    {
        id: 48,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 32,
        awayTeamParentMatchId: 33,
    },
    {
        id: 49,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 34,
        awayTeamParentMatchId: 35,
    },
    {
        id: 50,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 36,
        awayTeamParentMatchId: 37,
    },
    {
        id: 51,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 38,
        awayTeamParentMatchId: 39,
    },
    {
        id: 52,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 40,
        awayTeamParentMatchId: 41,
    },
    {
        id: 53,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 42,
        awayTeamParentMatchId: 43,
    },
    {
        id: 54,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 44,
        awayTeamParentMatchId: 45,
    },
    {
        id: 55,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 46,
        awayTeamParentMatchId: 47,
    },
    {
        id: 56,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 48,
        awayTeamParentMatchId: 49,
    },
    {
        id: 57,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 50,
        awayTeamParentMatchId: 51,
    },
    {
        id: 58,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 52,
        awayTeamParentMatchId: 53,
    },
    {
        id: 59,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 54,
        awayTeamParentMatchId: 55,
    },
    {
        id: 60,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 56,
        awayTeamParentMatchId: 57,
    },
    {
        id: 61,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 58,
        awayTeamParentMatchId: 59,
    },
    {
        id: 62,
        homeTeamId: undefined,
        awayTeamId: undefined,
        isHomeTeamSelected: undefined,
        homeTeamScore: 0,
        awayTeamScore: 0,
        isResolved: false,
        isHomeTeamWon: false,
        homeTeamParentMatchId: 60,
        awayTeamParentMatchId: 61,
    },
];

// TODO: populate
export const teamsData: MarchMadTeam[] = [
    {
        id: 0,
        name: 'Purdue Boilmakers',
        displayName: 'Purdue',
        logo: '',
        region: 'East',
        position: 1,
    },
    {
        id: 1,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 2,
    },
    {
        id: 2,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 3,
    },
    {
        id: 3,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 4,
    },
    {
        id: 4,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 5,
    },
    {
        id: 5,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 6,
    },
    {
        id: 6,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 7,
    },
    {
        id: 7,
        name: 'Kentucky Wildcats',
        displayName: 'Kentucky',
        logo: '',
        region: 'East',
        position: 8,
    },
    {
        id: 8,
        name: 'Pittsburgh Panthers',
        displayName: 'Pittsburgh',
        logo: '',
        region: 'East',
        position: 9,
    },
    {
        id: 9,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 10,
    },
    {
        id: 10,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 11,
    },
    {
        id: 11,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 12,
    },
    {
        id: 12,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 13,
    },
    {
        id: 13,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 14,
    },
    {
        id: 14,
        name: '',
        displayName: '',
        logo: '',
        region: 'East',
        position: 15,
    },
    {
        id: 15,
        name: 'Howard Bison',
        displayName: 'Howard',
        logo: '',
        region: 'East',
        position: 16,
    },
    {
        id: 16,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 1,
    },
    {
        id: 17,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 2,
    },
    {
        id: 18,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 3,
    },
    {
        id: 19,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 4,
    },
    {
        id: 20,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 5,
    },
    {
        id: 21,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 6,
    },
    {
        id: 22,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 7,
    },
    {
        id: 23,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 8,
    },
    {
        id: 24,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 9,
    },
    {
        id: 25,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 10,
    },
    {
        id: 26,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 11,
    },
    {
        id: 27,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 12,
    },
    {
        id: 28,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 13,
    },
    {
        id: 29,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 14,
    },
    {
        id: 30,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 15,
    },
    {
        id: 31,
        name: '',
        displayName: '',
        logo: '',
        region: 'West',
        position: 16,
    },
    {
        id: 32,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 1,
    },
    {
        id: 33,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 2,
    },
    {
        id: 34,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 3,
    },
    {
        id: 35,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 4,
    },
    {
        id: 36,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 5,
    },
    {
        id: 37,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 6,
    },
    {
        id: 38,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 7,
    },
    {
        id: 39,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 8,
    },
    {
        id: 40,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 9,
    },
    {
        id: 41,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 10,
    },
    {
        id: 42,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 11,
    },
    {
        id: 43,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 12,
    },
    {
        id: 44,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 13,
    },
    {
        id: 45,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 14,
    },
    {
        id: 46,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 15,
    },
    {
        id: 47,
        name: '',
        displayName: '',
        logo: '',
        region: 'South',
        position: 16,
    },
    {
        id: 48,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 1,
    },
    {
        id: 49,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 2,
    },
    {
        id: 50,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 3,
    },
    {
        id: 51,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 4,
    },
    {
        id: 52,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 5,
    },
    {
        id: 53,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 6,
    },
    {
        id: 54,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 7,
    },
    {
        id: 55,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 8,
    },
    {
        id: 56,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 9,
    },
    {
        id: 57,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 10,
    },
    {
        id: 58,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 11,
    },
    {
        id: 59,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 12,
    },
    {
        id: 60,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 13,
    },
    {
        id: 61,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 14,
    },
    {
        id: 62,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 15,
    },
    {
        id: 63,
        name: '',
        displayName: '',
        logo: '',
        region: 'Midwest',
        position: 16,
    },
];
