import { TBD_ADDRESS } from 'constants/network';
import { Network } from 'enums/network';
import { ContractData } from 'types/viem';

const overdropRewardsContract: ContractData = {
    addresses: {
        [Network.OptimismMainnet]: '0x74f6742e62c65Bf5d3D15477cBA1db78C8769CB5',
        [Network.Arbitrum]: '0x563c5bc1686E1284d58e3af13d60305eE8B8d3E7',
        [Network.Base]: TBD_ADDRESS,
        [Network.OptimismSepolia]: '0xa4505687368a044931C96dad55BEe2c3e4Ae2516',
    },
    abi: [
        {
            inputs: [{ internalType: 'address', name: 'target', type: 'address' }],
            name: 'AddressEmptyCode',
            type: 'error',
        },
        {
            inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
            name: 'AddressInsufficientBalance',
            type: 'error',
        },
        { inputs: [], name: 'AlreadyClaimed', type: 'error' },
        { inputs: [], name: 'ClaimsDisabled', type: 'error' },
        { inputs: [], name: 'FailedInnerCall', type: 'error' },
        { inputs: [], name: 'InvalidAmount', type: 'error' },
        { inputs: [], name: 'InvalidInitialization', type: 'error' },
        { inputs: [], name: 'InvalidMerkleProof', type: 'error' },
        { inputs: [], name: 'InvalidMerkleRoot', type: 'error' },
        { inputs: [], name: 'InvalidRecipient', type: 'error' },
        { inputs: [], name: 'InvalidSeason', type: 'error' },
        { inputs: [], name: 'NotInitializing', type: 'error' },
        {
            inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
            name: 'SafeERC20FailedOperation',
            type: 'error',
        },
        {
            anonymous: false,
            inputs: [{ indexed: false, internalType: 'bool', name: 'enabled', type: 'bool' }],
            name: 'ClaimsEnabled',
            type: 'event',
        },
        {
            anonymous: false,
            inputs: [
                { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
                { indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
            ],
            name: 'CollateralWithdrawn',
            type: 'event',
        },
        {
            anonymous: false,
            inputs: [{ indexed: false, internalType: 'uint64', name: 'version', type: 'uint64' }],
            name: 'Initialized',
            type: 'event',
        },
        {
            anonymous: false,
            inputs: [
                { indexed: false, internalType: 'bytes32', name: 'oldRoot', type: 'bytes32' },
                { indexed: false, internalType: 'bytes32', name: 'newRoot', type: 'bytes32' },
                { indexed: false, internalType: 'uint256', name: 'newRound', type: 'uint256' },
            ],
            name: 'MerkleRootUpdated',
            type: 'event',
        },
        {
            anonymous: false,
            inputs: [
                { indexed: false, internalType: 'address', name: 'oldOwner', type: 'address' },
                { indexed: false, internalType: 'address', name: 'newOwner', type: 'address' },
            ],
            name: 'OwnerChanged',
            type: 'event',
        },
        {
            anonymous: false,
            inputs: [{ indexed: false, internalType: 'address', name: 'newOwner', type: 'address' }],
            name: 'OwnerNominated',
            type: 'event',
        },
        {
            anonymous: false,
            inputs: [{ indexed: false, internalType: 'bool', name: 'isPaused', type: 'bool' }],
            name: 'PauseChanged',
            type: 'event',
        },
        {
            anonymous: false,
            inputs: [
                { indexed: true, internalType: 'address', name: 'account', type: 'address' },
                { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
                { indexed: false, internalType: 'uint256', name: 'round', type: 'uint256' },
            ],
            name: 'RewardsClaimed',
            type: 'event',
        },
        {
            anonymous: false,
            inputs: [{ indexed: true, internalType: 'address', name: 'collateral', type: 'address' }],
            name: 'RewardsCollateralUpdated',
            type: 'event',
        },
        { inputs: [], name: 'acceptOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
        {
            inputs: [
                { internalType: 'uint256', name: 'amount', type: 'uint256' },
                { internalType: 'bytes32[]', name: 'merkleProof', type: 'bytes32[]' },
            ],
            name: 'claimRewards',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
        {
            inputs: [],
            name: 'claimsEnabled',
            outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [],
            name: 'collateral',
            outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [],
            name: 'currentSeason',
            outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [
                { internalType: 'address', name: '', type: 'address' },
                { internalType: 'uint256', name: '', type: 'uint256' },
            ],
            name: 'hasClaimed',
            outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
            name: 'hasClaimedCurrentSeason',
            outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
            stateMutability: 'view',
            type: 'function',
        },
        { inputs: [], name: 'initNonReentrant', outputs: [], stateMutability: 'nonpayable', type: 'function' },
        {
            inputs: [
                { internalType: 'address', name: '_owner', type: 'address' },
                { internalType: 'address', name: '_collateral', type: 'address' },
                { internalType: 'bytes32', name: '_merkleRoot', type: 'bytes32' },
            ],
            name: 'initialize',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
        {
            inputs: [],
            name: 'lastPauseTime',
            outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [],
            name: 'merkleRoot',
            outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
            name: 'nominateNewOwner',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
        {
            inputs: [],
            name: 'nominatedOwner',
            outputs: [{ internalType: 'address', name: '', type: 'address' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [],
            name: 'owner',
            outputs: [{ internalType: 'address', name: '', type: 'address' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [],
            name: 'paused',
            outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [{ internalType: 'bool', name: 'enabled', type: 'bool' }],
            name: 'setClaimsEnabled',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
        {
            inputs: [{ internalType: 'address', name: '_collateral', type: 'address' }],
            name: 'setCollateral',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
        {
            inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
            name: 'setOwner',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
        {
            inputs: [{ internalType: 'bool', name: '_paused', type: 'bool' }],
            name: 'setPaused',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
        {
            inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
            name: 'totalClaimed',
            outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [{ internalType: 'address', name: 'proxyAddress', type: 'address' }],
            name: 'transferOwnershipAtInit',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
        {
            inputs: [
                { internalType: 'bytes32', name: 'newMerkleRoot', type: 'bytes32' },
                { internalType: 'bool', name: 'resetClaims', type: 'bool' },
                { internalType: 'uint256', name: 'newSeason', type: 'uint256' },
            ],
            name: 'updateMerkleRoot',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
        {
            inputs: [
                { internalType: 'address', name: 'account', type: 'address' },
                { internalType: 'uint256', name: 'amount', type: 'uint256' },
                { internalType: 'bytes32[]', name: 'merkleProof', type: 'bytes32[]' },
            ],
            name: 'verifyProof',
            outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
            stateMutability: 'view',
            type: 'function',
        },
        {
            inputs: [
                { internalType: 'uint256', name: 'amount', type: 'uint256' },
                { internalType: 'address', name: 'recipient', type: 'address' },
            ],
            name: 'withdrawCollateral',
            outputs: [],
            stateMutability: 'nonpayable',
            type: 'function',
        },
    ],
};

export default overdropRewardsContract;
