export const countries = [
    'Qatar', // 1
    'Ecuador',
    'Senegal',
    'Netherlands',
    'England',
    'Iran',
    'USA',
    'Wales',
    'Argentina',
    'Saudi Arabia',
    'Mexico',
    'Poland',
    'France',
    'Australia',
    'Denmark',
    'Tunisia',
    'Spain',
    'Costa Rica',
    'Germany',
    'Japan',
    'Belgium',
    'Canada',
    'Morocco',
    'Croatia',
    'Brazil',
    'Serbia',
    'Switzerland',
    'Cameroon',
    'Portugal',
    'Ghana',
    'Uruguay',
    'South Korea', // 32
];

export const countriesFlagsNames = [
    'qatar', // 1
    'ecuador',
    'senegal',
    'netherlands',
    'england',
    'ir-iran',
    'united-states',
    'wales',
    'argentina',
    'saudi-arabia',
    'mexico',
    'poland',
    'france',
    'australia',
    'denmark',
    'tunisia',
    'spain',
    'costa-rica',
    'germany',
    'japan',
    'belgium',
    'canada',
    'morocco',
    'croatia',
    'brazil',
    'serbia',
    'switzerland',
    'cameroon',
    'portugal',
    'ghana',
    'uruguay',
    'south-korea', // 32
];
